### ISSUE TITLE
Properly use styles.css without a bundler?

### ISSUE THREAD

**Issue by BeniCheni** [reach/reach-ui#102]
After reviewing the [Reach UI - Styling](https://ui.reach.tech/styling), the guide is suggesting to access:

> the styles file at `your-app/node_modules/@reach/<package-name>/styles.css`.

> Include those files however you include the rest of your stylesheets.

The project we are working with is using `style-components` as style pattern, without other popular ways to include styles by CSS.

Without a bundler (e.g. `webpack`) in projects with pattern such as CSS-in-JS, what would be the suggestion to properly include the `style.css` file when using Reach UI components?

Thank you in advance!

**Comment by hedgerh** [comment]
are you not able to just add it in as a `<link>` in the head of your index.html?  aside from the css getting ported to css-in-js, that's gonna be your best bet.

**Comment by venikx** [comment]
The documentation suggests you add a link to your project, which links to a CDN of the @reach/styles. However this is not recommend for production use-cases. 
Even if you are using CSS-IN-JS libraries these styles should still be able to get picked up, when including the css via the link (or using a bundler). 

```js
<link
  rel="stylesheet"
  type="text/css"
  href="https://unpkg.com/@reach/<package-name>@<version>/styles.css"
/>
```

Not sure if this answer your question?

**Comment by bradwestfall** [comment]
Let us know if that worked, closing for now
