### ISSUE TITLE
Aria, and keyboard interactions

### ISSUE THREAD

**Issue by dcorb** [reach/reach-ui#103]
I'm an accessibility learner, so this is more a question 
I was reading about  best practices around accessible menus:

> The solution is plain and simple: Generally, don’t use menu, menuitem, menubar, menuitemcheckbox, or menuitemradio. Only if you build something like Google Docs and deal with what you get when you press Alt+F (or Alt+Shift+F in Firefox), these are warranted. In most likely all other cases, they are not.

http://adrianroselli.com/2017/10/dont-use-aria-menu-roles-for-site-nav.html

The discussion continued here
https://github.com/w3c/aria-practices/issues/353

It seems quite clear in the latest comments of that thread that "UNLESS" you are building an "application menu" (similar to a desktop menu), then better not to use all these menu aria attributes. Because... 

> However, it actually creates an inconvenience by triggering screen reader to go into application mode and disable HTML navigation keys for screen reader.

If Reach UI Menu components are aiming to provide Application Menu Components, then I would expect to support all the key interactions expected in the application mode? Or this is expected to be implemented by the final user of the library?
Like this example, where up-down arrows expand submenus 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html
and their JS implementation is 80% about handling keyboard interactions
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/js/MenubarItemLinks.js

Again, please, these are just naive questions, I just learned today about these issues, and you have been a long time in this space  ... I found this tweet from you in 2014 :D https://twitter.com/monsika/status/483833790347739137

But it would be good to give guidance for developers interested to learn the proper way of doing accessible navigation in their apps

**Comment by dcorb** [comment]
Sorry, my bad, after checking again.. I guess that Reach UI offers only MenuButton, not menubar component. 
So you shouldn't make a top navigation menu out of multiple MenuButtons. They have different behaviors.

**Comment by venikx** [comment]
Hi @dcorb 

It might be a late response, but indeed, reach-ui only implements the MenuButton at the moment. You can find the status of the other components here: https://github.com/reach/reach-ui#development-plans

**Comment by bradwestfall** [comment]
Let us know if you have any more questions. Closing for now
