### ISSUE TITLE
MenuButton does not support nesting

### ISSUE THREAD

**Issue by NateRadebaugh** [reach/reach-ui#117]
I'm looking to use MenuButton for advanced menus that can be nested.

![image](https://user-images.githubusercontent.com/130445/52590826-f5808480-2e07-11e9-884c-bf9b0cea7cfb.png)

Button
  > Item 1
   > Item 2 Button
         > Nested Item 1
         > Nested Item 2

However, the main dropdown is dismissed when attempting to show the nested menu.

Codesandbox of what I'm using: https://codesandbox.io/s/pm9koronqx

**Comment by NateRadebaugh** [comment]
6 months later and no movement on this. Anything I can do to help this get addressed?

**Comment by bradwestfall** [comment]
Sorry @NateRadebaugh, we're making a big push right now through the issues. I hope we can get to this soon

**Comment by chancestrickland** [comment]
What you're describing here is a little beyond the scope of a MenuButton as it's designed for Reach UI. We have tentative plans for a full `Menu` component that would allow for a lot more functionality (including nesting), but we don't have firm plans for that at this time.

**Comment by NateRadebaugh** [comment]
Thanks for the update @chancestrickland is there anything I can do to help with that effort?

**Comment by chancestrickland** [comment]
If you'd like to propose an API for a full aria menu, that is typically how we begin the design process for new components! I can't guarantee we'll ultimately decide to include it, but we are discussing it as a possibility. `Menu` is currently marked with a ❓ on the todo list which basically means we're still considering it but it *might* be beyond the scope of what we're doing here!
