### ISSUE TITLE
MenuItem cannot be styled with emotion (or other css-in-js solutions?)

### ISSUE THREAD

**Issue by bmcmahen** [reach/reach-ui#119]
The problem occurs when you try to wrap the `MenuItem` component.

```jsx
export function DropdownItem({ children, ...props }: MenuItemProps) {
  return (
    <MenuItem
      css={{
        width: "100%",
        display: "block",
      }}
      {...props}
    >
      {children}
    </MenuItem>
  );
}
```

When the `MenuList` component goes to render the list and cycle through its children elements, it fails to count the above as a focusable element. 

```jsx
let focusableChildrenTypes = [MenuItem, MenuLink];
let isFocusableChildType = child => focusableChildrenTypes.includes(child.type);
```

This fails because our new child type isn't included in the above array. As a result, the `DropdownItem` component is still rendered, but not using the `cloneElement` function and the necessary props are not passed to our `DropdownItem` component. 

Any idea on a solution here?

**Comment by amberleyromo** [comment]
Same: https://github.com/reach/reach-ui/issues/23#issuecomment-464367615

**Comment by nulladdict** [comment]
[This PR](https://github.com/reach/reach-ui/pull/79) seems to be the case

**Comment by grrowl** [comment]
ryan florence linked to this on twitter, which might help inform this conversation:

https://gist.github.com/ryanflorence/10e9387f633f9d2e6f444a9bddaabf6e

https://github.com/reach/reach-ui/blob/menu-button-rewrite/packages/adapter/src/descendants.js

**Comment by chancestrickland** [comment]
As of v0.7.0, you should be able to use styled components for MenuItem or MenuLink components either by using the `as` prop as we've suggested before, or the normal way of wrapping your components via `styled(MenuItem)`. Check out the updated examples as needed. cc @amberleyromo

**Comment by karlhorky** [comment]
Hm... this didn't really address the original issue - styling using Emotion with the `css` prop.

Is there a way to do this with Reach UI?
