### ISSUE TITLE
Conditional MenuItems throws off children

### ISSUE THREAD

**Issue by kevee** [reach/reach-ui#121]
Could be related to #114 and #119:

When using a conditional to control the display of menu items, like the sample below, an [error is thrown here](https://github.com/reach/reach-ui/blob/fdfe5e64f122224cfd525213b516684b3fdbde42/packages/menu-button/src/index.js#L25).

```javascript
<Menu>
        <MenuButton>Actions</MenuButton>
        <MenuList>
          <MenuItem>Download</MenuItem>
          {false && <MenuItem>Should never display</MenuItem>}
          <MenuItem>Foo</MenuItem>
        </MenuList>
      </Menu>
```

Here's a sample:
https://codesandbox.io/s/4qyv4yzlxw

**Comment by amberleyromo** [comment]
I believe I have an issue possibly related to this?

When using a combination of `<MenuItem/>` elements that are explicitly defined, with `<MenuItem/>` elements that are generated by mapping, the focus hover gets screwed up (though the select on individual items works just fine).

(example snippet and gif)

```
<Menu>
      {sourceOrganizations && (
        <MenuButton>
          {selectedOrg ? selectedOrg : `All`}
          <MdArrowDropDown />
        </MenuButton>
      )}
      <MenuList>
        <MenuItem onSelect={chooseAllOrgs}>All</MenuItem>
        {sourceOrganizations.map(org => (
          <MenuItem
            key={org.id}
            onSelect={() => {
              changeOrg(org.name)
            }}
          >
            {org.name}
          </MenuItem>
        ))}
      </MenuList>
    </Menu>
```

![reach-menu-bug](https://user-images.githubusercontent.com/3461087/54292388-19a4c200-457c-11e9-8436-864ff4224aec.gif)
