### ISSUE TITLE
Uncaught TypeError: forwardRef is not a function

### ISSUE THREAD

**Issue by sjelfull** [reach/reach-ui#126]
Trying to add a ref to `DialogOverlay`, and getting this error. We're on React 16.5.

![image](https://user-images.githubusercontent.com/10508/54605107-c84b7580-4a48-11e9-9830-dbcd9855ff5b.png)

Looks like `forwardRef` now returns a object instead of a function, and on this line your using it as a function: https://github.com/reach/reach-ui/blob/master/packages/dialog/src/index.js#L98

Would it be correct to change it into something like:
```javascript
ref: function ref(node) {
    if (forwardRef && forwardRef.current !== null) {
        return forwardRef;
    }
}
```

How could I make it easy for you to tag a new release that fixes this? It's currently a blocking issue for us.

**Comment by mikeLspohn** [comment]
I'm having the same problem using React 16.8.0. Excited to use this when it's fixed!

**Comment by jdfm** [comment]
This is an issue in the @reach/tooltips component as well. I've had to pass a function like `node => myRef.current = node` in that case.

**Comment by chancestrickland** [comment]
This should be fixed in our next release 👍
