### ISSUE TITLE
Error in example on alert-dialog docs

### ISSUE THREAD

**Issue by amcvitty** [reach/reach-ui#128]
Quick FYI

I see this 

>Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

when I click the "delete something" button on https://ui.reach.tech/alert-dialog/

**Comment by timlogemann** [comment]
@ryanflorence there seems to be a breaking bug in v0.1.2.

We're currently using it in an app we're building. I have version v0.1.1 installed and a coworker has v0.1.2. My coworker gets all these errors when using the alert-dialog, I can use it without problems.

We also have it in our production build of the app that has v0.1.2 installed. Downgrading to v0.1.1 resolves the issues.
