### ISSUE TITLE
@reach/skip-nav types not exported

### ISSUE THREAD

**Issue by SleeplessByte** [reach/reach-ui#131]
Because of [this block](https://github.com/reach/reach-ui/blob/master/packages/skip-nav/package.json#L18) in package of json, the `index.d.ts` is not present on npm.

I also suggest adding the `types` key to package.json

**Comment by hedgerh** [comment]
looks like every package needs the `types` key from the look of it

**Comment by SleeplessByte** [comment]
It doesn't _need_ it, but it makes resolution straightforward 🚀 😁

**Comment by petejohansonxo** [comment]
The type files need to get added to the `files` section too, so they get packaged when published.

**Comment by chancestrickland** [comment]
This was updated...not sure when, but it was updated! 😅
