### ISSUE TITLE
Dialog: onDismiss fires when selecting text and releasing mouse outside of modal

### ISSUE THREAD

**Issue by clight-fastly** [reach/reach-ui#132]
When using onDismiss, simply releasing a mouse click outside causes onDismiss to fire. Is this behavior intended? It causes issues when someone tries to select text inside.

Behavior recorded from https://ui.reach.tech/dialog#dialog-ondismiss example

![dialog-on-dismiss](https://user-images.githubusercontent.com/43175846/55256745-d4df8300-522b-11e9-9c6b-c48a9a6ede00.gif)

**Comment by chancestrickland** [comment]
This should be fixed!
