### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by collegeimprovements** [reach/reach-ui#138]
Is it advisable to build accordion with <Tab> Component or should we wait for the explicit accordion component ?

**Comment by stereobooster** [comment]
There is https://github.com/springload/react-accessible-accordion

**Comment by stereobooster** [comment]
Shameless plug https://github.com/stereobooster/react-accessible-accordion

**Comment by chancestrickland** [comment]
See https://github.com/reach/reach-ui/issues/167#issuecomment-541807786
