### ISSUE TITLE
Critical rendering issue with AlertDialog / AlertDialogContent

### ISSUE THREAD

**Issue by coreylight** [reach/reach-ui#139]
Can't seem to get base functionality going:

Reproduction:
https://codesandbox.io/s/vy7pxoq697

**Comment by andytuba** [comment]
Previews on https://ui.reach.tech/alert-dialog are also throwing errors:

> Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by osartun** [comment]
Same error here.
However, I already read the code and don't understand why it would say something would be `undefined` there. Can't figure out where the issue comes from.

**Comment by cweeii** [comment]
I've noticed something strange too that when I do an explicit install of @reach/utils instead of `yarn bootstrap` and linking, the lib folder and `<IdConsumer> is there.

**Comment by chancestrickland** [comment]
Closing, as this should be fixed. See https://github.com/reach/reach-ui/issues/133 for more info.
