### ISSUE TITLE
Is it possible to hide a tab panel when selected again? 

### ISSUE THREAD

**Issue by daydream05** [reach/reach-ui#140]
First off, this is library is amazing! 

I have a component that looks like this:

![ui sample](https://user-images.githubusercontent.com/11723413/56148376-2bf98d80-5f78-11e9-9ca6-7320de19cff7.jpg)

What i would like to do is if I select the tab that I currently selected, the tabpanel would be hidden.

Would this be as simple as setting all tabs to `display: none`?

**Comment by scottaohara** [comment]
sounds like you're looking for a different component (a stylized accordion for instance), imo.  a tab widget is always meant to have a persistently selected `tab` and opened associated `tabpanel`.

**Comment by bradwestfall** [comment]
Yea I'm not sure if the UI you showed us is appropriate for tabs. In any case, `<Tab>` has `onChange` which you might be able to use to set your own state to know what's selected and then conditionalize the display of a panel?

Closing for now, let us know how it worked out
