### ISSUE TITLE
Element IDs are not valid to be used as selectors

### ISSUE THREAD

**Issue by gnapse** [reach/reach-ui#147]
The `Tabs` component dynamically generates some IDs for its elements that are not valid when  parsed by `document.querySelector` in a css selector. Take this example from a quick test in the browser's js console:

```
> document.querySelector('#tab:5bfmna4727o:0')
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#tab:5bfmna4727o:0' is not a valid selector.
```

I discovered this not because I was attempting myself to select these elements in this way, but because the js console of [this page](https://ui.reach.tech/tabs) was already showing these errors. Not sure what code was attempting to do this (either on that page or maybe a browser extension of mine) and now after a refresh I cannot reproduce immediately. Probably not a big deal since this is something that's not supposed to be happening, but I guess it wouldn't hurt to change these selectors to be something that can be parsed corrected as a selector anyway.

**Comment by stereobooster** [comment]
Ids are valid see http://xahlee.info/js/html_allowed_chars_in_attribute.html, but you need to escape CSS specifier

```js
document.querySelector('#tab\\:5bfmna4727o\\:0')
```

**Comment by gnapse** [comment]
Ok, great. Thanks for clarifying that. I can close this then.

**Comment by Yevhenii2** [comment]
You can do this:
```
document.querySelector(`[id="tab:5bfmna4727o:0"]`)
```
It worked for me. but I used a variable.
```
document.querySelector(`[id="${myId}"]`)
```
