### ISSUE TITLE
Tooltip:  arria attributes do not have valid values

### ISSUE THREAD

**Issue by moonmeister** [reach/reach-ui#158]
Lighthouse is complaining about invalid aria values on tooltip.

[aria-*] attributes do not have valid values

```html
<svg class="icon-module--icon--27QhR" viewBox="0 0 24 24" aria-labelledby="tooltip:1" data-reach-tooltip-trigger="">
  <path d="the long path is here"></path>
</svg>
```

Thanks for all the work on this, this made the tooltip project I've been putting off real quick.

**Comment by chancestrickland** [comment]
This should be fixed with https://github.com/reach/reach-ui/commit/85e41a91ba9b46f6231b1d419af61cd70f1e9941
