### ISSUE TITLE
❓ tooltip: should wrap onBlur instead onFocus?

### ISSUE THREAD

**Issue by rexpan** [reach/reach-ui#160]
Is this a mistake or intention for wrap `onBlur` with `onFocus`? 
https://github.com/reach/reach-ui/blob/99c687b6d9eca174133e0f5beadafd1842be2214/packages/tooltip/src/index.js#L343

**Comment by chancestrickland** [comment]
Fixed in https://github.com/reach/reach-ui/pull/226
