### ISSUE TITLE
Scroll not locked when moving mouse out of window after scroll (Chrome, macOS)

### ISSUE THREAD

**Issue by karlhorky** [reach/reach-ui#161]
#111 added scroll locking to the background elements.

It works well except for the following case (admittedly, an edge case):

1. Scroll a lot with a mouse/setup that allows acceleration scrolling (ex. I have a Magic Mouse)
2. Move mouse outside of window quickly afterwards
3. Watch the locked background scroll with the left over acceleration

![Kapture 2019-05-03 at 13 13 43](https://user-images.githubusercontent.com/1935696/57134881-d14d9780-6da7-11e9-9de0-bd9a0d41301d.gif)

I have also added an issue upstream: theKashey/react-remove-scroll#4

**Comment by theKashey** [comment]
I've tried Chrome, Sarafi and FF, with trackpad and magic mouse - could not confirm the issue, but I know how to fix it, even in this case :)

**Comment by karlhorky** [comment]
@theKashey Seems like it is fixed with your commit theKashey/react-remove-scroll@c9c320935c5cb0adb277d7dd5359295b80b6bf52. I suppose this is version `1.1.5` of `react-remove-scroll`?

**Comment by theKashey** [comment]
You are absolutely right.

**Comment by karlhorky** [comment]
Ok then now all that remains is that the version be bumped for the dialog. Opened #164 for this.

**Comment by karlhorky** [comment]
Closed by @chancestrickland in #164
