### ISSUE TITLE
Tab buttons need `type='button'`

### ISSUE THREAD

**Issue by flybayer** [reach/reach-ui#165]
I'm launching the Dialog from inside a form. The default tab buttons have the default, implicit type of "submit" so clicking a tab submits the form.

Workaround is manually set `type='button'` on each `<Tab>`

**Comment by olistic** [comment]
I just run into this issue. Happy to submit a PR for this, just lemme know!

**Comment by chancestrickland** [comment]
Fixed in https://github.com/reach/reach-ui/pull/304

**Comment by 1000hz** [comment]
this seems to have regressed in https://github.com/reach/reach-ui/commit/a2ab2be8b0ca122e3fa03a00e24d78b757b48e35

**Comment by chancestrickland** [comment]
Per my note in the linked PR, this was removed because our type check isn't reliable. It might still be worth it to have this as a default, but if a custom component is passed to `as` then the end user will still have to manually set `type="button"` if a button element is ultimately created.
