### ISSUE TITLE
[Proposal] Collapsible Sections

### ISSUE THREAD

**Issue by venikx** [reach/reach-ui#167]
First of all great library and initiative. I've come to be interested in trying to be more a11y-friendly, but I'm still learning. So using the lib has helped me not to worry about common use-cases. 

I have use-case that is currently not covered by any of the components (unless you count the component-component), but that seems a bit hacky nowadays with hooks. 
It could be more helpful to show you an [interesting link](https://inclusive-components.design/collapsible-sections/) I've found about inclusive components, when I was trying to look for an a11y friendly version of an "Accordion", "Collapsible Panel", ... 

Since there is already an initiative going here to make some common components a11y friendly, I was asking myself if you think it would be a good fit for reach-ui to support this type of component. 

I'm willing to work on a PR myself, as I'm probably going to need one anyways for my project and I thought it would be nicer to add it to reach-ui in stead of developing my own lib.

Thanks!

**Comment by ritchieanesco** [comment]
+1 for this feature. Sometimes you want the submenu to be visible directly under its parent button.

**Comment by nhunzaker** [comment]
I recently implemented the solution linked to above from [Inclusive Components](https://inclusive-components.design/collapsible-sections/).

Has there been an effort made towards this? I'd be happy to send a PR with my React implementation.

**Comment by chancestrickland** [comment]
> Has there been an effort made towards this? I'd be happy to send a PR with my React implementation.

I've got a branch in the works, not quite ready for a PR but I sent you a DM if you'd like to collaborate or provide some feedback.

**Comment by chancestrickland** [comment]
@nhunzaker We have a `dev-accordion` branch published now. It's not yet released and we're still working through internal feedback/revisions before it goes to alpha, but feel free to take a look and submit PRs if you see anything that needs improvement. Closing this issue for now and we'll keep the conversation going with a PR when it's ready!
