### ISSUE TITLE
React components as Tooltip children?

### ISSUE THREAD

**Issue by chasemccoy** [reach/reach-ui#171]
Using `@reach/tooltip`, and getting a lot of errors about `getBoundingClientRect` being undefined whenever I nest a React component within the tooltip:

```jsx
<Tooltip label='Hello!'>
  <Box>foo</Box>
</Tooltip>
```

![Screen Shot 2019-05-10 at 1 03 34 PM](https://user-images.githubusercontent.com/8663074/57547463-29464a00-7324-11e9-8f5b-fcef4e403086.png)

If I pass just a regular HTML element, it works just fine. But it seems like components should be supported as children, no?

**Comment by ericchernuka** [comment]
I ran into this today. The underlying component must be able to the ref that Tooltip is cloning onto the child component.  I ended up just modifying my functional component to use forwardRef.

If not, you might have to go a low-level so that you can use the useTooltip hook and pass the ref using another convention such as `innerRef` that has become common.

For more info on refs check the React docs here: https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-class-component

**Comment by chasemccoy** [comment]
@ericchernuka Hmm, this makes sense but I am not sure exactly what I need to do to solve this.

Here's the code for my tooltip component:

```jsx
const Tooltip = (props: TypeProps) => {
  const {
    label,
    position = "bottom",
    ariaLabel,
    children,
    zIndex = 1,
    qa,
    ...rest
  } = props;

  const [trigger, tooltip] = useTooltip({ DEBUG_STYLE: false });

  return (
    <React.Fragment>
      {React.cloneElement(children, trigger)}

      <ReachTooltip
        {...tooltip}
        label={label}
        ariaLabel={ariaLabel || label}
        position={positions[position]}
        zIndex={zIndex}
        {...rest}
      />
    </React.Fragment>
  );
};
```

I am using the hook, but I am not sure what ref I am supposed to pass where.

**Comment by ericchernuka** [comment]
The `trigger` from useTooltip owns the ref. It can either be passed in my the ref key or you can let useTooltip initialize one for you. It then gets cloned into the child component. So the child component, `<Box />` in your case needs to be able to forward the ref to a DOM node.

**Comment by chasemccoy** [comment]
Ah, I see. So, no matter what I do, this will require source changes to the child component (i.e. this will never work with a component that doesn't forward refs?)

**Comment by ericchernuka** [comment]
Pretty sure that’s correct. My implementation was broken today until I added ref forwarding.

**Comment by chasemccoy** [comment]
Gotcha. Thanks for the help! This is kind of a bummer because we can't control what the consumer of the component passes in, and if they don't pass a component that forwards refs, it will break in a really weird way.

**Comment by chasemccoy** [comment]
I ended up solving this by doing something like this:

```jsx
return (
    <React.Fragment>
      <Box {...trigger}>
        {React.cloneElement(children)}
      </Box>

      <TooltipContainer
        {...tooltip}
        label={label}
        ariaLabel={ariaLabel || label}
        position={positions[position]}
        zIndex={zIndex}
        {...rest}
      />
    </React.Fragment>
  );
```

Basically wrapping the children of the tooltip in a container that forwards refs (I updated `Box` to forward refs). Don't love wrapping the children in an unnecessary element, but it works!

**Comment by raunofreiberg** [comment]
This is a major shortcoming, imo. While building a design system, I cannot guarantee that the `children` will be components that forward refs.

**Comment by ryanflorence** [comment]
```
const Box = forwardRef((props, ref) => {
  return <div ref={ref}/>
})
```

Tooltip needs a ref so it can manage focus, so you need to forward it.

If you don’t like that (seems weird, but okay) drop down to the useTooltip hook and spread the return values wherever you need it.

But there’s no need to start wrapping for one off situations. Forward Ref is what you want.

**Comment by rajjejosefsson** [comment]
@ryanflorence is there anything in the docs stating that forwardRefs needs to be used? I see a lot of people having the same issue.

**Comment by raunofreiberg** [comment]
@ryanflorence I've tried doing what you suggested, but it doesn't seem to work on the second example with `<Span />`

https://codesandbox.io/s/naughty-sun-7q7bo

**Comment by ericchernuka** [comment]
@raunofreiberg Since the tooltip clones it's children, you have to ensure you pass all the props onto the underlying component. So in your example, you need to spread the props from `forwardRef` onto the span so that all the `on*` handlers still work.  I've forked your example with a working one found here: https://codesandbox.io/s/optimistic-benz-ldg49?fontsize=14

**Comment by brookback** [comment]
I just got here after some time of *"Why isn't the tooltip showing at my button?!"*. Turns out it doesn't work on function components at all.

I think the docs should totally mention this, as it's pretty severe.

**Comment by ericchernuka** [comment]
@brookback Not sure why you're saying it doesn't work, but you may need to wrap your functional component in `forwardRef` and pass that ref to the child component so that the tooltip has something to attach to.

As an aside, I can make a PR that indicates that the underlying component requires a `forwardRef` if people are ok with that?

**Comment by brookback** [comment]
@ericchernuka Sorry – it worked after I found my way here and read instructions on `forwardRef` :) Just saying the docs could need some love around this.

This shows up in the console at Codesandbox (although not for me locally 🤔):

<img width="934" alt="image" src="https://user-images.githubusercontent.com/30257156/75049057-d4964900-54c9-11ea-8bb5-8ac0f73fd056.png">

So it looks like it's taken care of already.

**Comment by NickyMeuleman** [comment]
> @ryanflorence I've tried doing what you suggested, but it doesn't seem to work on the second example with `<Span />`
> 
> [codesandbox.io/s/naughty-sun-7q7bo](https://codesandbox.io/s/naughty-sun-7q7bo)

What's the proper way to do this?
I ran in to the same situation.
Ended up wrapping the `Span` component in a `<span>` (and deleted the one rendered as wrapping element in the component and replaced it by a fragment).
This works, and results in what appears to be functionally identical code, but isn't.

**Comment by ryanodd** [comment]
I haven't been able to find a way to use a class component as a tooltip child yet. Does anyone know a way?

[Here's a simple demo with a tooltip wrapping a class component, functional component, and a basic HTML element](https://codesandbox.io/s/stupefied-euler-ih9inq?file=/src/App.tsx)

**Comment by karlhorky** [comment]
Ohh interesting, looks like you don't even need refs anymore with the latest `@reach/tooltip` (as long as you pass the props along):

```ts
function Span(props) {
  return <span {...props}>{props.children}</span>;
}

function App() {
  return (
    <>
      <div>
        <Tooltip label="Bar">
          <Span>Hey Span</Span>
        </Tooltip>
      </div>
    </>
  );
}
```

![Screen Shot 2022-06-12 at 12 44 22](https://user-images.githubusercontent.com/1935696/173229454-735eea56-64be-4791-ae79-7d71d802907f.png)

https://codesandbox.io/s/optimistic-mclaren-9vrs05?file=/src/index.js

**Comment by karlhorky** [comment]
Ah, this appears to work at first, but then fails without `React.forwardRef` - same "You need to place the ref" warnings in the console:

![Screen Shot 2022-06-12 at 13 05 36](https://user-images.githubusercontent.com/1935696/173230133-3403fa82-7c6f-4503-a14f-bd50690723e5.png)

![Screen Shot 2022-06-12 at 13 05 56](https://user-images.githubusercontent.com/1935696/173230135-fb88e2c8-ad96-4dcb-8587-f9693a9b297e.png)

**Comment by Raghav1400** [comment]
Please ensure that the child node of Tooltip accepts onMouseEnter, onMouseLeave, onFocus, onClick events.
