### ISSUE TITLE
MenuButton(Dropdown) question

### ISSUE THREAD

**Issue by VladSez** [reach/reach-ui#173]
Hello! I need some help. I want MenuList to be equal width with MenuButton. How can i do this ? Also need responsiveness

![Снимок экрана 2019-05-15 в 18 01 15](https://user-images.githubusercontent.com/16666234/57786238-d01f5180-773b-11e9-94bf-c679bb74c041.jpg)

![Снимок экрана 2019-05-14 в 15 06 49 (2)](https://user-images.githubusercontent.com/16666234/57784087-fe029700-7737-11e9-9a6e-ccb699804fc0.jpg)

**Comment by VladSez** [comment]
![Снимок экрана 2019-05-14 в 15 06 49](https://user-images.githubusercontent.com/16666234/57784035-e2978c00-7737-11e9-88bf-762264181053.jpg)

**Comment by gillerg8** [comment]
Do you have a set width for MenuButton?

**Comment by VladSez** [comment]
the width is set to 100% of the column
<img width="1381" alt="Снимок экрана 2019-05-15 в 17 59 37" src="https://user-images.githubusercontent.com/16666234/57785953-51c2af80-773b-11e9-9c65-bf1a2a92b8bc.png">

**Comment by gillerg8** [comment]
Can you put your issue in a https://codepen.io/? What happens when you set the width of MenuList to 100%?

**Comment by VladSez** [comment]
<img width="1070" alt="Снимок экрана 2019-05-15 в 19 05 07" src="https://user-images.githubusercontent.com/16666234/57790907-6192c180-7744-11e9-9eea-c3587185bdc7.png">

**Comment by VladSez** [comment]
https://codesandbox.io/s/x317l35nxp

**Comment by gillerg8** [comment]
Hey @VladSez, in your style.css file you were changing the width to be 100% on [data-reach-menu] which seemed to be causing this issue:
![Here is your culprit](https://user-images.githubusercontent.com/7545331/57796654-a6076880-7716-11e9-8243-843efdf1d12b.png)

Seems to be working as expected when removing this from your style.css file:
https://codesandbox.io/embed/eager-lederberg-97wrx

**Comment by VladSez** [comment]
Then how can i set MenuList to be equal width with MenuButton?

**Comment by talyaacovi** [comment]
I am having the same issue, trying to set a specific width on MenuButton and the MenuList is not also conforming to that width. It only works if I also set the width on the [data-reach-menu] div, which i can only do in console when inspecting the element.

**Comment by VladSez** [comment]
@talyaacovi @raunofreiberg so, there is an issue with a menu-button package. At /packages/menu-button/src/index.js
this if statement is causing the issue with width

![image](https://user-images.githubusercontent.com/16666234/62011086-4e589500-b17c-11e9-9aaa-eb52e111fc3e.png)

**Comment by bradwestfall** [comment]
@VladSez do you want that removed?

**Comment by VladSez** [comment]
@bradwestfall  from my point of view, yes it should be removed. Also, could you explain, why this code was added to the package? What's the purpose?

**Comment by bradwestfall** [comment]
@VladSez I just wanted to clarify, we're starting to ramp up a bunch of work on Reach UI and so we're going though and fixing a bunch of issues. I was just labeling them and asking clarification questions as needed, it's actually @chancestrickland or @mjackson who will be making all the changes

**Comment by chancestrickland** [comment]
@VladSez I'm going to look into this, but just FYI what your screenshot is showing is actually a misuse of menu button. You should not be using menu button to create custom select menus, as it uses completely different aria roles and keyboard behavior than what users would expect from a select.

We are working on a listbox for this, but in the mean time you may want to use a native HTML5 select menu or look for an alternative package for this specific use case.

**Comment by Silverwolf90** [comment]
Have just ran into this issue as well. I was expecting that the menu list would always inherit the width of the menu button unless styled otherwise.

Is the conditional application of the width intended? Or is that bug?

**Comment by VladSez** [comment]
@Silverwolf90 could you please check the comment above?

**Comment by Silverwolf90** [comment]
@VladSez I read through the thread before posting my initial comment. Unless I've missed something, there hasn't been a clarification on the intended behavior yet.

**Comment by chancestrickland** [comment]
FYI, in 0.7.0 you can use the position prop along with one of our positioning functions in `@reach/popover` to achieve this.

```jsx
import { positionMatchWidth } from "@reach/popover";

function MyMenu() {
  return (
    <Menu>
      <MenuButton id="example-button">
        Actions <span aria-hidden="true">▾</span>
      </MenuButton>
      <MenuPopover position={positionMatchWidth}>
        <MenuItems>
          <MenuItem onSelect={action("Download")}>Download</MenuItem>
          <MenuItem onSelect={action("Copy")}>Create a Copy</MenuItem>
          <MenuItem onSelect={action("Mark as Draft")}>Mark as Draft</MenuItem>
          <MenuItem onSelect={action("Delete")}>Delete</MenuItem>
        </MenuItems>
      </MenuPopover>
    </Menu>
  )
}
```
