### ISSUE TITLE
@reach/tooltip IE 11 is not supported

### ISSUE THREAD

**Issue by andrew-humu** [reach/reach-ui#174]
## Overview

Tooltips don't appear to be visible in any case in IE11.

It looks like the only issue is that IE11 doesn't support `window.scrollX` or `window.scrollY`.

https://developer.mozilla.org/en-US/docs/Web/API/window/scrollX

## Version tested

`"@reach/tooltip": "0.2.0"`

**Comment by ryanflorence** [comment]
thanks! fixed and released.

**Comment by andrew-humu** [comment]
Amazing, thank you!
