### ISSUE TITLE
reach ui dialog not announcing to screen readers?

### ISSUE THREAD

**Issue by westbrookc16** [reach/reach-ui#179]
I'm not sure how to say this tactfully, your dialog modal seems to be not performing well with screen readaers. I noticed this on your demo site, especially infirefox. In firefox, latest version, when opening hte demo dialog on your site with nvda or jaws, the text of the page disappears. Chrome is  little better, I can still see the text, but there is no announcement of dialog, etc. like I would expect. I thought this was just a problem with your demo site since you advertise accessibility so prominently, but I tried to use it and noticed the same issues. Is it something with react 16?

**Comment by hedinne** [comment]
Fixed in 38eeea8529f652d380505cb21bd4f7e64208adc3
