### ISSUE TITLE
publishing appears to have missed portal

### ISSUE THREAD

**Issue by luke-john** [reach/reach-ui#18]
Hey, this library looks really amazing, thanks for your excellent work on this.

We were looking at trying out the dialog on one of our products and ran into an issue where the latest published version of `@reach/dialog` is marked in [its package.json](https://github.com/reach/reach-ui/blob/master/packages/portal/package.json) as having `@reach/portal@^0.1.0` as a dependency.

On npm the latest published version of `@reach/portal` appears to be `0.0.2` which was published ~1 month ago. https://www.npmjs.com/package/@reach/portal

From looking at the checked in `package.json` for `@reach/portal` it appears the version has been bumped to `0.1.0` in the [commit titled Publish](https://github.com/reach/reach-ui/commit/9dfc1e5a6972fc000d55b4688a3d78ae1cbc1d5e) which I'm assuming was generated by lerna.

It appears publishing is currently a manual process, so I'm unsure what commands have resulted in portal not being published.

**Comment by ryanflorence** [comment]
Thanks, yes there was a hiccup when I published this week (publishing @scoped packages doesn't work from the lerna the first time). I didn't realize the error caused other packages to not be published, too! Thanks.

**Comment by ryanflorence** [comment]
😅 Just manually published:

- portal
- menu-button
- rect
- window-size

Shouldn't have this hiccup again (at least with these packages) and they'll be published w/ my normal flow.

Thanks again.
