### ISSUE TITLE
Dialog is closed if a drag ends out of the dialog

### ISSUE THREAD

**Issue by tmcw** [reach/reach-ui#186]
Reach is awesome! Thanks for working on it, @ryanflorence 

We're switching to reach/dialog, and one thing I'm running into is that, when we have interfaces that involve dragging _inside_ of a dialog - like, in one case, a crop editor for people changing user avatars, if someone accidentally ends a drag outside of the modal, the modal is closed.

Closing the modal by clicking outside of it is a good behavior, but I don't think that anyone intends to close a modal by starting a drag inside of it and ending that drag event outside.

**Comment by maxmalov** [comment]
Looks like a duplicate of https://github.com/reach/reach-ui/issues/132

**Comment by tmcw** [comment]
Yep, that's the same issue.
