### ISSUE TITLE
Manual tab activation?

### ISSUE THREAD

**Issue by ZebraFlesh** [reach/reach-ui#188]
It looks like the Tabs component supports automatic activation out of the box. Is there a way to make it work with manual activation?

**Comment by bradwestfall** [comment]
Can you elaborate on this a little more? "Manual activation"?

**Comment by ZebraFlesh** [comment]
Sure, here's the manual activation example: https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html

If the contents of every tab panel are the result of an ajax call, then you don't want to automatically activate every tab. Instead you want the user to be able to navigate to the desired tab and then manually activate it.

**Comment by bradwestfall** [comment]
Thanks @ZebraFlesh, I just wanted more info for @mjackson and @chancestrickland who are going through issues

**Comment by oyeanuj** [comment]
@ZebraFlesh Have you found a workaround for manual activation in the meantime?

@chancestrickland Big +1 for this!

**Comment by ZebraFlesh** [comment]
No work around at this time that I’m aware of

**Comment by chancestrickland** [comment]
BTW this was introduced with the `keyboardActivation` prop. https://reacttraining.com/reach-ui/tabs#tabs-keyboardactivation

**Comment by ZebraFlesh** [comment]
Awesome, thank you for this!
