### ISSUE TITLE
Auto ID 404 (page not found)

### ISSUE THREAD

**Issue by nickmccurdy** [reach/reach-ui#191]
If you click on Auto ID in the sidebar or visit https://ui.reach.tech/auto-id, you will get a 404 (page not found) error

**Comment by filipdanic** [comment]
Still a 404 error. Referenced here: https://github.com/reach/reach-ui/blob/1ef8b0c541df1eaf9bb25f6ab5a46dda095fd22b/www/src/components/layout.js#L169 but no example page actually exists.

**Comment by chancestrickland** [comment]
Fixed in https://github.com/reach/reach-ui/pull/183.
