### ISSUE TITLE
Tooltips flicker when modal dialog is added

### ISSUE THREAD

**Issue by bvaughn** [reach/reach-ui#193]
Example usage are the buttons inside of this modal:
https://github.com/bvaughn/react-devtools-experimental/blob/master/src/devtools/views/Components/ComponentFiltersModal.js

![Tooltips flickering on modal display](https://user-images.githubusercontent.com/29597/59133076-c00a2480-892b-11e9-9f11-46156dc8d0af.gif)

Maybe related to #166. Let me know if you'd like me to create a smaller repro. Kind of busy at the moment but I can make the time!

**Comment by FlipgridMartin** [comment]
I ran unto a similar issue, and this it's related to the `auto-id`. On first render, all of the tooltip IDs are `tooltip:null`, and then update to `tooltip:N` on the next render. Looking into why now 🙂

**Comment by FlipgridMartin** [comment]
Here's a repro for the `auto-id` bug: https://codesandbox.io/s/reach-auto-id-null-repro-0w8ki

**Comment by chancestrickland** [comment]
@bvaughn Prioritizing this (a little late but we'll get there). Did you happen to find a workaround for your particular case?

I do believe @FlipgridMartin is correct about auto-id. We're reviewing a few better solutions there.

**Comment by FlipgridMartin** [comment]
@chancestrickland FWIW, we didn't come up with a workaround. The visible tooltips last for ~20-100ms in most instances, and since our issue is happening when a dialog was being opened, they were barely visible before they went away.

**Comment by bvaughn** [comment]
> @bvaughn Prioritizing this (a little late but we'll get there). Did you happen to find a workaround for your particular case?

@chancestrickland No, but it also didn't seem high enough priority to invest much time into (assuming it would eventually be fixed upstream)
