### ISSUE TITLE
[Tooltip] jumpy positioning in concurrent mode

### ISSUE THREAD

**Issue by aweary** [reach/reach-ui#197]
Noticed this while messing with some concurrent mode stuff using `ReactDOM.unstable_createRoot`. 

I know, I know, "concurrent mode isn't released yet", but eventually this will be relevant 🙃

[Here's a minimal repro for the bug](https://codesandbox.io/s/reach-tooltip-concurrent-mode-bug-418y8). Hover over the "Home" button and you'll see that the initial tooltip jumps in from the right.

If you set the `useConcurrentMode` variable to `false` the problem goes away. I tested this with a build of React from `master` too and it had the same issue.

_________

![2019-06-08 21 42 26](https://user-images.githubusercontent.com/6886061/59155103-5f1b4300-8a36-11e9-9dfa-5fb5ab68a988.gif)

(The gif makes it look like it's only happening sometimes, but that's just because its dropping the frame)

**Comment by aweary** [comment]
Removing the wrapping `Portal` around `TooltipContent` seems to fix it 👀

**Comment by bradwestfall** [comment]
Closing, Let us know if you'd like to see any changes
