### ISSUE TITLE
[ComboBox] optionsRef approach unstable

### ISSUE THREAD

**Issue by Andarist** [reach/reach-ui#199]
Pushing to the `optionsRef` in `ComboboxOption` is unstable - if we trigger a rerender on the Option without triggering `ComboboxList` rerender (which clears `optionsRef`) we might just push and push onto it making any logic based on that array unstable.

**Comment by amannn** [comment]
Same is true when `ComboboxList` renders, but `ComboboxOption` doesn't due to `React.memo`.

I guess this is related: https://github.com/reach/reach-ui/issues/354

**Comment by chancestrickland** [comment]
Can either of you share a CodeSandbox link the demos the problems with our approach?

**Comment by Andarist** [comment]
@chancestrickland I couldn't reproduce it **right now** because of this https://github.com/reach/reach-ui/pull/379 , but once you fix that it will be possible to reproduce it with code like this:
https://codesandbox.io/s/loving-margulis-lx5zs
