### ISSUE TITLE
menu: NVDA + Firefox doesn't count links in "list [x] items"

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#2]
If you've got a NavLink NVDA doesn't count it:

```jsx
<MenuList>
  <MenuItem/>
  <MenuItem/>
  <MenuLink/>
</MenuList>
```

It announces "List, 2 items".

**Comment by chancestrickland** [comment]
I believe this *may* be fixed since updating Menu Button to meet the WCAG 1.2 spec. I'll test for sure ASAP.
