### ISSUE TITLE
MenuButton disappears when hover all but first child [IE 11]

### ISSUE THREAD

**Issue by rebolyte** [reach/reach-ui#201]
Thanks to #181 the MenuButton displays in the correct place in IE 11, but if I hover over a MenuItem past the first child, it disappears:

![L1iHHoaULY](https://user-images.githubusercontent.com/6430933/59302610-f8766f00-8c59-11e9-9d5c-0ce92fc7d163.gif)

This appears to be because within the `onBlur` handler, `event.relatedTarget` is `null`:

![screenshot-1](https://user-images.githubusercontent.com/6430933/59303370-b0f0e280-8c5b-11e9-964c-17d99d208fdb.png)

Version: MenuButton 0.1.18

**Comment by MariuszSzlachta** [comment]
I have the same problem. Are you willing to fix this soon?

Version: 0.1.16

**Comment by JohnnyMcFadden** [comment]
Also having the same issue, would love to see a wee fix for this 🔥

**Comment by liamjohnston** [comment]
Same here, really need this one fixed 🤞 

(otherwise, fantastic library!)

**Comment by chancestrickland** [comment]
Addressed here: https://github.com/reach/reach-ui/pull/110
