### ISSUE TITLE
[Dialog] react-spring animation example slow to return focus?

### ISSUE THREAD

**Issue by kishba** [reach/reach-ui#206]
I was using React Spring's Transition component and the Reach UI Dialog component together like this example from the docs:

https://ui.reach.tech/dialog#animation-example

I noticed what feels to be a delay when the component is leaving. It's also visible in the documentation example... watch (closely) for the focus outline to return to the button. Is the delay expected? The dialog is essentially invisible and then there's still a brief period before the focus is fully returned.

In our internal project we decided to use a more simple Spring animation when the dialog appears so that dismissing the modal returns focus more quickly. Am I overlooking a way to speed up the leave aspect of a Transition?

Thank you for a great set of components & examples!

**Comment by bradwestfall** [comment]
What @alexandernanberg is saying sounds about right. @kishba let us know if there's an actionable item here.
