### ISSUE TITLE
Disabling browser autocomplete with autocomplete="off"

### ISSUE THREAD

**Issue by CodebyOmar** [reach/reach-ui#210]
**Feature request**
**Current behavior:** 
```
<ComboboxInput autocomplete={false}/>
```
this in only determines if the value in the input changes or not as the user navigates with the keyboard. **this prop can be renamed**

**Request:**
```
<Combobox autocomplete="off "/>
```
the native autocomplete for an input element, to be able to disable the annoying browser autocomplete/suggesstion.

**Comment by xtalx** [comment]
@CodebyOmar you can add that dom attribute with
`<ComboboxInput autoComplete="off" />`
The component prop is 'autocomplete'
The input dom attribute is 'auto**C**omplete'

**Comment by CodebyOmar** [comment]
Wow! I totally missed that. Thank you. @ryanflorence i'm closing this issue

**Comment by pdc** [comment]
Shouldn't autoComplete be `off` by default since the whole point of this component is it supplies a suggestions UI replacing the default one if any?
