### ISSUE TITLE
Reset Dialog state after hide/dismiss

### ISSUE THREAD

**Issue by joshuaiz** [reach/reach-ui#212]
I'm using Dialog to show Firebase auth errors instead of the browser `alert()`.

I have a Dialog with `initialState={{ showDialog: true }}` set and then showing it conditionally based on an error in a parent component, with Modal being my component that includes the Dialog.

```javascript
{error && <Modal content={modalContent} />}
```
This works great however once I hide or dismiss the Dialog, if another error is triggered the Dialog does not show again. I have to reload the page for the Dialog to be reset and to be triggered another time.

How can I reset the Dialog state so that when the next error is triggered, the Dialog will show again without reloading?

**Comment by tarang9211** [comment]
@joshuaiz could you please provide a re-producing example on codesandbox or something similar?

**Comment by joshuaiz** [comment]
Hey @tarang9211. I ended up using a different solution so I'm going to go ahead and close this.

Thanks!
