### ISSUE TITLE
[Menu-button] menu disappears during mouse over menu item

### ISSUE THREAD

**Issue by MariuszSzlachta** [reach/reach-ui#218]
Hi, I'm still having the issue under IE11 with closing react-portal of menu-button.
I have already tried a solution from https://github.com/reach/reach-ui/issues/201, but the problem still occurs. There are no errors in the console. Under different web browsers, everything is ok.
Are you willing to release bugfix soon?

**Comment by JohnnyMcFadden** [comment]
Also would love to see a fix for this ^

**Comment by alistairjcbrown** [comment]
@MariuszSzlachta We've bumped into the same IE11 issue, but #201 appears to solve the issue.

![reach-ui-menu-button](https://user-images.githubusercontent.com/635903/60726786-4e29f880-9f34-11e9-93fc-2a4f70e30cfd.gif)

Do you have any more details on what was breaking for you, maybe it's a different issue?

**Comment by chancestrickland** [comment]
Addressed here: https://github.com/reach/reach-ui/pull/110
