### ISSUE TITLE
[Feature request] Default placement for Tooltip

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#223]
Is it possible to provide a default position for Tooltip? It would still respect the collisions, but could place itself to the top by default, instead of bottom, whenever possible.

**Comment by venikx** [comment]
Hi @raunofreiberg 

There's supposed to be a `position` prop exposed, which a function where you can calculate the preferred positioning. When collision occur reach/ui should still take it over and ignore the settings you've defined. 

I'm unfamiliar with the prop and haven't used it, so maybe that's what you are referring to already and are reporting buggy behavior.

**Comment by bradwestfall** [comment]
@raunofreiberg Let us know if that didn't work
