### ISSUE TITLE
[Combobox] Controlled value will open suggestion popover

### ISSUE THREAD

**Issue by tjallingt** [reach/reach-ui#224]
Not sure if this is mentioned anywhere but when controlling the `value` of the `ComboboxInput` the `ComboboxPopover` will start out opened.

```jsx
function App() {
  let [value, setValue] = useState("initial value");

  return (
    <Combobox>
      <ComboboxInput
        value={value}
        onChange={event => setValue(event.target.value)}
      />
      <ComboboxPopover>
        <ComboboxList>
          {results.map(result => (
            <ComboboxOption key={result} value={result} />
          ))}
        </ComboboxList>
      </ComboboxPopover>
    </Combobox>
  );
}
```

example: https://codesandbox.io/s/reachcombobox-behaviour-test-uc5qj

This seems to happen because of the transition to change triggered by these lines:
https://github.com/reach/reach-ui/blob/master/packages/combobox/src/index.js#L362-L367

Additionally controlling the onChange is not called when selecting a value using keyboard or mouse so it is necessary to also add an onSelect to the `Combobox`.

**Comment by tjallingt** [comment]
Something like this might work (but would require some hacky changes to the "reducer machine")

```js
// If they are controlling the value we still need to do our transitions, so
// we have this derived state to emulate onChange of the input as we receive
// new `value`s ...[*]
if (isControlled && controlledValue !== value) {
  if (value === "") {
    // this is most likely the initial value so we want to
    // update value without transitioning to SUGGESTING
  } else {
    handleValueChange(controlledValue);
  }
}

```

**Comment by marciobarrios** [comment]
I have the same problem, I fixed it having a a boolean to control when to show the popover and a `useEffect` to capture when the are suggestions:
```js
useEffect(() => {
    if (suggestions.length) {
      console.log(suggestions.length)
      setReadyToShowAutocomplete(true)
    }
  }, [suggestions])
```

**Comment by tonypee** [comment]
Im also encountering this now... It seems that the component isnt designed to be controlled?
