### ISSUE TITLE
reach portal is bad positioned when the container has a height. (MenuButton)

### ISSUE THREAD

**Issue by felipediogo** [reach/reach-ui#225]
The reach-portal is bad positioned, when the menubutton is inside a container with a height bigger than the component.

Here's a codesandbox sampling my issue.
[codesandbox](https://codesandbox.io/s/lucid-ganguly-1tsow?fontsize=14)

is there a way to get around this problem? like a position absolute from the menuitems and attach it to the menubutton.

Thanks in advance for creating this amazing library.

**Comment by cevr** [comment]
You must import the appropriate css styles if you want the components to have some sort of default styling attached.

In this case:

```js
import '@reach/menu-button/styles.css'
```

**Comment by felipediogo** [comment]
That's awesome @cevr , sorry about that =/
