### ISSUE TITLE
[Tabs] @reach/tabs cause FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ldramowicz** [reach/reach-ui#228]
I installed @reach/tabs tabs as directed, run a build/run script and got:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

As soon as I uninstall @reach/tabs everything compiles fine. Possible memory leak?

**Comment by venikx** [comment]
What version of node are you using?
Are you using docker?

**Comment by donaldpipowitch** [comment]
Hard for me to create a reproducible test case for this issue right now, but I had the same problem whenever I tried to render `DialogOverlay` from `@reach/dialog` (`@reach/dialog@0.8.6`, `jest@25.1.0`). I used this workaround - maybe it helps someone:

```ts
jest.mock('@reach/dialog', () => ({
  ...jest.requireActual('@reach/dialog'),
  DialogOverlay: ({ children }: any) => children
}));
```

**Comment by donaldpipowitch** [comment]
Apparently it takes three months for me to forgot that I had this issue already before 😭  Just debugged this problem down to `DialogOverlay` again - but now I was curious and invested a little bit more time. `DialogOverlay` uses `DialogInner` which uses `{ RemoveScroll } from "react-remove-scroll"`.

So the better fix would be to add a `__mocks__/react-remove-scroll.js` file with the following content:

```ts
module.exports = {
  RemoveScroll: (props) => props.children,
};
```
