### ISSUE TITLE
menu-button styling issues with emotion

### ISSUE THREAD

**Issue by bogdansoare** [reach/reach-ui#23]
I'm trying to style the menu-button component using emotion.
```js
// Menu.js
import styled from 'react-emotion';
import {
  Menu as ReachMenu,
  MenuButton as ReachMenuButton,
  MenuList as ReachMenuList,
  MenuItem as ReachMenuItem
} from '@reach/menu-button';
import '@reach/menu-button/styles.css';

const Menu = ReachMenu;

const MenuButton = styled(ReachMenuButton)`
  background-color: #fff;
  border: 1px solid #ccc;
  padding: 6px 10px;
`;

const MenuList = styled(ReachMenuList)`
  background-color: red;
`;

const MenuItem = styled(ReachMenuItem)`
  padding: 20px;
`;

export { Menu, MenuButton, MenuList, MenuItem };

```

But I get this error when clicking the button `Cannot read property 'selectionIndex' of undefined`

You can check it out here https://codesandbox.io/s/7zmq7803k6

**Comment by ryanflorence** [comment]
Ah shoot, I should have thought of this 😑

`if (child.type === MenuItem || child.type === MenuLink) {`

Gonna allow anything I guess.

**Comment by ryanflorence** [comment]
Don't forget you'll want to style the selected state probably too :)

```js
const MenuItem = styled(ReachMenuItem)`
  padding: 20px;
  &[data-selected] {
    color: red;
    background: white;
  }
`;
```

**Comment by ryanflorence** [comment]
https://codesandbox.io/s/8z3yln1x0l

**Comment by bogdansoare** [comment]
awesome, thanks 🙌

**Comment by amberleyromo** [comment]
I'm still getting this error trying to do the same thing :( 

`TypeError: Cannot read property 'selectionIndex' of undefined`

Tried just copy-pasting from the sandbox. Was this later reverted?

```
import React, { useState } from "react"
import styled from "react-emotion"
import "@reach/menu-button/styles.css"
import {
  Menu as ReachMenu,
  MenuButton as ReachMenuButton,
  MenuList as ReachMenuList,
  MenuItem as ReachMenuItem,
} from "@reach/menu-button"

const Menu = styled(ReachMenu)``

const MenuButton = styled(ReachMenuButton)`
  background-color: #fff;
  border: 1px solid #ccc;
  padding: 6px 10px;
`

const MenuList = styled(ReachMenuList)`
  background-color: red;
`

const MenuItem = styled(ReachMenuItem)`
  padding: 20px;
  &[data-selected] {
    color: red;
    background: white;
  }
`
const Test = () => {
  return (
    <Menu>
      <MenuButton>Actions</MenuButton>
      <MenuList>
        <MenuItem>Download</MenuItem>
        <MenuItem>Foo</MenuItem>
      </MenuList>
    </Menu>
  )
}

export default Test
```

**Comment by qoalu** [comment]
Same issue. Using styled-components.

Interestingly documentation page provides an example of styling MenuItems by attribute from MenuList component

https://ui.reach.tech/styling/

```
let YourMenuList = styled(MenuList)`
  border: solid 2px black;
  background: black;
  color: red;
  > [data-reach-menu-item][data-selected] {
    background: red;
    color: white;
  }
`
```

**Comment by jamesarosen** [comment]
I get this on the latest version. My higher-order component:
```jsx
export default function withClassName(Component, extraClass, displayName) {
  const Wrapped = React.forwardRef(({ className, ...props }, ref) => {
    return <Component {...props} className={classnames(className, extraClass)} ref={ref} />
  })

  Wrapped.propTypes = {
    className: PropTypes.string,
  }

  Wrapped.defaultProps = {
    className: '',
  }

  Wrapped.displayName = displayName

  return Wrapped
}
```

This works:
```jsx
import { Menu as ReachMenu } from '@reach/menu-button'
export const Menu = withClassName(ReachMenu, 'my-menu', 'MyMenu')
```

This doesn't:
```jsx
import { MenuItem as ReachMenuItem } from '@reach/menu-button'
export const MenuItem = withClassName(ReachMenuItem, 'my-menu-item', 'MyMenuItem')
```

Specifically, `state` is undefined [here](https://github.com/reach/reach-ui/blob/9b0e970f1419a07927e4a2b7f8bc4a6ae3eeaff1/packages/menu-button/src/index.js#L182).

**Comment by focux** [comment]
Same here, MenuItem isn't working on styled-components yet.

**Comment by chukkwagon** [comment]
I am having this problem as well. Can we re-open this issue since it appears to have regressed?:
My installed version of `@reach/menu-button` is `0.3.0`. I'm also unable to style `MenuLink` using the suggested workaround. The following has no effect:
```tsx
const MenuList = styled(_MenuList)`
  border: solid 2px black;
  background: black;
  color: red;
  > [data-reach-menu-link] {
    background: red;
    color: white;
  }
```

**Comment by dwilt** [comment]
I'm also seeing this in my [puppeteer](https://github.com/GoogleChrome/puppeteer) tests specifically.

**Comment by chancestrickland** [comment]
FYI, we have a duplicate issue that is still open dealing with this. I'm tracking the conversation there, but we are aware and working on this. We'll have a rewrite of MenuButton out (hopefully) in the next couple of weeks. https://github.com/reach/reach-ui/issues/119

**Comment by amberleyromo** [comment]
Happy to see this update, thanks for all your work @chancestrickland!!
