### ISSUE TITLE
[Combobox] Cannot unfocus after selecting an option

### ISSUE THREAD

**Issue by bsonntag** [reach/reach-ui#230]
After selecting one of the options I can't focus other inputs. The only way to focus other things is to do Shift+Tab first.

This is happening on Chrome 75.0.3770.100 and Safari 12.1.1. It works on Firefox, but I have to wait about 1 second, otherwise focus goes back to the combobox input.

I'll make a repro on codesandbox later.

**Comment by marciobarrios** [comment]
Can you create a codesandbox showing the problem? this way would be easier to help :)

**Comment by venikx** [comment]
Hi @bsonntag A codesandbox would be great indeed. I quickly tried out what you were explaining and I can't seem to reproduce it in Chrome, nor Firefox (not sure about Safari, don't own a mac).

**Comment by bsonntag** [comment]
I can't reproduce this again, and I changed my original code to use `react-select` instead, so I can't check what I did before exactly.
