### ISSUE TITLE
Ability to skip styles altogether

### ISSUE THREAD

**Issue by selbekk** [reach/reach-ui#244]
I love this project, and I'm using tons of its component in the apps I work for. Thanks for all of your work, efforts and dealing with all of these issues.

I typically don't use the default styles provided by the component - but I also hate the yellow console warning I get if I don't import them. 

After digging through the source code (okay, it was literally opening the CSS file, but still), I found that I can add `::root { --reach-dialog: 1 }` to avoid this warning. I still think this should be documented though!

Would you be open to me opening a PR documenting this "manual override"?

**Comment by venikx** [comment]
Go for it I'd say. Worst case scenario Ryan says no. Not that bad, tbh.
