### ISSUE TITLE
menu-button: button id issues

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#25]
The id is auto generated for the menu button, it needs to:

- Accept a props.id before autogenerating one
- Generate ids in a deterministic way so that rehydrating a server render works (I think it ought to be broken right now)

**Comment by bogdansoare** [comment]
I see that hasn't been much activity in the RFC regarding isomorphic IDs https://github.com/reactjs/rfcs/pull/32 .

The only decent solution that I've found is to do something like https://github.com/thearnica/react-uid#server-side-friendly-uid which uses the Context API to track used IDs.

@ryanflorence what do you think ?

**Comment by ryanflorence** [comment]
I was planning something exactly like that. I'm gonna wait for hooks to ship though so it's not so arduous.

**Comment by mfix22** [comment]
Would this work:
```js
let genId = (prefix, count) => `${prefix}-${count}`;

let count = -1;
let getInitialMenuState = () => ({
  // ...
  buttonId: genId("button", count++)
});
```
? 
If so i'll push the PR. Will be easy to migrate to hooks.

**Comment by stereobooster** [comment]
> Accept a props.id before autogenerating one

```js
export const useId = (defaultValue) => {
  const [id] = useState(genId || defaultValue);
  return id;
};
```

> Generate ids in a deterministic way so that rehydrating a server render works (I think it ought to be broken right now)

I guess we need something like this https://github.com/thearnica/react-uid

**Comment by venikx** [comment]
It seems to be that the react-uid library is now using hooks and the hooks are SSR friendly. So I suppose we could change the UUID generator to the react-uid one? 

Source: https://github.com/thearnica/react-uid#hooks-167
