### ISSUE TITLE
[MenuButton] Provide a Button component

### ISSUE THREAD

**Issue by alexluong** [reach/reach-ui#251]
Hi,

I'm building a UI library on top of Reach UI. I wonder if we can provide our own Button component for MenuButton. At the moment, the only way to style it is through classes. Any chance we can have a prop that provide the Button instead?

```jsx
<MenuButton as={Button}>
  Actions <span aria-hidden>▾</span>
</MenuButton>
```

Thank you!!

**Comment by tarang9211** [comment]
@alexluong It seems like the `Button` component is not a priority to be built. @mjackson Are we planning on building this?

**Comment by alexluong** [comment]
I’m not asking for the Button component. I want to supply my own Button to MenuButton for styling purposes.

**Comment by tarang9211** [comment]
I see. I think that is something that is achievable. Will have to wait and see the roadmap.

**Comment by chancestrickland** [comment]
@alexluong Any reason you couldn't do this?

```js
function StyledMenuButton({ children = "Actions", ...props }) {
  return (
    <MenuButton {...props}>
      {children} <span aria-hidden>▾</span>
    </MenuButton>
  );
}
```

or 

```js
const StyledMenuButton = styled(MenuButton)`
  {...}
`
```

I'm kind of opposed to accepting an `as` prop for MenuButton because we definitely don't want folks using something that renders a non-button HTML tag.

**Comment by Silverwolf90** [comment]
I think an `as` prop should be reconsidered. Not being able to substitute with the canonical button component(s) in a design system is problematic. Styles either have to be duplicated or shared, which I think is unnecessary ceremony and more error prone.

Sure it's possible to shoot themselves in the foot and make something inaccessible, but I think the convenience far outweigh this risk.
