### ISSUE TITLE
Dialog not scrollable at certain window heights

### ISSUE THREAD

**Issue by nicolasschabram** [reach/reach-ui#253]
Hey there,

I've noticed that a `Dialog` sometimes doesn't allow for scrolling even though it is higher than the window and a scrollbar is displayed. It happens for me whenever the dialog content is *just a bit* higher than the viewport. When increasing the height of the content (or decreasing the window size), it works fine.

Here it works:
![works](https://user-images.githubusercontent.com/1027642/63020430-662f5900-be9e-11e9-9219-958e998e2dcd.png)

Here it doesn't:
![broken](https://user-images.githubusercontent.com/1027642/63020448-6e879400-be9e-11e9-8ca0-29464e85ea91.png)

I only experience the issue when using the mouse wheel; no problems with a touchpad or when dragging the scrollbar.

It happens in all major browsers except Firefox (at least on Windows).

Any idea what's behind this?

Thanks!
Nicolas

**Comment by chancestrickland** [comment]
I am unable to reproduce this, but I'm also using a magic mouse which may be perceived as a trackpad somehow. I don't have a traditional mouse with a wheel, so...we might need to change that! 

Looked through a seemingly related issue with react-remove-scroll https://github.com/theKashey/react-remove-scroll/issues/14 so I'm going to investigate a bit more here in the mean time.

**Comment by zackkrida** [comment]
I had an issue in my app like this that related to using react with react-remove-scroll.

I intend on investigating that incompatibility and posting an issue in the appropriate place, but figured i'd note it here.

**Comment by chancestrickland** [comment]
Important to note that Preact does not use React's synthetic events. Without seeing your app, I suspect that could be related to your issue @zackkrida .

**Comment by zackkrida** [comment]
@chancestrickland exactly what i was thinking. if i find some downtime today i was going to see if the best fix is a pr to preact/compat or react-remove-scroll itself
