### ISSUE TITLE
[Dialog] Issue with newer version of react-focus-lock's onActivation

### ISSUE THREAD

**Issue by gnapse** [reach/reach-ui#267]
I'm using `@reach/dialog` in a project, and we recently started using `react-focus-lock` directly ourselves to lock focus in situations other than dialogs. When we installed it as a direct dependency, it seems we got the latest v2.x, which has been rewritten to use React hooks.

A side effect seems to have been that now [this `onActivation` callback prop](https://github.com/reach/reach-ui/blob/32cbe30859d3a32093fd01c243365fd01d64c520/packages/dialog/src/index.js#L79) is being called every time the dialog re-renders for any reason. An example as simple as managing some state in the component that renders the dialog, when this state is used inside the dialog, will cause `onActivation` to happen. In our case this was having the effect that auto focus was being reset every time we typed inside input fields inside a form that was inside the dialog.

I know this lib is not yet depending on v2.x of `react-auto-focus`, but wanted to make the case anyway to fix it (maybe wrapping the `onActivation` callback above inside `React.useCallback`?)

It wouldn't hurt also to migrate to use v2.x of react-focus-lock in general. It's much smaller in size.

**Comment by chancestrickland** [comment]
@gnapse We've updated `react-focus-lock` in our latest alpha release. Check it out and let us know if you have any issues.
