### ISSUE TITLE
Use hooks in examples instead of component^2

### ISSUE THREAD

**Issue by selbekk** [reach/reach-ui#269]
component^2 was really cool once it came out, but it's not the easiest way of showing how the other components work. at least not anymore.

Would you be open to a pull request refactoring the examples in the documentation to use regular hooks instead?

**Comment by mjackson** [comment]
Yes, absolutely. Now that hooks are here, I'd like to deprecate component-component. Thank you!

Also, if you wouldn't mind adding a few basic tests as you go just to make sure that things still work as expected I'd be very grateful. I just upgraded the repo to Jest 25 last night and noticed that we barely have any test coverage at all. A refactoring like this could break stuff 😬

**Comment by selbekk** [comment]
Sure, I’ll see what I can get around to this weekend 🙌

**Comment by selbekk** [comment]
I skipped the tests 

![shame](https://media.giphy.com/media/vX9WcCiWwUF7G/giphy.gif)

, but did you mean in the project in general, or for the docs examples? I'm not sure how I'd write tests for the mdx examples outside of pulling in something like cypress, and i'm not really about to to that right now 😄 

The docs should be good with the PR above.
