### ISSUE TITLE
menu-button: add a css selector to the Menu to know when it's open 

### ISSUE THREAD

**Issue by bogdansoare** [reach/reach-ui#28]
My use case is that I want to style an arrow icon inside the `MenuButton` based on whether the menu is open or not.

Is this a feature that could be accepted? Can I make a pull request?

**Comment by bogdansoare** [comment]
or maybe I should use the `aria-expanded` attribute?

**Comment by chadwithuhc** [comment]
`[aria-expanded="true"]` will accomplish same thing fo sho

**Comment by ryanflorence** [comment]
^ that works, will also be adding a render prop API here because we can't animate the exit transition yet.

It'll probably look like this:

```jsx
<Menu>
  {({ isOpen }) => (
    <MenuButton/>
    {isOpen && <MenuList/>}
  )}
</Menu>
```

Not only will it allow animations, but you'd be able to add whatever classNames you wanted when it's open.
