### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by alexluong** [reach/reach-ui#288]
## ❓Question

Hey, I'm excited for the new development initiative for Reach UI. Is there anything I can do to help?

I've looked around at `good first issue` and `help wanted` issues, but those seem to be outdated.

**Comment by chancestrickland** [comment]
Hey @alexluong, super glad you're looking to help! I'm updating old issues and labels as quickly as possible, so please keep an eye on these labels and jump in wherever you feel comfortable. Feel free to comment on any open issues with questions and tag me directly if you need any help figuring things out.
