### ISSUE TITLE
DialogOverlay and DialogContent html tree

### ISSUE THREAD

**Issue by enzoferey** [reach/reach-ui#289]
Hi !

I was wondering if making something like this doesn't break accessibility concerns:

<img width="450" alt="Screenshot 2019-10-07 at 18 22 58" src="https://user-images.githubusercontent.com/10673347/66329863-90961380-e92f-11e9-96eb-8f8c702b65e0.png">

In the [docs](https://ui.reach.tech/dialog#dialogcontent) it states that it needs to be a child of `DialogOverlay`, but not a direct child.

Other solution for me would be to create a wrapper element like this:

<img width="450" alt="Screenshot 2019-10-07 at 18 23 12" src="https://user-images.githubusercontent.com/10673347/66329859-8d9b2300-e92f-11e9-8975-731818fb89db.png">

But then I would need to place the overlay styles on my element and use the `DialogOverlay` as my `SomeDiv`, which may be semantically not correct.

For the sake of completeness, my `SomeDiv` is a styled component that looks like this:

<img width="222" alt="Screenshot 2019-10-07 at 18 25 08" src="https://user-images.githubusercontent.com/10673347/66330026-de128080-e92f-11e9-8059-fdced0ab576f.png">

(where `ScrollableStyles` is some css to style the scrollbar)

Thank you very much !

**Comment by chancestrickland** [comment]
@enzoferey Nothing I see here really raises any flags to me. Just be mindful that clicking or touching in the overlay region outside of the DialogContent is intended to fire the `onDismiss` handler, so just be sure to make sure your final implementation doesn't impact expected behavior there.
