### ISSUE TITLE
use const instead of let when variable is not reassigned

### ISSUE THREAD

**Issue by jescowuester** [reach/reach-ui#296]
A lot of declarations are using `let` but are never reassigned. This is confusing to new contributors and makes it harder to see if a variable actually will be reassigned.

**Comment by chancestrickland** [comment]
See our notes in the PR. Even if it may be a bit confusing, it's important that beginners understand the nuances of `let` and `const`. A negative side effect of this rule IMO is giving new developers the impression that `const` variables are immutable when, in fact, they just can't be reassigned. It's an important distinction that can keep us from introducing bugs through a false sense of safety!
