### ISSUE TITLE
Maybe the slider can support `options + arrow` can change double steps

### ISSUE THREAD

**Issue by thoamsy** [reach/reach-ui#323]
### Current Behavior

Now the [Slider](https://reacttraining.com/reach-ui/slider) just can be adjust the value with fixed step. 
For example, the `min=1, max=100, step=1`, and I want to just use my keyboard to adjust the value to 50, I need to press about 49 times, it's painful!

### Suggested Solution

What if I can use `option ⌥ ` or `alt` in window to adjust the value with multiple times(5) of the step?
Now I just need to press 9 times of `⌥ + arrow right` and 4 times of arrow right.

Thank you guys. 😊

**Comment by chancestrickland** [comment]
I'm not sure if that's the expected behavior. Native input range elements don't behave this way, nor is it isn't outlined in the ARIA spec. You can use `PageUp`/`PageDown` to move the slider in 10-step intervals. You can also set your own `onKeyDown` prop to add your own logic if you'd like. This is untested, but something like this *should* work (you can build onto our event handlers without breaking them):

```js
function handleKeyDown(event) {
  let newValue;
  let flag = false;
  let fiveSteps = (max - min) / 5;
  switch (event.key) {
    case "ArrowLeft":
    case "ArrowDown":
      if (event.altKey) {
        newValue = actualValue - fiveSteps;
        flag = true;
      }
      break;
    case "ArrowRight":
    case "ArrowUp":
      if (event.altKey) {
        newValue = actualValue + fiveSteps;
        flag = true;
      }
      break;
  }
  if (flag) {
    // prevent our event handler from firing by calling preventDefault
    event.preventDefault();
    yourControlledSetState(newValue);
  }
}
```

**Comment by thoamsy** [comment]
I think your code snippet is helpful for me. 
I am not very familiar with the ARIA standard, but emm… 
I have seen similar applications in many places, like you can press `option ⌥ ` and scroll in VSCode,  
the speed of scrolling has increased.
Also, I like use `option ⌥` + `arrow right` to move my cursor between words. So if the feature can be built in, it's very cool!

**Comment by chancestrickland** [comment]
Closing as this is not in the aria spec, nor would it necessarily be the expected behavior for every type of slider. Implementing this in your own components should be as simple as passing event handlers as noted above.
