### ISSUE TITLE
Why are there almost no tests?

### ISSUE THREAD

**Issue by beckerei** [reach/reach-ui#327]
## ❓Question

I was curious to contribute to `reach-ui` as we recently started to use components from it in our apps.
Checking out the code I noticed that there are almost no tests. So I don't feel very confident in contribute as I never know if I break something else.
Even more I no longer feel confident in using reach-ui components as a base in our app.

Is there a motivation behind "no tests"?

**Comment by chancestrickland** [comment]
No motivation, no good reason, we just haven't. I'm planning to write them for new components as we introduce them, but if you'd like to contribute some for existing components that would be very helpful, and I'm happy to offer any guidance if you want to submit a PR.

Tests are on the todo list but @ryanflorence @mjackson and I need to coordinate on priority for that before I make any promises!

**Comment by beckerei** [comment]
I'm happy to help 👍  

> I need to coordinate on priority for that before I make any promises!

**Comment by chancestrickland** [comment]
@beckerei I'm good with testing-library. I don't think we'll need too much here though. Based on a quick convo with Ryan, you might find this helpful as a guide for test sequences.

- Render -> snapshot -> fire event -> snapshot
- check `document.activeElement` -> fire event -> snapshot
- check `document.activeElement`

**Comment by beckerei** [comment]
Seems fine, even though I personally tend to use less snapshots as they take longer (might not matter in this case) than other assertions, and specific assertions help to understand what went wrong, while snapshots cover a lot of stuff which can change, but doesn't matter.

But I start with the proposed snapshot approach, I will check if the react test renderer is sufficient in that case and only switch to testing lib if it does not seem helpful.

**Comment by chancestrickland** [comment]
I think for small reusable components snapshots can work well and shouldn't be too slow. Thanks for the assist!

**Comment by beckerei** [comment]
I tried to cover all use cases of the tooltip and created a Draft PR.
There is still an issue with the `useId` which should be mocked or reset in some way before each test.
