### ISSUE TITLE
Slider typings not consistent with documentation

### ISSUE THREAD

**Issue by ed-sparkes** [reach/reach-ui#332]
### Current Behavior

Documentation suggests can use Slider in its simplest form as 

`<Slider />`

However in my typescript project it doesn't allow this as the following are required ...

- children 
- handleAlignment

can handleAlignment be defaulted and children made optional if not required?

### Expected behavior

Should be able to recreate the examples in the documentation in a typescript project without error

### Reproducible example

https://codesandbox.io/s/elegant-bash-if98w

**Comment by chancestrickland** [comment]
@ed-sparkes Should be good to go with 0.5.1. Note the API changed slightly when we moved Slider out of beta for 0.4.0. Here's an updated sandbox for you. https://codesandbox.io/s/funny-cartwright-67ovc
