### ISSUE TITLE
Drag slider to right then back to left doesnt allow dragging to the inital position, it stops one short, keyboard can get back to start but not with mouse 

### ISSUE THREAD

**Issue by ed-sparkes** [reach/reach-ui#333]
### Current Behavior

In the example attached if you drag the slide handle to the right then try and drag back to the beginning it stops one step short, using the keyboard you can get it back to the initial position but not with the mouse. 

### Expected behavior

Should be able to slide backwards and forwards through the full range

### Reproducible example

https://codesandbox.io/s/peaceful-lederberg-14yxr

**Comment by chancestrickland** [comment]
Thanks for catching! This is fixed in 0.5.2 https://codesandbox.io/s/cool-robinson-hgkgf
