### ISSUE TITLE
Typescript error with @reach/alert 0.4.0

### ISSUE THREAD

**Issue by WestonThayer** [reach/reach-ui#338]
### Current Behavior

`npm install @reach/alert` (latest is 0.4.0).

```jsx
import Alert from "@reach/alert";

<Alert>stuff</Alert>
```

Typescript emits error 2740.

### Expected behavior

No TS error.

### Suggested solution(s)

https://github.com/reach/reach-ui/blob/master/packages/alert/index.d.ts#L6 should not be unioned with `HTMLDivElement`. Instead `React.ComponentProps<"div">` would work fine.

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| **[REACH_PACKAGE_NAME]** | @reach/alert@0.4.0
| React                    | 16.8.6
| Browser                  | N/A
| Assistive tech           | N/A
| Node                     | v10.13.0
| npm/yarn                 | npm 6.4.1
| Operating System         | macOS Mojave

**Comment by chancestrickland** [comment]
This should be fixed in 0.5.0. @WestonThayer let me know if you still have issues and I can re-open.
