### ISSUE TITLE
Typescript error: A 'declare' modifier cannot be used in an already ambient context.

### ISSUE THREAD

**Issue by rjoaopereira** [reach/reach-ui#341]
## 🐛 Bug report
**EDIT:**
Just saw that the following PR solves the problem: https://github.com/reach/reach-ui/pull/334

Compiling a Typescript application that includes a reach component that contains a type declaration file which contains a `declare` inside a `declare` will result in error.

### Current Behavior

```bash
    error ...node_modules/@reach/tooltip/index.d.ts:41:3
          A 'declare' modifier cannot be used in an already ambient context.
```
### Expected behavior

Compilation without errors

### Reproducible example

[Typescript playground](http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#code/CYUwxgNghgTiAEBbA9sArhBAiAAnKYAFgPQAuyyEpAlgA5bwDeAUPPNYrcjKfAFTwoAZ3gAlEAV4AzGMkTws+MKSwBuZq3ggAHlx7sAdqRAwpBBABUY1AOY2TABVhREIlmzZZY1KAFpQQmDWAEYgwMEAnlgAXPBCpNYGNuoeCsBQpH5KhL7klDS0udZ2JjFxCdRJKR5wUrHikgB04lIAPFAGEQB81WzIBgCyyGhCIACiRib1EsrNM6RjAG4gRgASHcCYML3w-UMjIEPL000NyksrpOsGmyY7-QBiyGAjJ7NnC8trG1v3BgBCEDQMDepDmkgu3xuv00fUGw1GABkJMcxPNwecvlcfndYbsDABpEARAAiyAA7gZQRjPpdrrdtni9giQGTKdSPpDsdDcWwAL4aNg6PS8SrGUzmeAWChUOhOGAuNx46jAWLxRLJPEVEowcTKWIkgDyAz1pB21CEADULdRgphYsEZRIDNUBZphdxpGgDMpqP14Adpfk6AAKPEZBJCAD81NWFgGiIcsloQnanS6mgAlLEANpWWz2GDyxUAGilMoKxdcZcdlGdAF11O7dJ74KQIrQEP9hCAg7LaEnkCn4ABeJjh6xQRFQUIQGPlDU7LhCag0frzkPL1d+gwARgNxtNZa3a4MACYDybwKRM6OuvAjVflDtoLOOfMAHKoECu+AAMngQ1EFXVoPkaOME0HFNWggxESWoRYxkwRBLi6MssFfEAICwHpBS0Ft9HbTty2DAdkxEMd3A8IhqAgYA4CpNFTk-b9fwA7tRj7StyKbIUCN4IjLArOUhzQMihwo8dUhouiGPnMCPi-UA2PgDje2E8SU14+BQEgWAEDAfp4hI-tqQeb1fX6ABhOQuAMS5Wi4uVyNwviRXgQyDGMpyB1E2gzIs08bM4foHJ8hw-KgoRXPw9zPO8jSbMmIwAp9ILbNCoxWjU8KXOqD19FAMwMF4Hz1D5IA)

### Suggested solution(s)

removing the inner declare solves the issue

### Your environment

| Software                           | Name/Version(s) |
| ------------------------ | --------------- |
| **@reach/tooltip**          | 0.4.0
| React                                | ^16.*
| Typescript                        | 3.6.3
| Browser                            | n/a
| Assistive tech                  |
| Node                                | 10
| npm/yarn                         | yarn
| Operating System           | MacOS X

**Comment by chancestrickland** [comment]
Fixed in https://github.com/reach/reach-ui/pull/334 and a subsequent fix on master for other affected packages.
