### ISSUE TITLE
Slider with Children duplicates track in DOM

### ISSUE THREAD

**Issue by ed-sparkes** [reach/reach-ui#348]
### Current Behavior

if you specify children for you slider e.g. 

```
<Slider
        min={1}
        max={4}
        step={0.25}
        handleAlignment="center"
        value={zoom}
        onChange={nv => setZoom(nv)}
      >
        <SliderTrack>
          <SliderTrackHighlight />
          <SliderHandle />
        </SliderTrack>
      </Slider>
```

It appears as if the top level Slider adds a `<SliderTrack>` dom element and the child adds another, this leads to duplicate tracks in the DOM

Screenshot here https://ibb.co/PzSBR9m

### Expected behavior

Single track per slider, if you specify a track as a child then the default one should omitted so that you can control the apparance and props of the track using the child. 

### Reproducible example

https://codesandbox.io/s/cool-robinson-hgkgf

**Comment by chancestrickland** [comment]
@ed-sparkes `Slider` is the standalone component and should not accept children. This API changed when we took Slider out of beta. For the low-level API you're looking for, you'll want to use `SliderInput` instead.
