### ISSUE TITLE
Remove font-family style from MenuButton css

### ISSUE THREAD

**Issue by JasonEtco** [reach/reach-ui#349]
### Current Behavior

Hi folks! Sorry if this is miscategorized as its not a _bug_, but was a confusing discovery. The styles that come with `@reach/menu-button` includes a `font-family: sans-serif` definition:

https://github.com/reach/reach-ui/blob/6dbd4f9e35e5f5efdb57f70bb6f6c6a6ba310bd3/packages/menu-button/styles.css#L7

This was surprising to me - AFAIK, there's no a11y reason for it, aside from the usual contrast/size/readability concerns. My project (and most I assume) sets a global `font-family`, and while they're both `sans-serif`, this line overrides it to force it into the default sans-serif.

### Expected behavior

I'd expect the styles here to focus on the functional stuff, without being too heavy handed on the aesthetic.

### Reproducible example

N/A

### Suggested solution(s)

I'd remove the line 🔪 but open to discussion! In the meantime, I've copied over the provided styles into stylesheets I control, and removed that line myself (I had to make other changes so it wasn't a huge issue).

### Additional context

N/A

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| `@reach/menu-button` | 0.5.0
| React                    | 16.11.0
| Browser                  | Firefox 71.0b2
| Assistive tech           | N/A
| Node                     | N/A
| npm/yarn                 | N/A
| Operating System         | MacOS Mojave

**Comment by chancestrickland** [comment]
Removed in 0.5.4
