### ISSUE TITLE
Move @reach/observe-rect in reach-ui repo

### ISSUE THREAD

**Issue by stefanprobst** [reach/reach-ui#356]
It looks like [`@reach/observe-rect`](https://github.com/reach/observe-rect) is a dependency of `@reach/rect` but lives in a separate repo. Does it make sense to move it here?

**Comment by chancestrickland** [comment]
If I had to guess, I'd say that it's probably in a separate repository because Reach UI is a React-specific library, whereas observe-rect is just a JS utility. We could consider merging it into this project in the future but for now I think it's fine on its own.

**Comment by stefanprobst** [comment]
ok makes sense, just thought it would make maintainance easier - like review for [this PR from Jun 2018](https://github.com/reach/observe-rect/pull/2)
