### ISSUE TITLE
@reach/skip-nav type definition not allowing self-closing tags

### ISSUE THREAD

**Issue by MarkH817** [reach/reach-ui#358]
### Current Behavior

After running `tsc` to typecheck, it errors out because `<SkipNavLink />` and `<SkipNavContent />` don't have children.

### Expected behavior

This TypeScript error should not be showing, given that the documentation says this is allowed to be used with no children.

### Suggested solution(s)

Changing the `children: React.ReactNode;` to `children?: React.ReactNode;` to mark `children` as optional for the 2 mentioned components above.

### Additional context

This might also apply to other Reach components that optionally have children components.

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| @reach/skip-nav | 0.5.3
| React                    | 16.11.0
| Browser                  | N/A
| Assistive tech           | N/A
| Node                     | 12.13.0
| npm/yarn                 | 6.12.0
| Operating System         | Windows 10

**Comment by chancestrickland** [comment]
This should be fixed as of 0.6.1.
