### ISSUE TITLE
[Combobox] Allow to always display the options if exists even if the input is empty

### ISSUE THREAD

**Issue by tesnouf-drivy** [reach/reach-ui#367]
### Current Behavior

When we type some term in the input then we clean it (using backspace), the ComboboxPopover is forced to be hidden even if some options could be displayed.
This behavior makes sense as a "default behavior" with a static option list.
But when the list is computed programmatically based on the input, the developer is responsible for filtering the list and so the Component should not take the decision to hide the popover on an empty input.
In my case (a Google address picker), I need to suggest to the user some options when the input is empty: the current location (geolocation), the previous queries (history) ...

The list is correctly displayed on focus with the `openOnFocus` property (even if the input is empty)
The issue occurs with the backspace.

### Desired Behavior

If the developer ask for, always display the Combobox options (no hidden attribute on the popover) even if the input is empty

### Suggested Solution

As there is no way for the Combobox to know if the list is filtered/controlled by the developer, perhaps we should have a `hideOnEmpty` property that we could set to false to prevent the component to set the `hidden` attribute on an empty input (backspace)

### Who does this impact? Who is this for?

Anyone who would like to display some suggestions on an empty input (could be a tip "enter a user name, 3 characters minimum", or some specific options)

**Comment by mlimberg** [comment]
Wanted to follow up on this as I am interested in this feature as well. We'd like to populate any recent searches in the popover when the input is focused but has an empty state. I see there is an `openOnFocus` prop you can set, which works great on the initial focus. However, when a user types, and then deletes all typed characters the popover does not stay rendered even though there are recent searches to default back to.

Is this feature available and if so, what is needed to achieve? 

Thank you!

**Comment by markus-heer** [comment]
Same here. I want to give the user the opportunity to remove the typed characters and see all available options again (as when `openOnFocus` set to true and clicked inside the input)

**Comment by mavalon** [comment]
This is a terrible workaround solution, but it does seem to work:

Force focus onto another element and then focus back onto the ComboboxInput  field to reopen results:

```
  const cbRef = useRef() // ComboboxInput ref
  const hiRef = useRef() // Hidden text input ref

  // ComboboxInput onChange event
  const onTextChanged = (e) => {
    // search function
    matches(e)

    // toggle focus if empty string to trigger ComboboxPopover
    if (!e.currentTarget.value.trim().length) {
      hiRef.current.focus() // focus on text box (with zero opacity, height and width)
      setTimeout(() => {
        cbRef.current.focus() // return focus to combobox
      }, 50)
    }
  }
```
