### ISSUE TITLE
[MenuButton] Allow ability to set alignment of MenuList

### ISSUE THREAD

**Issue by NerdCowboy** [reach/reach-ui#370]
### Current Behavior

Defaults alignment of `MenuList` to the left and only changes with collision detection.

### Desired Behavior

Add the ability to set the initial default alignment of the `MenuList`, similar to how Bootstrap does it: https://getbootstrap.com/docs/4.3/components/dropdowns/#menu-alignment, so that right aligned menu list stays aligned with the design.

### Suggested Solution

Add a prop like `defaultAlignment`, which would be used as the starting point for alignment, but still be able to use collision detection.

### Who does this impact? Who is this for?

People that want a design that stays in alignment.

### Describe alternatives you've considered

I can fix it with magic numbers using CSS, but that's less than ideal, especially with responsive design necessitating multiple magic numbers.

**Comment by chancestrickland** [comment]
As of 0.7.0, you can now add a `position` prop into `MenuPopover` to assist with this.

```jsx
// you can check out the positioning functions here if you want to inject your own logic
import { positionMatchWidth } from "@reach/popover";

function MyMenu() {
  return (
    <Menu>
      <MenuButton id="example-button">
        Actions <span aria-hidden="true">▾</span>
      </MenuButton>
      <MenuPopover position={positionMatchWidth}>
        <MenuItems>
          <MenuItem onSelect={action("Download")}>Download</MenuItem>
          <MenuItem onSelect={action("Copy")}>Create a Copy</MenuItem>
          <MenuItem onSelect={action("Mark as Draft")}>Mark as Draft</MenuItem>
          <MenuItem onSelect={action("Delete")}>Delete</MenuItem>
        </MenuItems>
      </MenuPopover>
    </Menu>
  )
}

**Comment by NerdCowboy** [comment]
@chancestrickland  Finally getting around to taking a look at this.

That's pretty convenient for matching the width of the `MenuButton` but I want to be able to set the default alignment of the dropdown to the right edge of the `<MenuButton>` and still having the width of the dropdown be automatic.

I saw in your comment that I can write my own logic to do that manually, which is a great for more complex use cases.

But from an API standpoint, it would be greatly preferred to just be able to pass in a default alignment property. This is a very common pattern as it's almost always the desired behavior for right-aligned dropdowns, popovers, or tooltips. The logic is already there for aligning it left, so it feels like a waste to re-measure and recreate collision detection on the consumer side.

Is that something that you think we can add? Happy to try my hand at a PR if so. Was thinking we could add a new prop, `defaultAlignment="right"` on the `MenuPopover`.

**Comment by chancestrickland** [comment]
Reach UI is designed to be a lower-level library than many other component libraries. As such we tend to avoid style props, as those can and often should be handled by a library built on top of Reach UI.

That said, take a look at our popover package where we define a few position functions that you can use here (`positionDefault` and `positionMatchWidth`). If you'd like to write one that handles left-positioning, we can export it from `@reach/popover` and your lib/project can abstract that as a prop if you'd like!

**Comment by BrunoQuaresma** [comment]
Just as extra info, you can import this `import { positionRight } from '@reach/popover';`

**Comment by NerdCowboy** [comment]
Thanks for updating, meant to add a link to my PR for positionRight:
https://github.com/reach/reach-ui/pull/484
