### ISSUE TITLE
[VisuallyHidden] No need for display: block with position: absolute

### ISSUE THREAD

**Issue by pepelsbey** [reach/reach-ui#372]
## 🐛 Bug report

Existing `position: absolute` property makes elements behave like it’s `display: block`.

```jsx
let style = {
  display: "block", // <-- this
  border: 0,
  clip: "rect(0 0 0 0)",
  height: "1px",
  width: "1px",
  margin: "-1px",
  padding: 0,
  overflow: "hidden",
  position: "absolute"
};
```

### Current Behavior

Extra `display: "block"` present.

### Expected behavior

`position: "absolute"` would be enough.

### Suggested solution(s)

Remove `display: "block"`.

### Additional context

I’d be happy to be proved wrong if this is something you might need in some particular cases. Also, `white-space: nowrap;` might help in some cases, have you considered to adding it?

**Comment by chancestrickland** [comment]
Updated in 0.6.2
