### ISSUE TITLE
Handle `event.key` for IE 11

### ISSUE THREAD

**Issue by RealMattOwen** [reach/reach-ui#374]
### Current Behavior

Trying to dismiss `@reach/dialog` using the `Escape` key does not work in IE 11.

### Expected behavior

Using the `Escape` key should successfully dismiss `@reach/dialog` in IE 11.

### Reproducible example

I have not been able to test this CodeSandbox on IE11 but this is the same usage as within my application so I don't believe there is any other differences.
 
[CodeSandbox Reproduction](https://codesandbox.io/s/reach-ui-template-5holm)

### Suggested solution(s)

Add additional checks for the IE 11 variants of `event.key` values as shown in the link below in the last example on the page. In this specific case it appears that there also needs to be a check for `Esc`. I believe this `event.key === 'Escape' || event.key === 'Esc` should be sufficient.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

Note: the MDN example has comments that this is the case for Edge too but when testing on the latest version of Edge I was unable to reproduce.

### Additional context

I also noticed that there are quite a few other occurrences across all reach-ui packages where the IE 11 value is not supported, whether every occurrence should be updated as a part of this issue, I'm not sure.

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| @reach/dialog | 0.5.4
| React                    | 16.11.0
| Browser                  | Internet Explorer 11
| Assistive tech           | N/A
| Node                     | 12.13.0
| npm/yarn                 | 6.13.0
| Operating System         | Windows 10

**Comment by chancestrickland** [comment]
React normalizes keyboard events. I tested escape for Reach Dialog on https://reacttraining.com/reach-ui/dialog/ in IE11 with no issues (though I am noticing some CSS bugs that we should probably fix, so thanks for flagging no less!). 

I actually can't open the CodeSandbox link at all in IE11. Are you able to reproduce in an real environment elsewhere I could look at?

**Comment by RealMattOwen** [comment]
My apologies, I opened this issue late at night and completely forgot that the build process for my application uses Preact.. which appears to not normalize events as React does, thanks!
