### ISSUE TITLE
[MenuList] Display none does not remove menubutton from keyboard nav list

### ISSUE THREAD

**Issue by ccveer** [reach/reach-ui#392]
## ❓Question

**Pre-requisite:** I have a MenuList with multiple items and one of them hides based off of screen size using display none.

```
<Menu>
    <MenuButton>
        Actions
    </MenuButton>
    <MenuLis>
        <MenuItem onSelect={func1}>
            ...
        </MenuItem>
        <MenuItem onSelect={func2} classname="hideMeSometimes">
            ...
        </MenuItem>
        <MenuItem onSelect={func3}>
            ...
        </MenuItem>
    </MenuList>
</Menu>
```

```
.hideMeSometimes {
    @include query(767) {
        display: none !important;
    }
}
```

**Problem:** This only visually hides the button. It is still rendered in the dom, so it still has a spot in keyboard nav and we watch focus disappear for one click of the down arrow before re-appearing on the next MenuItem.

**Question:** Do I have to use something like window.innerWidth and conditionally render my MenuItem or is there a way for me to get reach to reflect display none in keyboard nav?

**Comment by chancestrickland** [comment]
@ccveer I would advise conditionally rendering instead. Any child `MenuItem` or `MenuLink` will be counted as a navigable component, and I'm not sure if we want to add an additional check for computed styles or not (not ruling it out, but I'd like to think on this a bit before marking this as a bug). You can use `@reach/window-size` or write the logic yourself if you'd like, but either should work.
