### ISSUE TITLE
Hiding expensive-to-render content

### ISSUE THREAD

**Issue by viridia** [reach/reach-ui#398]
## 🚀 Feature request

This is a general request to allow widgets such as tabs and menus to not pre-render their content.

For large, complex web sites rendering of hidden content can be expensive and put a strain on the browser. Here are a couple of use cases:

* A social networking site or chat application has text messages with a "..." button that opens a popup menu. There may be hundreds of messages on a page, which means hundreds of copies of the same popup menu.
* A tab panel might be used to control user preference settings panes. Those panes might include components which fetch data from the server as part of their lifecycle.

In such cases, it is highly desirable that the children not be executed at all rather than simply hidden at the DOM level. The most straightforward way to handle this is via the 'renderprops' pattern, where the children are an executable function.

### Who does this impact? Who is this for?

Large complex web applications.

**Comment by chancestrickland** [comment]
Can you not do something like this?

```js
<Tabs value={tabIndex} onChange={setTabIndex}>
  <TabList>
    <Tab>Tab 1</Tab>
    <Tab>Tab 2</Tab>
    <Tab>Tab 3</Tab>
  </TabList>
  <TabPanels>
    {tabIndex === 0 && <TabPanel>{getExpensiveContent(0)}</TabPanel>}
    {tabIndex === 1 && <TabPanel>{getExpensiveContent(1)}</TabPanel>}
    {tabIndex === 2 && <TabPanel>{getExpensiveContent(2)}</TabPanel>}
  </TabPanels>
</Tabs>
```

**Comment by viridia** [comment]
That works. I assume there's no ARIA problem with not pre-rendering the content that is associated with a particular tab.

**Comment by chancestrickland** [comment]
I would probably manually test it with a screen reader to be sure (I may try myself if I have time), but I don't believe it should make a difference. A SR won't announce the tab content of an inactive tab anyway, so I don't *think* it should care whether or not all tabs are present in the DOM so long as the active tab is available. You could also conditionally render the inside content instead:

```js
<TabPanel>{tabIndex === 0 ? getExpensiveContent(0) : 'Some fallback content'}</TabPanel>
