### ISSUE TITLE
[Tooltip] Not working locally or on demo website

### ISSUE THREAD

**Issue by jkjustjoshing** [reach/reach-ui#399]
## 🐛 Bug report

The tooltips at https://reacttraining.com/reach-ui/tooltip don't seem to be working. I also installed the tooltip package from NPM and it doesn't seem to be working in my local repo either (reproduced in this basic Codesandbox - https://codesandbox.io/s/wonderful-moon-qgqwc).

It appears that the button is doing absolutely nothing.

### Environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| **@reach/tooltip** | 0.6.2
| React                    | 16.8.6
| Browser                  | Firefox 70.0.1
| Assistive tech           | None
| Node                     | Whatever Codesandbox is using
| npm/yarn                 | Whatever Codesandbox is using
| Operating System         | macOS Mojave 10.14.6

**Comment by chancestrickland** [comment]
I don't have an issue here on either the docs site or your repro. I tried in FF 70.0.0 and FF dev edition 71.0b and tooltips work as expected. You should see the tooltips when hovering or focusing on buttons, not by clicking.

**Comment by jkjustjoshing** [comment]
Ah, that was my problem. Since they were on buttons I was trying to click, which cancels the tooltip showing. Also the delay was preventing me from seeing the tooltip.

Would making the hover delay customizable be something the Reach team would be interested in seeing in a PR? The application I'm working on would work better with 0ms delay.
