### ISSUE TITLE
menu: Lighthouse says there are invalid aria attributes?

### ISSUE THREAD

**Issue by ryanflorence** [reach/reach-ui#4]
Says:

Failing elements:

```
<button
  id="some-button-id"
  aria-haspopup="menu"
  aria-controls="some-id"
  aria-expanded="false"
  type="button"
>
  Actions <span aria-hidden="true">▾</span>
</button>
```

It doesn't tell me which attribute though, as far as I can tell those are all valid aria attribute values? Anybody know what it wants?

**Comment by jtmcgrath** [comment]
Could be that `aria-controls="some-id"` is invalid because there isn't an element which matches that id?

**Comment by ryanflorence** [comment]
Ah, yes, that makes sense. When I checked the DOM to see if the ids matched up the menu was visible, but when lighthouse runs it's not rendered at all.

Additionally, I think aria-controls is pointless in the dropdown menu anyway: http://www.heydonworks.com/article/aria-controls-is-poop

After I read that I had a conversation with @Heydon where he convinced me it's redundant. I'm going to remove it.

**Comment by ryanflorence** [comment]
![dl3-qypu4aurao2](https://user-images.githubusercontent.com/100200/44877586-484ef100-ac59-11e8-8c78-bab2b84fb19c.jpg)

Of course, lighthouse can only tell us so much :)

**Comment by Heydon** [comment]
@ryanflorence Can't complain, though 💯

**Comment by ring2727dexter** [comment]
how or where are you able to change or remove **aria-controls="some-id"**
