### ISSUE TITLE
[Tabs] Can't conditionally render tabs!

### ISSUE THREAD

**Issue by Ericnr** [reach/reach-ui#406]
Can't return null inside TabList or TabPanels. ex:
```jsx
<TabList>
    {!tab1 && <Tab>Switch to tab #1</Tab>}
</TabList>
```
error: 
```
Element type is invalid: expected a string (for built-in components) 
or a class/function (for composite components) but got: undefined.
```
Using a ternary and returning an empty React.Fragment works though.
#274 was supposed to fix this I think, but it still happens.

Reproduction: [Code Sandbox](https://codesandbox.io/s/naughty-mclean-bqk3i)

**Comment by chancestrickland** [comment]
Fixed in  v0.6.4, but note that in your example you aren't controlling the state of the tabs which will probably lead to some buggy behavior regardless (you should always render a TabPanel if the tab is active). Made some changes but this shows conditional rendering should work as expected. https://codesandbox.io/s/priceless-butterfly-gr5eb

**Comment by Ericnr** [comment]
Uh, I thought you could use the component both controlled and uncontrolled. 

Sorry if I was unclear, In your example you didn't achieve what I was trying to do. I don't want to just unmount the TabPanel that is not active. I wan't, for an example, to be able to hide both the Tab button and its TabPanel when the user doesn't have the permission to access it. The toggle button was supposed to really hide a tab completely from the user, like it does in my example if you use React.Fragment.

The latest version seem to have fixed it now and its working as expected after I upgraded to version in the sandbox.

**Comment by chancestrickland** [comment]
Ah sorry, I wasn't sure what you were trying to achieve. That said, I still wouldn't advise rendering a TabPanel conditionally unless the tab isn't active, as that would definitely create an accessibility problem (in which case you still need to control the state to know).
