### ISSUE TITLE
MenuLink cannot be used with react-router Link in TypeScript

### ISSUE THREAD

**Issue by sciyoshi** [reach/reach-ui#407]
### Current Behavior

Using `<MenuLink as={Link} to="/">Text</MenuLink>` fails to compile with TypeScript.

### Expected behavior

`<MenuLink as={Link}>` should work correctly.

### Reproducible example

[CodeSandbox example](https://codesandbox.io/s/distracted-franklin-kb1xf)

### Suggested solution(s)

Type for `ResolvedMenuLinkProps` should use `T extends Omit<React.HTMLProps<HTMLAnchorElement>, "role"> ? T : never`

### Additional context

Introduced with this change: https://github.com/reach/reach-ui/commit/18281e8be79e2cf2399408b835e5f0879f657592#diff-697ebb4dd7523eae89a076bebe3f9cd6R27

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| @reach/menu-button | 6.1.4
| React                    | 16.12.0

**Comment by chancestrickland** [comment]
Should be fixed in 0.7.0. Added an example using this case as well just to be sure!
