### ISSUE TITLE
Missing Package Versions

### ISSUE THREAD

**Issue by indiesquidge** [reach/reach-ui#408]
## 🐛 Bug report

NOTE: this is more of an inquiry on the current publishing strategy than an explicit "bug".

### Current Behavior

Some versions of this package do not seem to exist. For instance, I  can't find some packages (like `tabs`, among others) for [v0.6.3], I can't find some packages (like `utils` or `auto-id`, among others) for [v0.6.2], etc.

### Expected behavior

Similar to how React keeps `react` and `react-dom` packages in version sync, I would expect (or perhaps just prefer Reach UI packages to exist for all [releases]. This makes it easier to upgrade multiple Reach UI packages at the same time, and also makes it easier to use the packages via a CDN like Unpkg.

It seems the reason this doesn't currently happen is because only the packages with file changes get a version bump on new release, as can be seen via the release notes (e.g., `dialog` is in the change log for v0.6.3 and indeed that package [exists][1] for that version). 

### Reproducible example

[See hyperlinks above]

### Suggested solution(s)

I'm not privy to the changes this would require at a config level (perhaps this is configurable with [Yarn Workspaces]?).

[v0.6.3]: https://unpkg.com/@reach/tabs@0.6.3/index.js
[v0.6.2]: https://unpkg.com/@reach/utils@0.6.2/index.js
[releases]: https://github.com/reach/reach-ui/releases
[Yarn Workspaces]: https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/#introducing-yarn-workspaces

[1]: https://unpkg.com/@reach/dialog@0.6.3/index.js

**Comment by chancestrickland** [comment]
We will likely shift to independent versioning for each component after we get to 1.0, but we have no plans to change our approach at this time. This does mean that, in the mean time, sometimes packages will skip patch release versions if they don't change between releases. You'll need to rely on npm/yarn to upgrade rather than assuming each patch version should be the same for all components.
