### ISSUE TITLE
[MenuButton] Provide a mechanism to focus on a specific MenuItem when the Menu opens

### ISSUE THREAD

**Issue by wileym** [reach/reach-ui#409]
### Current Behavior

The `Menu` component provides no mechanism for users to specify which `MenuItem` should be focused when the Menu opens.

### Desired Behavior

Enable behavior like presently exists for the native HTML `select` element where, upon opening the `select` menu, the currently selected option is given focus/highlight. 

### Suggested Solution

Provide a `MenuItem` prop (say `focusOnOpen` or something) that results in the corresponding `MenuItem` receiving highlight/focus when the menu is opened. Guards for multiple `MenuItems` using the prop would obviously be needed.

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Provide a `Menu` or `MenuList` prop that instructs the component to focus on the last selected item when the menu is opened (`openOnLastSelected` or something)

Provide the `context` (MenuContext) as a property in the `Menu` `children` function so API users have more insight into the state of the `Menu`.  Seems dangerous though...

### Additional context

I'm trying to use `Menu` to create something similar to: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

**Comment by chancestrickland** [comment]
`MenuButton` is not a listbox and should not be used to recreate a listbox. We are working on a `Listbox` component but I would highly discourage you from going down this route as it would certainly be a misuse of aria roles.

I'd use a regular select for now if possible, or look for an alternative until we release `Listbox` (hopefully in the next couple of weeks)

**Comment by wileym** [comment]
Thanks Chance. I'll keep an eye out for ListBox
