### ISSUE TITLE
Tooltip configurable timers

### ISSUE THREAD

**Issue by skokenes** [reach/reach-ui#411]
### Current Behavior

The tooltip is hardcoded with the following timer values:

rest timer: 100ms
leave timer: 500ms

### Desired Behavior

These values sometimes produce an awkward UX, especially the leave timer of 500ms which can feel like an eternity after the user stops focusing an element with a tooltip. It would be great to be able to pass props to control what these timer values are.

### Suggested Solution

Provide props like `leaveTime`, `restTime` for the `Tooltip` component to override the 100ms, 500ms default values

### Who does this impact? Who is this for?

All users of the tooltip that want to customize it for their UX.

### Describe alternatives you've considered

My alternative is to fork the library - I don't see any way to accomplish the desired feature with the existing @reach API.

**Comment by andreypopp** [comment]
The tooltip should probably be hidden immediately when element loses focus.

**Comment by skokenes** [comment]
I believe it doesn't hide immediately when an element loses focus in order to have a better experience when moving focus from one element to another. A timer is used to prevent flashing a tooltip on and off.

My perspective is that this is great but the default time is too long, causing an awkward UX when going from focusing an element to not focusing anything. I'd like to shorten that time

**Comment by chancestrickland** [comment]
We may consider this at some point but we're going to hold for the time being. Recommendations from W3 on specific tooltip behavior are still under consideration, and I suspect there may be spec around the timer details when they eventually land on something. I'd hate to introduce an API only to be forced to take it away.

**Comment by patrickdbakke** [comment]
@chancestrickland I have this working on a local fork. Would you entertain a PR with experimental props?

```
<Tooltip enterTime={1000} leaveTime={1000}/>
```

I could include a `console.warn` message "`enterTime` and `leaveTime` are non-standard props for tooltip timing, and this api may change at any tme"

**Comment by chancestrickland** [comment]
Per my comment above, I would prefer not to do that at this time. We may consider it after our WebAIM review, but in the mean time If you have a need for this I'd recommend using https://www.npmjs.com/package/patch-package

**Comment by patrickdbakke** [comment]
Sounds good! Thanks @chancestrickland !

**Comment by gnapse** [comment]
Isn't it the current recommendation to remove the tooltip as soon as the element looses focus or on mouse out?

> If the tooltip is invoked when the trigger element receives focus, then it is dismissed when it no longer has focus (onBlur). If the tooltip is invoked with mouseIn, then it is dismissed with on mouseOut.

It doesn't mention anything about keeping a delay after the triggering event occurs.

Source: https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-21
