### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by hedgehog34** [reach/reach-ui#412]
### Current Behavior

Browser autocomplete popup is appearing on top of conbobox popover in Chrome
Same behaviour I discovered on first "Basic, Fixed List Combobox" example of Combobox here:
https://reacttraining.com/reach-ui/combobox

### Expected behavior

I was expecting to browser autocomplete to be completely switched off
### Reproducible example
https://reacttraining.com/reach-ui/combobox - "Basic, Fixed List Combobox" combobox example
### Suggested solution(s)
Using "autocomplete" and setting it up to "off" seems to be recommended action by MDN:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
but this prop is already reserved on `<ComboboxInput />` component

### Additional context

![Screenshot (2)](https://user-images.githubusercontent.com/3428656/70995624-e3770e80-20c8-11ea-969d-cf870374ecb1.png)
![Screenshot (3)](https://user-images.githubusercontent.com/3428656/70995763-38b32000-20c9-11ea-9857-0ce0c9f9896b.png)

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| **[REACH_PACKAGE_NAME]** | Combobox
| React                    | 16.11.0
| Browser                  | 78.0.3904.108 (Official Build) (64-bit)
| Assistive tech           | No
| Node                     | 10.16.0
| npm/yarn                 |  6.9.0
| Operating System         | Windows 10

**Comment by hedgehog34** [comment]
I was able to "switch off" browser's autocomplete from "outside" by placing my `<ComboboxInput />` inside the form element and using `autocomplete="off"` on the form itself.

**Comment by xtalx** [comment]
you can add that dom attribute with
`<ComboboxInput autoComplete="off" />`
The component prop is 'autocomplete'
The input dom attribute is 'auto**C**omplete'
