### ISSUE TITLE
MenuItem doesn't compose

### ISSUE THREAD

**Issue by dlwalsh** [reach/reach-ui#413]
### Current Behavior

Composing MenuItem in the following manner breaks basic functionality such as closing when clicking outside the menu.

e.g.

```js
const MyMenuItem = forwardRef((props, ref) => (
  <MenuItem {...props} ref={ref} />
));
```

### Expected behavior

I expect to retain important menu behaviour like closing when clicking outside the menu or pressing escape.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/peaceful-mclean-1r9i7)

**Comment by chancestrickland** [comment]
This should be fixed in 0.7.0. https://codesandbox.io/s/staging-cdn-bcx7e
