### ISSUE TITLE
[Combobox] Define custom input component

### ISSUE THREAD

**Issue by asakalou-exadel** [reach/reach-ui#418]
## ❓Is it possible to define custom input component instead of default one.
We need to display formatted content like tags but now there is no way to do this because `as` property supports only string values and works only for `input` and `textarea` but we need custom input component to be rendered.

Thanks!

**Comment by chancestrickland** [comment]
Can you point to an example of what you're trying to simulate? If it's what I think it is, this may be out of scope for Combobox as it exists today. I think you could probably simulate this with an visually hidden wrapper div that injects the tags where you want them using `@reach/rect`, but the input itself definitely needs to be an actual text input field.

**Comment by asakalou-exadel** [comment]
Sorry for the delay.

We already have custom components library and would like to reuse what we have. We have custom input component which is a wrapper over native `input`. 
We want to pass this component  down to reach/combobox in order to reuse what we have rather than copy pasting styles and behaviour.

Please see example below.
`FormSelect2Input` is a custom component which we want to pass to `as` prop of combobox.

According to current typings it's not possible since combobox supports only input.

Is there a way to pass anything except input to combobox or what is the most correct solution in our case?

```
const FormSelect2Input = React.forwardRef<HTMLDivElement, FormInputProps>((props, ref) => {
    return (
      <FormInput
        abcId={props.abcId}
        id={props.id}
        name={props.name}
        innerRef={ref}
        inputProps={{ autoComplete: 'off' }}
        {...props}
      />
    )
  })

<Combobox openOnFocus={true} onSelect={this.handleSelect}>
  <div className={controlContainerClasses}>
    <ComboboxInput
      as={FormSelect2Input}
      autocomplete={false}
      aria-labelledby="demo"
      className={styles.control}
      onChange={this.handleInputChange}
      onFocus={this.handleFocus}
      onBlur={this.handleBlur}
      value={inputValue}
      onKeyDown={this.onKeyDown}
    />
  </div>

  <ComboboxPopover className={styles.menuWrapper} ref={this.containerRef}>
    {menuListRenderer!(
      results.length > 0 ? (
        <ComboboxList className={styles.menu}>
          {results.map((r, index) => (
            <CustomOption
              key={index}
              option={r}
              optionRenderer={optionRenderer!}
              selectedItems={selectedItems}
              onClick={this.handleOptionClick}
              onFocus={this.handleItemFocus}
            />
          ))}
        </ComboboxList>
      ) : (
        <div>{noOptionsMessage!({ inputValue })}</div>
      ),
    )}
  </ComboboxPopover>
</Combobox>
```

Thanks!

**Comment by CodingDive** [comment]
I'd also love to pass the `Input` component of my design system instead of having to style the `ComboboxInput`.

**Comment by alexluong** [comment]
Is there any update on the issue?

**Comment by chancestrickland** [comment]
`ComboboxInput` accepts an `as` prop that should work, I believe.

`<ComboboxInput as={MyCustomInput} />`
