### ISSUE TITLE
Dialog: Failed prop type: Calling PropTypes validators directly is not supported

### ISSUE THREAD

**Issue by danieltott** [reach/reach-ui#420]
## 🐛 Bug report
Using `<DialogContent>` with an `aria-label` or `aria-labelledby` value (which happens by default when using `<AlertDialog>`) results in the following console warning:

```
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
```

### Expected behavior

There would be no console warnings for correct usage.

### Reproducible example

`<Dialog>` with `aria-label` example:
https://codesandbox.io/s/vigorous-kilby-ubkt9

AlertDialog default example:
https://codesandbox.io/s/vigilant-engelbart-hzzg5

![image](https://user-images.githubusercontent.com/360261/72084809-2f852f80-32d2-11ea-9615-3408535296a1.png)

### Suggested solution(s)

Looks like this is the offending line:
https://github.com/reach/reach-ui/blob/964f4df9e439ccb127fb515b2431628a04e5b191/packages/dialog/src/index.js#L232

I'm not entirely sure what the fix is yet but I could take a stab at it.

### Additional context

- `@reach/dialog`: `0.7.1`,
- `react`: `16.12.0`,
- `react-dom`: `16.12.0`,
- `react-scripts`: `3.0.1`

### Your environment

| Software                 | Name/Version(s) |
| ------------------------ | --------------- |
| `@reach/dialog` |`0.7.1`
| React                    |`16.12.0`
| Browser                  |Firefox, Chrome
| Assistive tech           |n/a
| Node                     |
| yarn                 |`1.21.1`
| Operating System         |`MacOS 10.15.2 (Catalina)`

**Comment by chancestrickland** [comment]
Fixed in 0.7.2!
