### ISSUE TITLE
[Tabs] TabPanel hidden attribute can't be overridden

### ISSUE THREAD

**Issue by xtalx** [reach/reach-ui#438]
### Current Behavior

In the latest version (0.7.3) I noticed two issues, the first is less important
1. The 'isSelected' prop appears to be no longer passed to the TabPanel component
2. There appears to be no way to override the hidden attribute. This makes it difficult to do certain animations without resorting to `[data-reach-tab-panel],[data-reach-tab-panel][hidden] {display: block !important}`

### Expected behavior

I expect to be able to set hidden to false on the TabPanel and it not be applied to the dom node

### Reproducible example
[v0.6.2 works as expected](https://codesandbox.io/s/reach-tabs-old-expected-behavior-hbl9d?fontsize=14&hidenavigation=1&theme=dark)

[v0.7.3 doesn't work as expected](https://codesandbox.io/s/reach-tabs-new-unexpected-behavior-0zrnc?fontsize=14&hidenavigation=1&theme=dark)

### Suggested solution(s)

I only looked briefly at the code, and not sure what some of it does but could moving the props spread below 'hidden' do the trick

```js
//TabPanel
      <Comp
        hidden={!isSelected}
        {...props}
        isSelected={isSelected} //adding this would be cool
        ref={ref}
        data-reach-tab-panel=""
        aria-labelledby={makeId(tabsId, "tab", index)}
        id={id}
        role="tabpanel"
        tabIndex={-1}
      >
        {children}
      </Comp>
```

### Additional context

Hopefully I didn't miss something in the docs. Thanks for your time!

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    tabs     | 0.7.3        |
| React            |         |      16.12.0   |
| Browser          |    Chrome     |  79.0.3945.117  |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |     yarn    | 1.21.1  |
| Operating System |    MacOS     |  10.15.2       |

**Comment by chancestrickland** [comment]
Should be good in 0.7.4!

**Comment by xtalx** [comment]
That was fast! Thanks!!!
