### ISSUE TITLE
menu-button PopoverMenu styles are not working

### ISSUE THREAD

**Issue by InfraK** [reach/reach-ui#441]
### Current Behavior

```i
mport styled from 'styled-components';
import {
  MenuPopover as _MenuPopover,
} from '@reach/menu-button';

export const MenuPopover = styled(_MenuPopover)`
  width: 100%;
  z-index: 1;
  background-color: red;
`;
```
![image](https://user-images.githubusercontent.com/20978394/73015089-2af46700-3dfa-11ea-94a1-77d65e4ce99f.png)
Trying to style the popover like above, renders two reach portals and popovers. The first one shows the styles but does not have a height (and is not rendered).

![image](https://user-images.githubusercontent.com/20978394/73015096-2def5780-3dfa-11ea-88d4-54f8cfb1c777.png)

while the other one is rendered to the DOM (has a height) with the default @reach-ui styles.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/fancy-shadow-6bowh)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     @reach/menu-button    |    0.7.3     |
| React            |         |     16.11    |
| Browser          |     Chrome    |     79.0.3945.88    |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by CodingDive** [comment]
Thank you for opening this issue. I also had this problem and originally posted it here https://github.com/reach/reach-ui/issues/316#issuecomment-553167456

**Comment by chancestrickland** [comment]
Thanks! I actually think this should be resolved in the next release thanks to https://github.com/reach/reach-ui/commit/00d9398a0faad21e894690fc7d7300beb8c00d64. Just adjusted the styled components example to include a styled popover and it seems to work now in Storybook. I'll keep this open until the release today or tomorrow.

**Comment by chancestrickland** [comment]
Should be good in 0.7.4!
