### ISSUE TITLE
@reach/alert Yarn v2 compatibility

### ISSUE THREAD

**Issue by PabloSzx** [reach/reach-ui#445]
## 🐛 Bug report

Trying to migrate a Next.js project to yarn v2 I encountered this problem 

```./.yarn/$$virtual/@reach-component-component-virtual-c06d27a5be/0/cache/@reach-component-component-npm-0.1.3-94c20ffc6f-1.zip/node_modules/@reach/component-component/es/index.js
Module not found: A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't`
```

And in the minimal repository I made for this issue I get:

```
[ error ] ./pages/index.js
Module not found: Something that got detected as your top-level application (because it doesn't seem to belong to any package) tried to access a package that is not declared in your dependencies
```

### Current Behavior

<img width="950" alt="WindowsTerminal_1pPHT4Vblk" src="https://user-images.githubusercontent.com/8672915/73194215-1e3e7e80-412c-11ea-8adf-83db8cffe00d.png">

### Expected behavior

To work

### Reproducible example

https://github.com/PabloSzx/reach_alert_bug_yarn_v2

### Suggested solution(s)

Fix the dependency declaration in @react/component-component

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   alert      |    latest     |
| React            |         |   16.12.0      |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |    13     |         |
| npm/yarn         |    yarn     |    2     |
| Operating System |   Windows      |     10    |

**Comment by chancestrickland** [comment]
We have no immediate plans to support Yarn 2 at this point, but if you have a specific fix that would do the trick I'd love to hear it. I need a little more info than `Fix the dependency declaration in @react/component-component`, as I'm unsure what Yarn 2 demands that we would do differently than Yarn 1.

**Comment by PabloSzx** [comment]
I checked out the source code and I found nothing wrong, it seems to be a [deeper problem with Next.js compatibility](https://github.com/zeit/next.js/issues/10298) and @reach-ui/alert just happened to try to compile first in my migration.
I'm sorry.
