### ISSUE TITLE
[Combobox Docs] Multiple selected values example on website

### ISSUE THREAD

**Issue by brennj** [reach/reach-ui#446]
##  📖 Documentation

Hi guys! I'm using and loving the Combobox, the API is great and was really helpful in a lot of use cases for me so far.

I've made a multiple selections input (where values are rendered as tags) but I'm not fully sure I'm doing best practices. Having a multiple values example in the docs, like the one Ryan [has here in his tweet](https://twitter.com/ryanflorence/status/1188604237090975745) would be amazing.

### Further info

I have done one multiselect example that I would be happy to make a PR for documentation but not fully sure if it is completely right. (this part can be ignored though, understand it borderlines into usage question territory!)

The thought process I have for making the Input accept and display multiple values is as follows:

1. Render the `ComboboxInput` in a wrapper that handles rendering of selected values.
2. In the wrapper, handle focus logic so that when you click anywhere in the wrapper, you're redirected to the focus of the input.
3. Other small quality of life things like allowing the user to respond to backspace keyboard events when they want to delete a previously selected value.

It means the state management of viewable options is left to the user to render correctly. 

I can share the code in a follow up codesandbox if its a valid case to add this to documentation :)

**Comment by chancestrickland** [comment]
This example is a out of scope for our existing combobox. We may build something like this in the future that composes on top of combobox, but that is TBD.
