### ISSUE TITLE
Broken Slider example on website

### ISSUE THREAD

**Issue by BurntCaramel** [reach/reach-ui#451]
## 📖 Documentation

The Slider documentation has a broken example under the Usage section: https://reacttraining.com/reach-ui/slider

<img width="841" alt="image" src="https://user-images.githubusercontent.com/2635733/73581930-1c373f80-44df-11ea-9229-83d8d6124506.png">

I can’t quite see what the problem is to create a PR — is it needing to have only one function to return?

**Comment by chancestrickland** [comment]
Good catch! Removed this as it doesn't really need to be a demo. It's the same code as the demo right above that section.
