### ISSUE TITLE
Body styles when opening dialog

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#457]
## ❓Question

I have two questions about the styles that get added to `body` element when opening dialog:

1. Why are the paddings and margins reset?
2. Where do these styles come from? I can't find a reference in the `@reach/dialog` package.

![image](https://user-images.githubusercontent.com/23662329/73746759-9cb7a380-475e-11ea-9ddd-3139a0b863ab.png)

Thanks!

**Comment by chancestrickland** [comment]
AFAICT this appears to come from the `react-remove-scroll` lib we use in Dialog. I believe it detects some values based on your system's scrollbar UI and sets these style properties aggressively to reduce jank when scrollbars are hidden as a result of the dialog opening.
