### ISSUE TITLE
[Combobox] Missing type defintion file

### ISSUE THREAD

**Issue by JaceHensley** [reach/reach-ui#458]
## 🐛 Bug report

`@reach/combobox@0.8.0` doesn't include a index.d.ts file, 0.7.4 has the type file tho

**Comment by charliewilco** [comment]
https://www.unpkg.com/@reach/combobox@0.8.0/dist/index.d.ts

**Comment by chancestrickland** [comment]
Weird! Fixed in 0.8.2 https://www.unpkg.com/@reach/combobox@0.8.2/dist/index.d.ts
