### ISSUE TITLE
Slider issue with min / max / and step

### ISSUE THREAD

**Issue by zenios** [reach/reach-ui#470]
## 🐛 Bug report

When having a slider with 
* min : 505
* max: 5005
* step: 500

And start dragging the slider instead of going 505, 1005, 1505 it goes 505, 1000, 1500 and goes on

**Comment by chancestrickland** [comment]
Hi! Please remember to use the provided bug report template when opening issues.

If you can provide a reproducible demo, I'll reopen this issue.
