### ISSUE TITLE
Slider keyboard interaction triggers page scroll

### ISSUE THREAD

**Issue by hd4ng** [reach/reach-ui#471]
### Current Behavior
When moving slider via keyboard, it also scroll the page. For example, when press Home, End, Page Up, Page Down the page will scroll.

### Expected behavior
The page should not scroll when handling Slider via keyboard

### Reproducible example
It can be tested in the document website: https://reacttraining.com/reach-ui/slider

### Suggested solution(s)
Add `event.preventDefault()`. I don't know why you did comment that.
https://github.com/reach/reach-ui/blob/a4a6abbf572eb207b14fc8fb620af267286e431d/packages/slider/src/index.tsx#L374

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   Slider      |      0.8.2   |
| React            |   16.12.0      |         |
| Browser          |     Chrome    |         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chancestrickland** [comment]
Fixed in 0.8.4
