### ISSUE TITLE
[Accordion] Animation

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#472]
## ❓Question

I'm having a hard time animating Accordion properly with height. Accordion panel being set to `display: none` is not helping to achieve an animation either. Would really appreciate an example or some help 🙂

**Comment by raunofreiberg** [comment]
I could get it to work by using `react-spring`, controlling the index state of Accordion, and passing `isActive` to each `AccordionItem` by mapping over the children of `Accordion`.

Although:

1) I had to set `display: block !important` to `AccordionPanel` to make `react-spring` exit animation work.
2) Can I do this without controlling state? I would very much like to have the same result, but keep the `multiple` and `collapsed` props working.

![gif](https://i.gyazo.com/3bd24fe03ca2e51ef2583cbf379d9a72.gif)

**Comment by raunofreiberg** [comment]
@chancestrickland Would it be too much of a "hack" to pass `isActive` to `AccordionItem` by Reach [here](https://github.com/reach/reach-ui/blob/master/packages/accordion/src/index.tsx#L394)? I see that Tabs has the same logic, but it seems like this is up for deprecation?

My thinking here is that I don't want to handle the `collapsed` and `multiple` cases myself, and would rather just Reach tell me whether my AccordionItem is active.

**Comment by raunofreiberg** [comment]
Friendly ping @chancestrickland 

I think implementing animations is quite a common case for accessible components. Would love to come to a solution that doesn't affect the functionality 🙃

**Comment by chancestrickland** [comment]
On my todo list! May not get to it today but should be able to take a look next week.
