### ISSUE TITLE
[feature] @reach/context-menu

### ISSUE THREAD

**Issue by CodingDive** [reach/reach-ui#473]
## 🚀 Feature request
To follow up on the comment https://github.com/reach/reach-ui/issues/350#issuecomment-555863740, I'd love to see a context menu component to handle right clicks and provide an accessible menu that can be navigated with the keyboard.
To achieve this, I'd assume that a lot of code from the menu-button can be used as the two specs have quite a few similarities. 

### Specification and resources
A component that follows the [context-menu spec](https://www.w3.org/TR/2016/REC-html51-20161101/interactive-elements.html#context-menus). I also found that the [menu-button spec](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html) mentions the context menu. 

### Existing solution(s)
I found prior art [here](https://ej2.syncfusion.com/javascript/documentation/context-menu/accessibility/).

**Comment by chancestrickland** [comment]
Thanks for the request! The current plan is to stick to the components listed in the readme for 1.0. We may revisit new ideas in the future, but we're going to freeze the list as is for now. The big priority is finishing up what we have scheduled, cleaning up our APIs across the board, then going in for an accessibility audit before the first stable release.

**Comment by CodingDive** [comment]
I understand. Very excited for v1!
