### ISSUE TITLE
Can't build or test locally

### ISSUE THREAD

**Issue by NerdCowboy** [reach/reach-ui#477]
## 🐛 Bug report
After forking and cloning reach-ui to do a PR, I followed the instructions https://github.com/reach/reach-ui#getting-started and ran `yarn install` and then `yarn build`, which resulted in the error below.

I also noticed if I try to run `yarn test` I get a lot of missing child dependency errors, so wondering if Lerna isn't installing all of that properly.

```@reach/component-component: Building ES modules ...
@reach/component-component: /bin/sh: /Users/larsonb/OneDrive: No such file or directory
@reach/component-component: child_process.js:650
@reach/component-component:     throw err;
@reach/component-component:     ^
@reach/component-component: Error: Command failed: /Users/larsonb/OneDrive - Tivity Health/Code/reach-ui/node_modules/.bin/babel src -o dist/component-component.esm.js --ignore src/*.test.js --root-mode upward
@reach/component-component:     at checkExecSyncError (child_process.js:611:11)
@reach/component-component:     at execSync (child_process.js:647:15)
@reach/component-component:     at exec (/Users/larsonb/OneDrive - Tivity Health/Code/reach-ui/packages/component-component/build-package.js:14:3)
@reach/component-component:     at Object.<anonymous> (/Users/larsonb/OneDrive - Tivity Health/Code/reach-ui/packages/component-component/build-package.js:20:1)
@reach/component-component:     at Module._compile (internal/modules/cjs/loader.js:1151:30)
@reach/component-component:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
@reach/component-component:     at Module.load (internal/modules/cjs/loader.js:1000:32)
@reach/component-component:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
@reach/component-component:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
@reach/component-component:     at internal/main/run_main_module.js:17:47 {
@reach/component-component:   status: 127,
@reach/component-component:   signal: null,
@reach/component-component:   output: [ null, null, null ],
@reach/component-component:   pid: 34766,
@reach/component-component:   stdout: null,
@reach/component-component:   stderr: null
@reach/component-component: }
@reach/component-component: error Command failed with exit code 1.
@reach/component-component: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@reach/component-component'
```

### Current Behavior
Unable to run `yarn build` or `yarn test` due to errors and missing child dependencies.

### Expected behavior
Be able to build & test locally

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |      0.8.4   |
| React            |         |     NA    |
| Browser          |         |     NA    |
| Assistive tech   |         |     NA    |
| Node             |         |    13.9.0     |
| npm/yarn         |  yarn       |     1.21.1    |
| Operating System |    macOS     |   10.14.6      |

**Comment by chancestrickland** [comment]
Have you tried using Node 12? I haven't tested on v13 yet, but we're currently set up to support the latest stable which is 12.

**Comment by chancestrickland** [comment]
Just glancing at the error, it seems as if Node is breaking with your directory name. The space in `OneDrive - Tivity Health` appears to be the culprit. No idea whether or not it would work in Node 12 either, but if renaming your directory is an option that should probably at least fix it. Otherwise I'm not sure what we could do to address that here!

**Comment by NerdCowboy** [comment]
Ah, ya good call. It was the spaces 🤦‍♂️ Thanks!
