### ISSUE TITLE
support for package managers

### ISSUE THREAD

**Issue by schwamic** [reach/reach-ui#478]
## 🚀 Feature request
Thanks for all your work! Hopefully next time I create a PR instead of an issue :-) I just wanted to say that it would be nice if you could publish this library, so I can install it via `yarn ` or `npm`. 

ps.: There are also libraries that focus on accessibility and css-in-js solutions, maybe it would be useful to cooperate with each other; e.g. [chakra-ui](https://github.com/chakra-ui/chakra-ui/tree/master/packages/chakra-ui)?

**Comment by chancestrickland** [comment]
Hi! You can install any of our packages with Yarn or NPM. But Reach UI is not like Chakra UI in many ways. You don't install `@reach/reach-ui` and get everything. You install only the packages you need, like `@reach/dialog` or `@reach/tabs`. Take a look at the installation instructions in the docs, hopefully that helps!

**Comment by schwamic** [comment]
@chancestrickland thank you!
