### ISSUE TITLE
[Accordion] Incorrect onChange signature

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#482]
### Current Behavior

`Accordion` `onChange` is typed as:

`onChange?: (value: number | number[]) => void`

### Expected behavior

`onChange` should (?) be called with only type `number`.

### Reproducible example

https://codesandbox.io/s/lingering-river-9p547

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |         |
| React            |         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chancestrickland** [comment]
Fixed in 0.8.5
