### ISSUE TITLE
[Combobox] Support multiple listboxes

### ISSUE THREAD

**Issue by indiesquidge** [reach/reach-ui#485]
### Current Behavior

In the "[Lots of arbitrary elements][1]" example, we render heading tags within the `<ComboboxList>`, which is a `<ul>` under the hood. I believe it's invalid HTML to render anything other than [li and script-supporting elements][2].

```jsx
<ComboboxList>
  <h5>Other Fruits</h5> {/* <h5> is not a valid child element of <ul> */}
  <ComboboxOption value="Banana" />
  <ComboboxOption value="Kiwi" />
</ComboboxList>
```

### Desired Behavior

Be able to associate multiple `<ComboboxList>` components with a single `<ComboboxInput>`.

NOTE: snippet uses [ARIA 1.2 spec][3]
```jsx
<Combobox>
  <ComboboxInput aria-controls="list--1 list--2" />
  <ComboboxPopover>

    <h5>Top Fruits</h5>
    <ComboboxList id="list--1">
      <ComboboxOption value="Apple" />
      <ComboboxOption value="Orange" />
    </ComboboxList>

    <h5>Other Fruits</h5>
    <ComboboxList id="list--2">
      <ComboboxOption value="Banana" />
      <ComboboxOption value="Kiwi" />
    </ComboboxList>

  </ComboboxPopover>
</Combobox>
```

### Suggested Solution

Theoretically, this should be a single line change to `<ComboboxList>`.

```diff
<Comp
+ id={props.id || listboxId}
  {...props}
  ref={forwardedRef}
  data-reach-combobox-list=""
  role="listbox"
- id={listboxId}
/>
```

However, there are a couple concerns.

First, if folks add an `id` prop themselves but don't also add `aria-controls="my-custom-id"` to their `<ComboboxInput>`, then a11y breaks. This could be hard to police programmatically, and we already [allow aria overrides][4].

Second, it's not clear to me if this is even valid. None of the [ARIA examples][5] include multiple listboxes, and although space separated ids is a valid value for the attribute itself, I’m not sure if that’s valid for the specific role.

### Who does this impact? Who is this for?

This is fully backwards compatible, and wouldn't explicitly impact any current usages of Combobox. It would be great to get some accessibility experts here to **determine if it's valid for a `role="combobox"` element to have `aria-controls` controlling multiple `role="listbox"` elements**.

### Describe alternatives you've considered

One alternative could be to use the `as` prop and avoid list elements

```jsx
<ComboboxList as="div">
  <h5>Top Fruits></h5>
  <ComboboxOption as="div" value="Apple" />
  <ComboboxOption as="div" value="Banana" />
</ComboboxList>
```

However, I'm not sure if the rendered HTML is valid.

```html
<div role="listbox">
  <h5>Top Fruits></h5>
  <div role="option">Apple</div>
  <div role="option">Orange</div>
</div>
```

Even if it is valid, I've been told that one of the nice things about using `<ul>` and `<li>` is that if the AT hasn’t implemented support for something like `role="listbox"`, it will still retain the semantics of the original HTML elements.

[1]: https://reacttraining.com/reach-ui/combobox#lots-of-arbitrary-elements
[2]: https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element
[3]: https://www.w3.org/TR/wai-aria-practices-1.2/#combobox
[4]: https://github.com/reach/reach-ui/issues/447
[5]: https://www.w3.org/TR/wai-aria-practices-1.2/#examples-1

**Comment by chancestrickland** [comment]
The HTML in your alternative approach is totally valid, and I believe `role=listbox` is pretty widely supported these days. If that's still a concern for you, you can also sub your headings instead to validate the markup:

```html
<ul role="listbox">
  <span role="heading" aria-level="5">Top Fruits></span>
  <li role="option">Apple</div>
  <li role="option">Orange</div>
</ul>
```

I haven't seen any case studies with multiple listboxes as you've proposed. This would have to be device-tested pretty extensively before we could possibly implement it since there's nothing in the spec to validate your pattern. I imagine that to be somewhat unlikely, so I might look for one of the alternatives instead for the time being.

Interesting idea though! I'll leave this open for now, maybe someone else has a case study in the wild that already does this.

**Comment by chancestrickland** [comment]
Another alternative: you could use nested lists to validate your HTML.

```jsx
<ComboboxList>
  <li role="none">
    <h5>Top Fruits></h5>
    <ul role="none">
      <ComboboxOption value="Apple" />
      <ComboboxOption value="Orange" />
    </ul>
  </li>
  <li role="none">
    <h5>Other Fruits></h5>
    <ul role="none">
      <ComboboxOption value="Banana" />
      <ComboboxOption value="Kiwi" />
    </ul>
  </li>
</ComboboxList>
```

```html
<ul role="listbox">
  <li role="none">
    <h5>Top Fruits></h5>
    <ul role="none">
      <li role="option">Apple</li>
      <li role="option">Orange</li>
    </ul>
  </li>
  <li role="none">
    <h5>Other Fruits></h5>
    <ul role="none">
      <li role="option">Banana</li>
      <li role="option">Kiwi</li>
    </ul>
  </li>
</ul>

**Comment by indiesquidge** [comment]
> I haven't seen any case studies with multiple listboxes as you've proposed.

Here is at least [one example][1] that exists on the W3C Editor's Draft of Best Practices for Listbox. The source posits having the `role="listbox"` element as a `div` instead of a ul, and each "section" of options as `<ul role="group">`, and each section title as a list item like the rest of the options but with `role="presentation"`.

```html
<div tabindex="0" role="listbox">
  <ul role="group" aria-labelledby="land">
    <li role="presentation" id="land">Land</li>
    <li role="option">Cat</li>
    <li role="option">Dog</li>
  </ul>
  <ul role="group" aria-labelledby="water">
    <li role="presentation" id="water">Water</li>
    <li role="option">Dolphin</li>
    <li role="option">Whale</li>
  </ul>
</div>
```

[1]: https://w3c.github.io/aria-practices/examples/listbox/listbox-grouped.html

**Comment by chancestrickland** [comment]
Yep, that should work just as well. I'd say to test different implementations with various screen readers and see if one makes more sense than the others. The only potential advantage I can think of with using heading tag inside the first `li` is that many users navigate by heading, but I'm really not sure if they would when the cursor is in the listbox.

FYI, I just merged support for the `as` prop on `ListboxOption`. Shouldn't really change the discussion here, but everything previously discussed should be doable with the existing implementation. Let me know if you think I may have missed something here.
