### ISSUE TITLE
[Disclosure] Checkbox instead of Button

### ISSUE THREAD

**Issue by alexluong** [reach/reach-ui#498]
### Current Behavior

Currently, the only element that can be used to control `Disclosure` is `DisclosureButton`.

### Desired Behavior

I'd like to use `Checkbox` to control `Disclosure` as well. Especially now that `role=checkbox` seems to be [WAI-ARIA compliant]](https://github.com/w3c/aria/issues/681).

**NOTE**: I'm an a11y newbie, so please please correct me if I'm wrong.

### Suggested Solution

I can think of 2 ways to handle this:

1. Create a `DisclosureCheckbox` that users can use instead of `DisclosureButton`.

```jsx
<Disclosure>
  <label>
    <DisclosureCheckbox />
    Do a thing
  </label>
  <DisclosurePanel>...</DisclosurePanel>
</Disclosure>
```

2. Modify `DisclosureButton` to allow the use of `<input type="checkbox" />` instead of `<button />`

```jsx
<Disclosure>
  <DisclosureButton type="checkbox">Do a thing</DisclosureButton>
  <DisclosurePanel>...</DisclosurePanel>
</Disclosure>
```

### Who does this impact? Who is this for?

I have a use case for this, but I think this is a common pattern.

### Describe alternatives you've considered

The alternative which I plan to do while waiting for this issue to be addressed is to learn from the source code and re-create the component myself.

### Additional context

N/A

**Comment by alexluong** [comment]
Just learned about [the official WAI-ARIA list of components](https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure). It seems like `Disclosure` needs to be a `button`. Not sure if there's a way to get similar functionality with it using a `checkbox` instead.

**Comment by chancestrickland** [comment]
I would stick with a button to follow ARIA guidelines, but you can simulate a checkbox visually with some styling. https://codepen.io/chancethedev/pen/QWbMreQ
