### ISSUE TITLE
[Combobox] Add id or custom value to ComboboxOption

### ISSUE THREAD

**Issue by CodingDive** [reach/reach-ui#502]
## 🚀 Feature request
Upon rendering a list of items inside a `Combobox`, I'd love to pass the item id to each option without rendering the id. This would make it easier to handle the `onSelect` as I wouldn't need to filter the list by the selected item string to retrieve the id.

### Current Behavior
As far as I know, only text can be passed to the value of `ComboboxOption` which will be rendered to the DOM.

### Desired Behavior
Pass item id or custom data along.

### Suggested Solution
Add an extra `id` or `data` prop to the `ComboboxOption` and pass it along to the `onSelect` handler of the `Combobox`.

```
<Combobox onSelect={(value, data) => void alert(`You selected item with index ${data.index}!`}>
  <ComboboxInput
    aria-label="Cities"
    className="city-search-input"
    onChange={handleChange}
  />
  <ComboboxPopover className="shadow-popup">
    <ComboboxList aria-label="Cities">
      {results.slice(0, 10).map((result, index) => (
        <ComboboxOption
          key={index}
          data={{index}}
          value={`${result.city}, ${result.state}`}
        />
      ))}
    </ComboboxList>
  </ComboboxPopover>
</Combobox>
```

What do you think? If data is the second argument of `onSelect`, this wouldn't be a breaking change.

**Comment by CodingDive** [comment]
@chancestrickland I'd be happy to send a PR for this

**Comment by chancestrickland** [comment]
@CodingDive Considering this! I certainly see the value but I'd want to think through the implementation a bit. Happy to review a PR if you want to move ahead.

**Comment by dusty** [comment]
Do you see any problems in just adding an `onClick` handler to the `ComboboxOption` component and using that instead of the onSelect?

```
<Combobox>
  <ComboboxInput
    aria-label="Cities"
    className="city-search-input"
    onChange={handleChange}
  />
  <ComboboxPopover className="shadow-popup">
    <ComboboxList aria-label="Cities">
      {results.slice(0, 10).map((result, index) => (
        <ComboboxOption
          key={index}
          value={`${result.city}, ${result.state}`}
          onClick={() => void alert(`You selected item with index ${data.index}!`}
        />
      ))}
    </ComboboxList>
  </ComboboxPopover>
</Combobox>
```

**Comment by CodingDive** [comment]
@dusty haven't tried this one yet, thanks for sharing. I guess when onSelect and onClick are both present, one would need to write some extra code to coordinate between the two. Until my PR gets merged, this seems like a good solution indeed.

**Comment by dusty** [comment]
I went ahead and removed onSelect entirely and am just using onClick, seems to be working fine.

**Comment by CodingDive** [comment]
I'm worried that it won't work for some keyboard control but since reach-ui
is so good at handling focus management correctly, the onclick may always
be called

**Comment by dusty** [comment]
Good call, seems like that is a problem.

**Comment by igloude** [comment]
Bump on this one. Even exposing the selected option's key or something would be a huge help.

**Comment by indiesquidge** [comment]
@igloude, keys only make sense in the context of the surrounding array when looping over data, and serve as a hint to React, but they don’t get passed to components. If we want the same value in the component, we'd have to pass it explicitly as a prop with a different name.

Is there a problem you're trying to solve for here that [managing your own custom option data][1] doesn't cover? I'd love to have a [CodeSandbox][2] showing the issues you're running into.

[1]: https://github.com/reach/reach-ui/pull/514#issuecomment-630504047
[2]: https://codesandbox.io/s/reach-ui-template-xonfs

**Comment by joms** [comment]
I tried using the `onClick` method on `ComboboxOption`, but that did not do the trick for keyboard navigation.
However, I feel like passing the event (click or keydown) from the `ComboboxOption` up to `onSelect` in the `Combobox` would be a better solution. This would make the data-attributes usable for passing custom data in stead of passing objects around.
