### ISSUE TITLE
[Slider] multiple handles

### ISSUE THREAD

**Issue by jeremyswann** [reach/reach-ui#505]
### Current Behavior

Single slider handle with a single value output

### Desired Behavior

2 slider handles with an array (range) output

### Suggested Solution

Expect similar behaviour to [React Compound Slider](https://github.com/sghall/react-compound-slider). I like the ability here to use multiple handles, though this library is an over-abstraction in comparison to the Reach-UI Slider.

### Who does this impact? Who is this for?

Developers looking to do a "Price Range Slider" with an Array[min,max] value output to filter products within a price range.

### Describe alternatives you've considered

I could use 2 sliders, one for min price another for max price. I feel this clutters the UI, especially if you are trying to maintain a tight sidebar.

**Comment by chancestrickland** [comment]
This will likely be a separate component (`MultiSlider`) in the future, but we have no plans to add support in the current slider package at this time.
