### ISSUE TITLE
[Listbox] Long lists and overflow

### ISSUE THREAD

**Issue by cour64** [reach/reach-ui#510]
## 🚀 Feature request
Add auto scrolling on long lists and overflowed content

### Current Behavior
If I have a long list of ```ListboxOption```'s and I apply ```max-height``` and ```overflow-y: auto``` styles then ```ListboxOption```'s that are highlighted or selected could potentially be out of view as they are overflowing the ```ListboxPopover``` or ```ListboxList```.

### Desired Behavior
When a ```ListboxOption``` is highlighted, using ```ArrowUp``` or ```ArrowDown```, it is scrolled into view. Also when the ```ListboxPopover``` is opened the selected ```ListboxOption``` is scrolled into view.

### Suggested Solution
Either implement this functionality internally or emit an event when the ```Listbox```'s ```navigationValue```  changes so this can be done manually.

### Who does this impact? Who is this for?
All users

### Describe alternatives you've considered
Don't use long lists with ```Listbox``` and use a ```ComboBox``` instead. This is fine but sometimes there may not be a lot long list but each ```ListOption``` could have a large height.

**Comment by chancestrickland** [comment]
Related, https://github.com/reach/reach-ui/issues/357.

This may be something we want apps to implement as needed, but I will look into it!

**Comment by cour64** [comment]
@chancestrickland I have my own implementation for the time being. It uses a ```querySelector``` much like the solution's suggested in #357 so it's not perfect but it works none the less. 

Thanks for the response, you can close this issue if you want and keep #357 open
