### ISSUE TITLE
[Combobox] Accessible virtual list example

### ISSUE THREAD

**Issue by CodingDive** [reach/reach-ui#513]
I'd love to see an example where many `ComboboxOptions` are rendered within `react-window` or another virtual-list implementation. One of the problems of solely using such libraries is that all the a11y benefits from `@reach/combobox` are lost, oftentimes leaving developers to choose between performance and accessibility.
It'd be great to see an example that combines the best of both worlds! 😍

**Comment by chancestrickland** [comment]
I am not familiar with that library, but if it's helpful and easily achievable then I'd welcome it

My gut reaction is that you really shouldn't have so many items in a combobox that you'd need a virtual list. The whole idea is that you can narrow down options by typing, preventing the need for a huge scrollable list. Do you have a use case you feel justifies this kind of integration?

**Comment by CodingDive** [comment]
Yes, using the arrow keys without having typed anything 😅

**Comment by chancestrickland** [comment]
If it's a huge list I'd still probably recommend paginating options vs. a virtual list from a UX perspective, but unfortunately I don't get to design everyone's components 😅 I'll have to slap a `help-wanted` tag for now as I'm just not familiar enough with virtual lists to know what this would look like myself. If you or someone wants to submit a PR, I'll review the work, make sure screen reader response works as expected, and seek some feedback from accessibility folks who may be more familiar with the pattern than myself.

**Comment by et** [comment]
@CodingDive - I wired up an example here: https://codesandbox.io/s/epic-meninsky-csvqc?file=/src/App.tsx
I'm a rookie when it comes to accessibility but I have to imagine that a 50,000 item list will never be considered accessibly-friendly 😬 

@chancestrickland - Check out that example if you have a chance. As you can see, I can had to hack the `ref` options to programmatically close the popover. It'd be nice if there was a friendlier way to do that.

**Comment by CodingDive** [comment]
@et thanks for the link! It's not quite accessible as I can't be using the arrow keys to navigate.

**Comment by CodingDive** [comment]
.
