### ISSUE TITLE
MenuPopover creates a second, redundant portal

### ISSUE THREAD

**Issue by viridia** [reach/reach-ui#520]
### Current Behavior

I'm attempting to build a select widget using MenuButton, and in particular I am attempting to use positionMatchWidth to get the popover width to match the width of the menu button. Unfortunately this does not work.

In my investigations, however, I discovered the following: in order to use 'position' I have to use MenuPopover. When I examine the DOM structure, what I discover is that the menu button is generating two portals: the first portal is the 'default' portal generated by MenuButton, and which contains all of the menu items. The second is the portal generated by MenuPopover, which contains nothing.

The reason that the styles generated by the position callback aren't working is because the styles returned by the position function are being applied to the portal created by MenuPopover, which contains no visible elements. The default portal does not have these styles applied, and so the position hook has no effect.

It appears that MenuButton is somehow failing to detect the presence of the MenuPopover component, and is generating its own default portal regardless.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | @reach/menu-button  | 0.8.4 |
| React            |         |  16.12.0  |
| Browser          |         | Chrome |
| Assistive tech   |         | n/a        |
| Node             |         | v12.3.1        |
| npm/yarn         | npm        | 6.13.6        |
| Operating System | OSX        |         |

**Comment by chancestrickland** [comment]
Can't reproduce on my end. If you can create a code sandbox reproduction I'll reopen and investigate.

**Comment by viridia** [comment]
I figured out the problem - I was putting the MenuPopover outside of the MenuList. (I got confused by the distinction between MenuList and MenuItems, the docs don't really explain the difference between these components.)
