### ISSUE TITLE
MenuItem.onSelect is broken in Menu render function

### ISSUE THREAD

**Issue by mxfs** [reach/reach-ui#523]
### Current Behavior

Rendering fails when using render function in `Menu` component.

![image](https://user-images.githubusercontent.com/7244323/77143935-9b161680-6a52-11ea-9af6-19e7ce945d81.png)

### Expected behavior

The normal behavior of `onSelect` event handler on `MenuItem`

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/frosty-buck-sbbil)

### Additional context

v0.9.0 and v0.9.1 fails at render time.
v0.8.6 fails when <MenuButton /> is clicked.
v0.8.5 it seems to work well.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/menu-button     |     0.9.1    |
| React            |         |    16.12.0     |
| Browser          |     Chrome    |     80    |

**Comment by chancestrickland** [comment]
This appears to only happen when the render prop is used. Will look into it further over the weekend.

**Comment by SimonDegraeve** [comment]
You can fix it by wrapping your `onSelect` handler with a `useCallback` hook.

**Comment by chancestrickland** [comment]
Fixed in 0.10.0
