### ISSUE TITLE
[Listbox] onBlur event is fired on item select

### ISSUE THREAD

**Issue by maksimsemenov** [reach/reach-ui#525]
### Current Behavior
When I select an item in the Listbox, it fires the `onBlur` event, while technically the Listbox is still focused. 

### Expected behavior
`onBlur` event should be fired only when Listbox is blurred (when user's action moves focus to another element).

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/optimistic-fast-rvpf0)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | Listbox|0.9.1|
| React            ||  16.13.1       |

**Comment by chancestrickland** [comment]
> while technically the Listbox is still focused

The `onBlur` event is passed to the `ListboxInput` wrapper element, which captures blur events from nested children (in this case, `ListboxList` is losing focus). Even though the list is in a portal, its event still bubbles up, so this is expected. https://reactjs.org/docs/portals.html#event-bubbling-through-portals

You can drop down to the lower-level API to attach handlers and refs to specific nodes in the listbox, then check the event's relatedTarget to fire your own events when specific conditions are met.
