### ISSUE TITLE
[Slider] On Pointer device: after swiping on the SliderTrack, any pointer event on the screen will affect the Slider position

### ISSUE THREAD

**Issue by danielberndt** [reach/reach-ui#527]
### Current Behavior

- visit the doc page (https://reacttraining.com/reach-ui/slider/) on a mobile device (tested on Pixel 2 with Android Chrome).
- perform a swipe on the SliderTrack
- any subsequent clicks on any area of the page will affect the slider position (it seems like a cancel event isn't fired or something)

### Expected behavior

- I would expect that only pointer events initiated on the slider (or nearby) would affect the slider position (Especially since I only accidentally performed a swipe on the slider track while I was scrolling the page)

### Your environment

https://reacttraining.com/reach-ui/slider/

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Browser          | Chrome on Android        |  80 |

**Comment by chancestrickland** [comment]
Should be fixed in 0.10.0, let me know if you still have issues!

**Comment by danielberndt** [comment]
Nice! I just tested it and the slider works really well now. Thanks a lot :)
