### ISSUE TITLE
open button for combobox popover

### ISSUE THREAD

**Issue by akonsu** [reach/reach-ui#529]
Hello, as I understand the "open" button that the WAI-ARIA spec at https://www.w3.org/TR/wai-aria-practices-1.2/#combobox discusses is not implemented. Is it possible to open the popover programmatically now, so that I can implement the button myself?

**Comment by chancestrickland** [comment]
See https://github.com/reach/reach-ui/blob/master/packages/combobox/examples/with-button.example.js

We do not allow you to fully control state for the popover as it should only be toggled by a user action.
