### ISSUE TITLE
Why does combobox popover have more than one highlighted item?

### ISSUE THREAD

**Issue by akonsu** [reach/reach-ui#530]
Is this by design that the combobox popover has two highlighted items when I navigate to it by arrow keys while it has mouse pointer over it? It highlights two items: one that has mouse hover, and the other one that I moved to using arrow keys.
<img width="235" alt="Screen Shot 2020-03-28 at 17 38 56" src="https://user-images.githubusercontent.com/1016035/77834518-a1c02000-711b-11ea-8552-7f8f2be9ffbd.png">

**Comment by chancestrickland** [comment]
Yes, though your implementation should have distinct styles for hover vs. selected states. Hovering over an item does not change the value of `aria-activedescendant`. We keep styling basic out of the box, though there is a small distinction between the two (I should maybe make this more explicit)
