### ISSUE TITLE
How to conditional tooltip?

### ISSUE THREAD

**Issue by cloud-walker** [reach/reach-ui#531]
Hi, what about conditional tooltip use-case? At the moment I've found these 2 ways of doing it:

## Not rendering the tooltip at all

This solution its a bit tedious as you have to conditionally render the Tooltip wrapper..

```javascript
import React from "react";
import Tooltip from "@reach/tooltip";

export const Example = ({ condition }) => {
  const content = <div>something with a tooltip</div>;

  if (condition) {
    return <Tooltip label="I'm a tooltip">{content}</Tooltip>;
  }

  return content;
};
```

## Using `:empty` CSS pseudo selector

```css
[data-reach-tooltip]:empty {
  display: none;
}
```

```javascript
import React from "react";
import Tooltip from "@reach/tooltip";

export const Example = ({ condition }) => {
  return (
    <Tooltip label={condition ? "I'm a tooltip" : ""}>
      <div>something with a tooltip</div>
    </Tooltip>
  );
};
```

What is the correct way of doing it? Thanks in advance!

**Comment by chancestrickland** [comment]
I'd probably opt for the first approach. Even if you don't display the tooltip, all of the logic is still being handled in the background. Since some tooltip state is global you don't want invisible tooltips affecting state for any other tooltips on the screen.

**Comment by cloud-walker** [comment]
@chancestrickland why is the label prop required? 

It would be better to support an official disabled state of the Tooltip? Like a `disabled` prop or let the `label` prop to be falsy?
