### ISSUE TITLE
Reach/tabs closing when using menu & menu button

### ISSUE THREAD

**Issue by JohnnyMcFadden** [reach/reach-ui#539]
### Current Behavior

Currently trying to use a menu dropdown (menu with menu button) inside reach tabs panel. However, clicking on the reach menu button inside a tab seems to close everything.

![closing](https://user-images.githubusercontent.com/48435771/78657101-31a25e80-78c0-11ea-8c10-194dfb86d4cf.gif)

### Expected behavior

Expecting that the using one reach component inside another doesn't close the tabs panel

### Menu snippet

```js
   <Menu>
        {({ isOpen }) => (
          <>
            <MenuButton
              className={combineClassNames(
                getClass('__button'),
                getClass(`__button--${isOpen ? 'open' : 'closed'}`)
              )}
              onClick={e => {
                e.preventDefault();
              }}
            >
              {selected}
            </MenuButton>
            <MenuList className={combinedListClassName} ref={listRef}>
              {search}
              {items}
            </MenuList>
          </>
        )}
 </Menu>
```

I've tried to prevent default on the menu button click but it's closing the reach tabs and not firing the onClick handler when used inside the reach tabs. It fires correctly when used outside reach tabs.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   @reach/tabs | ^0.10.0 |
| Reach Package    |   @reach/menu-button | 0.8.2 |
| React            |         |    16.8.6     |
| Browser          |   chrome      |   80    |
| Assistive tech   |         |         |
| Node             |        | 10        |
| npm/yarn         |         |         |
| Operating System |  macOS       |   high sierra      |

**Comment by chancestrickland** [comment]
I'm not sure what you mean by "closing the reach tabs", but it looks like you are trying to build a mega menu of sorts with tabs. This is beyond the scope of tabs and, from an accessibility standpoint, **not well tested and thus not encouraged**. I'd take a look at some mega menu implementations and build a proper menu component instead.

https://dequeuniversity.com/library/aria/menus/megamenu
https://adobe-accessibility.github.io/Accessible-Mega-Menu/
https://www.levelaccess.com/challenges-mega-menus-standard-menus-make-accessible/
