### ISSUE TITLE
Implsible to use @reach/alert with React Context

### ISSUE THREAD

**Issue by necinc** [reach/reach-ui#540]
### Current Behavior

The accessible `div` with `role="alert|status"` doesn't have any content.

It's is not anywhere that you're not supposed to pass as children anything that relies on a react context. 
This makes it impossible to use your awesome accessible alert component with most of css-in-js libraries. 

### Expected behavior

To render alert without throwing the errors.

### Reproducible example

**Notice how alert gets fired for the second time with `undefined` as a value**
[CodeSandbox example](https://codesandbox.io/s/cold-mountain-s2cb6?file=/src/App.js)

### Suggested solution(s)

To  either specify that you can't use context consumers as children of `@reach/alert` component or to somehow prevent cloning passed children. 

### Additional context

The error occurs because of this `render` call
https://github.com/reach/reach-ui/blob/a376daec462ccb53d33f4471306dff35383a03a5/packages/alert/src/index.tsx#L145-L149

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     Alert    |      0.10.0   |
| React            |         |      16.12.0  |
| Browser          |         |    Any     |
| Assistive tech   |         |    none     |
| Node             |         |      any   |
| npm/yarn         |         |     any    |
| Operating System |         |  any    |

**Comment by chancestrickland** [comment]
Yes, this render call does break the alert as written. It does not say this in the docs (I should fix that), but this comment block appears at the top of the component code explaining the limitation.

> Developers can't read from context inside of an Alert because we aren't using ReactDOM.createPortal(), we're actually creating a couple of brand new React roots. We could use createPortal but then apps would need to render the entire app tree in an <AlertProvider>, or maybe there's a way with default context to do it, but we haven't explored that yet. So, we'll see how this goes. If it becomes a problem we can introduce a portal later.

I know this is a simplified reproduction, but can you not invert the context consumer and alert wrapper in your case?

```jsx
function App() {
  return (
    <TestContext.Provider value={{ user: "World" }}>
      <TestContext.Consumer>
        {value => {
          alert(JSON.stringify(value));
          return (
            <ReachAlert>
              <code>{JSON.stringify(value)}</code>
            </ReachAlert>
          );
        }}
      </TestContext.Consumer>
    </TestContext.Provider>
  );
}
```

**Comment by necinc** [comment]
Hey, thank you for your reply!

In the case of my previous example, I definitely **can** consume the context outside of the `Alert`. But in case you use some css-in-js library that relies on the context you have no chance of _not inverting_ it.

Simplified example:

```javascript
const Paragraph = styled.p(theme => css`
  font-size: ${theme.text.regular}px;
  color: ${theme.colors.darkGrey};
`)

function App() {
  return (
    <ThemeProvider value={myTheme}>
      <ReachAlert>
        <Paragraph>Something went wrong</Paragraph>
      </ReachAlert>
    </TestContext.Provider>
  );
}
```

**Comment by chancestrickland** [comment]
I think it's probably a good idea to address this. Not sure I'll have the time or bandwidth to do it proper justice at the moment, but PRs are welcome!

**Comment by necinc** [comment]
Then could you please tell if there were any limitations that did not allow us to use portals in the first place? 
In case somebody (maybe even myself) will stumble upon this issue and would like to open an MR with the fix so they have some context.

**Comment by chancestrickland** [comment]
> Developers can't read from context inside of an Alert because we aren't using ReactDOM.createPortal(), we're actually creating a couple of brand new React roots. We could use createPortal but then apps would need to render the entire app tree in an `<AlertProvider>`, or maybe there's a way with default context to do it, but we haven't explored that yet. So, we'll see how this goes. If it becomes a problem we can introduce a portal later.
