### ISSUE TITLE
Dialog triggered from button via click doesn't focus initialFocusRef

### ISSUE THREAD

**Issue by cabezonidas** [reach/reach-ui#541]
### Current Behavior

When opening a dialog from a button, it doesn't focus initialFocusRef if it was triggered with a click and that button didn't have focus previously.

This works fine with key downs (enter/space), and as far as I can tell to capture those keys, the triggering button has to have focus first.

This also works fine if triggering button has focus and then it's clicked. But in Chrome when it's clicked and didn't have focus, the initialFocusRef doesn't work. (Firefox works fine)

### Expected behavior

If I click a button that doesn't have focus and triggers a dialog, I expect initialFocusRef to be focused.

### Reproducible example

It can be reproduced here
https://reacttraining.com/reach-ui/dialog/#dialogoverlay-initialfocusref

Thanks!

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package | Dialog | 0.10.0
| React | 16.13.1
| Browser | Chrome | 80.0.3987.149
| Operating System | Darwin | macOS 10.15.4 |

**Comment by chancestrickland** [comment]
AFAICT the initialFocusRef is in fact focused as intended, but the focus outline doesn't show up for one reason or another. But if you keydown pretty much any key after the fact the focus marker returns, and if the initialFocusRef is a button it indeed gets pressed when you press `Enter` or `Spacebar`. We aren't doing anything with styling other than relying on the user agent, so my guess is that Chrome has some UA distinctions between `focus` and `focus-visible` here.

If you drop this in your inspector you should see the red outline when following your steps.

```css
*:focus {
  outline: 2px solid red;
}
```
