### ISSUE TITLE
Issues using @reach/menu-button MenuLink with Typescript + React Router + non-string “as” property

### ISSUE THREAD

**Issue by joearasin** [reach/reach-ui#542]
“to” is typed as a string; which means using either object or functional constructions don’t typecheck

**Comment by chancestrickland** [comment]
I have no idea what version on @reach/menu-button you're using (that's why the issue template is helpful to follow). The current version does not define the `as` prop as a string, and in fact we have TS examples in the repo where we pass custom styled components. Feel free to take a look and update if you can.

**Comment by joearasin** [comment]
Sorry about the template -- I filed the issue from my phone and it didn't populate.
I'm on 0.10.0.

The issue isn't the "as" prop -- it's the "to" prop on MenuLink:
https://github.com/reach/reach-ui/blob/a376daec462ccb53d33f4471306dff35383a03a5/packages/menu-button/src/index.tsx#L770

react-router's Link "to" prop takes any number of different types (string, function, object): https://reacttraining.com/react-router/web/api/Link  -- MenuLink handles this right in that it passes To through, whatever it is, but the typing causes TS to choke.

**Comment by joearasin** [comment]
So an example of what breaks is something like:
```ts
import {  Link } from "react-router-dom";
...
<MenuLink as={Link} to={location => `${location.pathname}?sort=name`}>Sort by name</MenuLink>
```

**Comment by chancestrickland** [comment]
Ooh got it, sorry I misread that. I'll reopen and investigate. Thanks for the additional context 👍

**Comment by indiesquidge** [comment]
@joearasin would it be possible to get a minimum reproducible demo of this issue by using the [CodeSandbox Template](https://codesandbox.io/s/reach-ui-template-xonfs) from the issue template? Thanks.

**Comment by bees** [comment]
I think I'm running into a similar issue, here's a minimal repro case: https://codesandbox.io/s/naughty-pond-igdli?file=/src/index.tsx

I've been playing around with getting type variable inference working (would hopefully keep the same DX for unaffected users) but I'm out of my depth - my approach breaks the memoized implementation (its no longer a valid JSX constructor): https://github.com/bees/reach-ui/commit/805d3fb72bfdc50b7a744f7576666c2f668c7b1e

apologies for the hard to read diff, prettier changed the indent level

**Comment by chancestrickland** [comment]
Removed in 0.10.1, let me know if you still have issues.
