### ISSUE TITLE
Ability to pass targetRef to ComboboxPopover just like a normal Popover

### ISSUE THREAD

**Issue by sanfilippopablo** [reach/reach-ui#543]
### Current Behavior

The `ComboboxPopover` passes a hardcoded ref (the input) to the `targetRef` prop of `Popover`.

### Desired Behavior

I have an use case where I want the Combobox autocomplete list to attach to a different element than the input (just a wrapper around it) and grab that element's position/width instead. It'd be great to just pass a ref of that element to the popover.

### Suggested Solution

In `ComboboxPopover`, if `targetRef` is coming as a prop, pass that to `Popover` instead of the inputRef.

### Who does this impact? Who is this for?

I guess this is an advanced case?

### Describe alternatives you've considered

None.

### Additional context

N/A

**Comment by indiesquidge** [comment]
@sanfilippopablo Recognizing that it could be valuable to allow for the targetRef to be passed to the ComboboxPopover as a prop, there is also an option to [render the listbox inline][1] by passing `portal={false}`, which would allow you to style the listbox to match your input wrapper's width.

[1]: https://reacttraining.com/reach-ui/combobox#comboboxpopover

**Comment by indiesquidge** [comment]
@chancestrickland, is this something we'd like to support? I'd be happy to implement it. I've seen a few other cases come up with folks wanting to attach the popover to a wrapper element around the input.

<img width="50%" src="https://user-images.githubusercontent.com/3409645/80767051-d436b180-8afb-11ea-93ee-82e4b9699a56.png" />

**Comment by chancestrickland** [comment]
Sorry for the delayed response here. You can position the popover however you'd like with the `position` prop in popover, but it does look like we don't let you override that for combobox. Would that not be sufficient to handle custom positioning logic? You could use any other DOM refs you'd like in that case, no need to accept a custom `target` ref.

**Comment by sanfilippopablo** [comment]
@chancestrickland although not ideal, I guess it could work if I get a ref to my outer element in my component and then pass a `position` prop defined in the component that ignores the `targetRef` and uses that outer ref?
