### ISSUE TITLE
[Listbox] Listbox always re-render when clicking somewhere on the screen

### ISSUE THREAD

**Issue by Pustelto** [reach/reach-ui#552]
### Current Behavior

Listbox has a `mousedown` event listener bind to window. This will cause all Listbox components on the screen to re-render every time user clicks somewhere, even if the Listbox itself is not affected (open Listbox is closed). This may cause performance issues in case there is many Listbox components on the screen. 

<img width="1280" alt="Screenshot 2020-04-15 at 08 40 28" src="https://user-images.githubusercontent.com/10606260/79306301-4486e580-7ef5-11ea-8b4c-0b8016d46ac2.png">

I have encountered this issue when using listbox in a table (1 Listbox per row). With growing number of Listbox there was noticable lag and after some number the page become virtually unusable. I will have to solve it with virtualization (due to large number of data, would have to do it even without the Listbox). But I do not think this is desired behavior.

### Expected behavior

When clicking outside of the Listbox component, unless the component is open it shouldn't re-render.

### Reproducible example

[CodeSandbox example](https://codesandbox.io/s/listbox-perf-zbuc9)

### Suggested solution(s)

`mousedown` event dispatch `send` action to state machine. But the state shouldn't change for closed Listboxes. 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/listbox     |  0.8.7 (tested with 0.10.0 as well)       |
| React            |   React      | 16.12.0        |
| Browser          |   Chrome      |  Version 80.0.3987.163 (Official Build) (64-bit)       |
| Assistive tech   |   -      |     -    |
| Node             |         |   12.16.1      |
| npm/yarn         |   npm      |   6.13.4      |
| Operating System |   macOS      |   10.15.4      |

**Comment by chancestrickland** [comment]
Addressed in 0.10.1

**Comment by Pustelto** [comment]
Thanks for quick fix @chancestrickland and for great library.
