### ISSUE TITLE
[Dialog] Issue with radio buttons because of outdated react-focus-lock

### ISSUE THREAD

**Issue by sebpettersson** [reach/reach-ui#554]
There was [a bug](https://github.com/theKashey/react-focus-on/issues/35) involving radio buttons in [theKashey/focus-lock](https://github.com/theKashey/focus-lock) which Dialog uses through [theKashey/react-focus-lock](https://github.com/theKashey/react-focus-lock). 

Updating [theKashey/react-focus-lock](https://github.com/theKashey/react-focus-lock) to the latest version should fix the issue.

**Comment by chancestrickland** [comment]
Updated in 0.10.1
