### ISSUE TITLE
[Portal] Nested portals

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#555]
## ❓Question

Hey 👋

I noticed that using `@reach/portal` for nested portals does not work very well. Two sibling portals are created, whereas I would expect them to be nested. When implementing an overlay which would close on document click, then clicks on any portaled children would then close the overlay.

An example of nested portals: https://codesandbox.io/s/autumn-snow-ybvym?file=/src/App.js

Thanks!

**Comment by raunofreiberg** [comment]
An example of what I'm trying to do: https://codesandbox.io/s/blue-water-mxccp?file=/src/App.js

Clicking on an item in the menu should not close the entire popover. If portals were nested, this would not happen.

**Comment by chaance** [comment]
Closing this for now to clean up old issues I haven't had time to get to, but at the moment I don't plan to add support for nested portals. Useful as it might be, there's a bit of complexity involved that I don't we're ready to tackle, so instead I'll add a note to the portal documentation noting as much!

For components that use portals by default, the best solution at the moment is to disable portals in nested elements (i.e. using a menu button inside a dialog, disable the portal on the menu button's `MenuList`).
