### ISSUE TITLE
TypeError in Portal when used with hot loader

### ISSUE THREAD

**Issue by viridia** [reach/reach-ui#557]
## 🐛 Bug report

When I attempt to do a hot reload (I'm using the latest parcel) I get the following exception every time:

```
TypeError: Cannot read property 'ownerDocument' of null

at http://localhost:4000/src.f69400ca.js:120708:43
in Portal (created by Popover)
in Popover (created by MenuPopover)
in MenuPopover (created by MenuList)
in MenuList (created by FilterTermEditor)
in DescendantProvider (created by Menu)
in Menu (created by FilterTermEditor)
in section (created by Context.Consumer)
in StyledComponent (created by FilterTermEditor__FilterTermSection)
in FilterTermEditor__FilterTermSection (created by FilterTermEditor)
in FilterTermEditor (created by FilterParams)
in form (created by Context.Consumer)
in StyledComponent (created by FilterParams__FilterTermList)
in FilterParams__FilterTermList (created by FilterParams)
in section (created by Context.Consumer)
in StyledComponent (created by Collapse__CollapseStyle)
in Collapse__CollapseStyle (created by Collapse)
in Transition (created by CSSTransition)
in CSSTransition (created by Collapse)
in Collapse (created by FilterParams)
in section (created by Context.Consumer)
in StyledComponent (created by FilterParams__FilterParamsSection)
in FilterParams__FilterParamsSection (created by FilterParams)
in FilterParams (created by IssueListView)
in IssueListView (created by Context.Consumer)
in Route (created by ViewContextProvider)
in Switch (created by ViewContextProvider)
in ViewContextProvider (created by Context.Consumer)
in Route (created by MainPage)
in Switch (created by MainPage)
in section (created by Context.Consumer)
in StyledComponent (created by MainPage__ContentPaneLayout)
in MainPage__ContentPaneLayout (created by MainPage)
in section (created by Context.Consumer)
in StyledComponent (created by MainPage__MainPageLayout)
in MainPage__MainPageLayout (created by MainPage)
in MainPage (created by Context.Consumer)
in Route (created by App)
in Switch (created by App)
in Router (created by BrowserRouter)
in BrowserRouter (created by App)
in ApolloProvider (created by App)
in ThemeProvider (created by App)
in App (created by HotExportedApp)
in AppContainer (created by HotExportedApp)
in HotExportedApp
```

### Current Behavior

Exception from Portal during hot reload.

### Expected behavior

Hot reload should work.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | popover | ^0.9.0 |
| React            |         | ^16.13.1 |
| Browser          | Chrome | 80.0.3987.149 |
| Assistive tech   |         | n/a        |
| Node             |         | n/a        |
| npm/yarn         | npm | 6.14.3 |
| Operating System | OSX | 10.15.3 |

**Comment by jylertones** [comment]
I see the same behavior, using webpack, Firefox 76, Linux and reach-ui 0.10.1.

Error comes from this line, where `current` is null:

https://github.com/reach/reach-ui/blob/master/packages/portal/src/index.tsx#L31

It's coming from usage of `<MenuList>` in my case. If I add `portal={false}` the error does not occur, but then my menu popovers are not placed correctly.

Is it enough to just change that line to use value `mountNode.current?.ownerDocument`? Maybe too naive of a fix. I can't tell much from the React internals, but my wild guess is that in the hot loading situation, something is clearly different from normal. But if I can help in any way to debug this, I'm happy to help. I can help debug if you need, or provide a clean repo

**Comment by attfarhan** [comment]
I also see the same issue using MacOS, webpack, Chrome 81, and `@reach/menu-button` v0.10.0. 

Like in the comment above, the error disappears if I pass `portal={false}` to `MenuPopover`, but the positioning is off if so. Also happy to provide more info or a minimal repro if needed.
