### ISSUE TITLE
[Tabs] orientation types error

### ISSUE THREAD

**Issue by ChiaJune** [reach/reach-ui#558]
### Current Behavior

set `orientation` attribute and Typescript occur error

### Expected behavior

orientation can be set normally

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/typescript-tabs-orientation-error-feoun?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    tabs     |    0.10.0     |
| React            |     -    |     16.13.1    |
| Browser          |    Chrome     |    81.0.4044.113     |
| Assistive tech   |    -     |    -    |
| Node             |    -     |     12.16.1    |
| npm/yarn         |    yarn     |    1.22.4     |
| Operating System |    macOS     |     10.15.4    |

**Comment by chancestrickland** [comment]
For TypeScript, you should import the `TabsOrientation` enum. I need to update the documentation to reflect this, but last I checked I don't think there's a good way to coerce the enum into a union type of its values (and I'd prefer to keep enums for these kinds of props throughout the library).

**Comment by ChiaJune** [comment]
Thanks for your assistance
