### ISSUE TITLE
Support for Framer Motion (or documentation stating only React Spring is supported)

### ISSUE THREAD

**Issue by rey-wright** [reach/reach-ui#562]
### Current Behavior

Current it seems as if the Reach Dialog only supports React Spring for animation.

### Desired Behavior

It would be great if this supported some other up and coming libraries like Framer Motion.

### Suggested Solution

n/a

### Who does this impact? Who is this for?

Anyone who is looking for an alternative animation library.

### Describe alternatives you've considered

Tons of other libraries like anime.js, react transition (which Ryan already mentioned he wouldn't like), and possibly more.

### Additional context

n/a. Great library by the way.

**Comment by lednhatkhanh** [comment]
@rey-wright Hello, can I ask that did you figured it out? Could you please share an example with framer-motion and the Modal, thank you.

**Comment by kylemh** [comment]
In case anybody else needs this:

https://github.com/framer/motion/issues/543#issuecomment-695759835
