### ISSUE TITLE
[Dialog] Modal animation

### ISSUE THREAD

**Issue by VladSez** [reach/reach-ui#568]
## ❓Question

How can i animate unmount of Dialog component? I know about react-spring in the docs, but i want to use more lightweight solution

I was trying to animate it like this:
https://codesandbox.io/s/csstransition-component-mi7p3?file=/index.js
but, no luck

https://dev.to/michalczaplinski/super-easy-react-mount-unmount-animations-with-hooks-4foj

**Comment by chancestrickland** [comment]
Animating components as they unmount without hacking around the rendering logic is tricky indeed, that's why we typically recommend tools like `react-spring` that handle that for you. I haven't done this myself but I'll leave the issue open in case anyone else wants to weigh in with alternate methods.

**Comment by raunofreiberg** [comment]
I have worked on this! [Here's an example with `react-spring`](https://codesandbox.io/s/xenodochial-tesla-e39nm?file=/src/App.js).

**Comment by VladSez** [comment]
@chancestrickland @raunofreiberg what do you think about this? https://codesandbox.io/s/usedelayunmount-custom-hook-lenni?file=/src/index.tsx

**Comment by amir2mi** [comment]
I tried `react-transition-group` unfortunately did not work for both `<DialogContent/>` and <Dialog/>, my idea was using CSS animations, generally a delay to show the fade-out animation.

**Comment by indiesquidge** [comment]
@amir2mi if you provide a CodeSandbox example of your attempt at animating the dialog we may be able to help figure out what the issue is. Please open it as a new issue since this one is already resolved, thanks!
