### ISSUE TITLE
Add three SliderTrackHighlight inside 

### ISSUE THREAD

**Issue by gdsrosa** [reach/reach-ui#575]
## ❓Question
 I wanna know if it is possible to put 3 highlight sliders inside the SliderTrack, and at the of day the slider should look like this:
![image](https://user-images.githubusercontent.com/13604523/81114845-24958100-8ef9-11ea-8bc2-8c0492a681a8.png)

**Comment by chancestrickland** [comment]
You should be able to nest anything you want inside of a slider track, you just might need to write some logic to get that to work the way you want. What kind of measurement does that slider represent exactly?

**Comment by gdsrosa** [comment]
Nice!
Alright, so the measurement represents a monetary value, so the width of these divs inside the slider track has to change when I move the slider handle from left to right or vice versa.

**Comment by chancestrickland** [comment]
So this is untested, but if you control the value I imagine you could do something along these lines:

```js
function MoneySlider({ value, onChange, min, max }) {
  // assumes the shorter bar is 50% of the larger bar, adjust the math accordingly
  let smallTrackPercent = ((value / 2 - min) * 100) / (max - min);
  return (
    <SliderInput>
      <SliderTrack>
        <div style={{ position: `absolute`, left: 0, height: `100%`, width: `${smallTrackPercent}%` }} />
        <SliderTrackHighlight />
        <SliderHandle />
      </SliderTrack>
    </SliderInput>
  )
}
```

Again, that may need some tweaking but start there and let me know if you run into any limitations.
