### ISSUE TITLE
[Combobox] Allow for `value` and `displayValue` for `handleSelect` 

### ISSUE THREAD

**Issue by mirshko** [reach/reach-ui#578]
## 🚀 Feature request
It would possibly be useful to also enable the ability to have a key / label or value / displayValue for the ComboboxOption. 

Allowing someone to have multiple pieces of data returned from their API, one being the searchable entry / the value to show the autocomplete for, and a secondary value to be used later in the handleSelect. 

For instance https://github.com/wellyshen/use-places-autocomplete returns multiple points of data, the most ideal searchable piece of data being the description passed to the frontend as seen in the demo.

However, for certain use-cases it might be useful to get the `place_id` from the Google Maps integration. Using the combobox package this is currently not possible afaik.

Be able to pass multiple points of data would be useful, however I'm guessing due to the use of an uncontrolled component (I'm guessing from the use of `.target.value`) that passing multiple points of data would be harder / or break desired performance of the component. 

Either way would love this possibility!

**Comment by mirshko** [comment]
Also there doesn't seem to be a quick way to clear the currently selected value from the combobox? 

Is there something I'm missing?

**Comment by mirshko** [comment]
Ahh seems work is being done in #514

Closing

**Comment by indiesquidge** [comment]
> Allowing someone to have multiple pieces of data returned from their API, one being the searchable entry / the value to show the autocomplete for, and a secondary value to be used later in the handleSelect.

@mirshko what about using a JS object for keys and values in your app?

```js
function App() {
  const optionData = React.useRef({});

  return (
    <Combobox
      onSelect={(value) => {
        // O(1) lookup for data
        const data = optionData.current[value];
      }}
    >
      <ComboboxInput />
      {results && (
        <ComboboxPopover>
          <ComboboxList>
            {results.slice(0, 10).map((result, index) => {
              const value = `${result.city}, ${result.state}`;

              optionData.current[value] = {
                // extra data here
              };

              return <ComboboxOption key={index} value={value} />;
            })}
          </ComboboxList>
        </ComboboxPopover>
      )}
    </Combobox>
  )
}
```

**Comment by indiesquidge** [comment]
> Also there doesn't seem to be a quick way to clear the currently selected value from the combobox?

Can you explain a bit more about what you're trying to do here that seems to be broken/missing?

**Comment by mirshko** [comment]
> Can you explain a bit more about what you're trying to do here that seems to be broken/missing?

Yeah this would be a flow of clearing the input once and Item is selected from the Combobox, for instance if its used to add multiple items and the value is passed to another spot on the UI, the next Combobox's input should be empty awaiting new input.

**Comment by kilinkis** [comment]
> ```js
> key={index} value={value}
> ```

this is now allowed, since `value` only takes strings
