### ISSUE TITLE
[docs] Update animation examples

### ISSUE THREAD

**Issue by LukasDeco** [reach/reach-ui#579]
## 📖 Documentation
I noticed that on the example for the Phased exit and enter animation it says `// TODO: Update with Phased example` and the example does not demonstrate how to use Phased. I have tried to implement this myself without success. An example of how to achieve this would be very helpful! Thanks!

**Comment by chancestrickland** [comment]
Yeah, TBH this is a very old part of the docs that we need to update, possibly with a different approach. I don't have an example at the moment but would like to get this entire page updated in the upcoming docs revamp.

**Comment by LukasDeco** [comment]
Okay well I look forward to seeing that! I guess for now we can live without the exit animation, but I will be really eager to see the example.

**Comment by chancestrickland** [comment]
Take a look at React Spring, I've personally found it less cumbersome to work with. We have an example of an exit animation with React Spring in the Dialog docs, but we should definitely expand on that.
