### ISSUE TITLE
Popover/MenuList appears from the right

### ISSUE THREAD

**Issue by elgerlambert** [reach/reach-ui#589]
### Current Behavior
When a popover/menulist is aligned with the right side of the button (either through collision detection or by specifying the `positionRight` function on `MenuPopover`), the popover "flashes" to the right side of where it should appear, making it appear as though the menulist is animated in from the right side.

If you click the menubutton rapidly the flash to the right only appears 1 in 3 or 4 times, which is a bit strange.

Tried capturing a gif to illustrate what was going on. It kind of does that, but in the gif the menu appears to animate away (when you close the menu..?). Rather than animate in when you open the menu, which is what I'm seeing in browser.

![MenuList flash](https://user-images.githubusercontent.com/1628796/82231162-0bdf8f00-992d-11ea-84fd-9a52ce3080b0.gif)

### Expected behavior
No flash/animation illusion.

### Your environment
@reach/menu-button 0.10.2
React: 16.8.6

**Comment by raunofreiberg** [comment]
Hey 👋

Can you make a reproduction example using the [CodeSandbox Template](https://codesandbox.io/s/reach-ui-template-xonfs)? Thanks

**Comment by elgerlambert** [comment]
FYI for anyone else who might stumble on this issue.
The issue remains for higher versions of React (tested 16.9.0, 16.10.2 and latest experimental release 0.0.0-experimental-33c3af284).

To be clear, the issue can only be observed when the popover has `positionRight` (as a result of collision detection or when specified).
