### ISSUE TITLE
[auto-id] useId generates ids that will not be an valid selector

### ISSUE THREAD

**Issue by Pajn** [reach/reach-ui#591]
### Current Behavior

Use id generates a numeric ID however purely numeric ids can not be selected with querySelector.

```
> document.querySelector('#1')
SyntaxError: Document.querySelector: '#1' is not a valid selector
```

This causes problems when passing the ID to components that do just that. Currently I'm working around that by prefixing the id.

```js
  let labelId = useId();
  labelId = labelId && `l${labelId}`;
```

### Expected behavior

useId should return ids that can be used with querySelector (starting with a letter)

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/elated-cherry-oq8sn?file=/src/index.js)

### Suggested solution(s)

Prefix the id with something, maybe id so that the id becomes `id1` etc.

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | auto-id | ^0.10.2 |
| React            |         | 16.13.1 |
| Browser          | Firefox | 76.0.1 |
| Assistive tech   | N/A |         |
| Node             | N/A |         |
| npm/yarn         | N/A |         |
| Operating System | N/A |         |

**Comment by raunofreiberg** [comment]
Maybe we could add an optional `prefix` argument to `useId` which would be concatenated to the id?

```ts
const id = useId(undefined, 'prefix'); // `prefix-0`
```

**Comment by Pajn** [comment]
That would work however is there a reason to complicate the API and have people Google if they (like me) come upon this problem?
Does anyone depend on the current format of the ids?

**Comment by raunofreiberg** [comment]
I imagine not, but it would be nice to have semantic ID-s for components.

So you could, for example, have `TextField-0`, `Select-0` etc.

**Comment by chancestrickland** [comment]
`useId` should always be prefixed, but I don't think adding an argument is necessary.

If you need the fallback available in your component, I'd suggest something like:

```js
let _id = useId(props.id)
let id = props.id || `prefix-${_id}`
```

Otherwise, you can do it in one line:
```js
let id = `prefix-${useId()}`
```

I will update the docs to make this more clear.
