### ISSUE TITLE
Testing Rect/useRect

### ISSUE THREAD

**Issue by josephdburdick** [reach/reach-ui#594]
Hello, Rect/useRect has been crucial for what I've set out to do but I've encountered issues with assertions with React Testing Library. Whenever useRect is used within a test with React Testing Library the object is returned with all zeros. 

From this [Github issue thread](https://github.com/jsdom/jsdom/issues/653) I surmise this is expected behavior and I also see in the Rect/useRect folder that there are no tests, so how does one test with this package, specifically to detect if an element is outside a particular boundary, such as the Window? Any help or pointing me in the right direction would be much appreciated, thank you.

**Comment by josephdburdick** [comment]
I want to follow up with this since a label was added. If the expectation to test this is to mock getBoundingClientRect like so 
```
    delete Element.prototype.getBoundingClientRect
    Element.prototype.getBoundingClientRect = jest.fn()
      .mockReturnValue({
        bottom: 619.5,
        height: 265,
        left: 455.578125,
        right: 783.578125,
        top: 354.5,
        width: 328,
        x: 455.578125,
        y: 354.5
      })
```
that might be helpful to know for the any useRect beginners.
Any testing guidance would be helpful. Thanks!

**Comment by raunofreiberg** [comment]
Hey!

Do you have any examples of what you're trying to test that contains `useRect`?

I recently had to write lots of custom positioning helpers for a Tooltip component and this is what I ended up doing:

```js
// This is the function I would test.
function getPosition(rect) {
  // Do some fancy math here!
  return {
    top: rect.top,
    left: rect.left,
  };
}

function Component() {
  const ref = useRef();
  const rect = useRect(ref);
  return (
    <div ref={ref}>
      <div style={{ ...getPosition(rect) }} />
    </div>
  )
}

// Component.test.js
test('should position', () => {
  const mockedRect = { width: 50, height: 80, top: 20, left: 40 };
  const position = getPosition(mockedRect);
  expect(position).toEqual(expectedPosition);
})
```

I understand that it can be a bit cumbersome to mock all the rects out by hand, but I think this way you can be more explicit about the cases that you want to test and hopefully understand your code better as a result!

Hope this helps!

**Comment by josephdburdick** [comment]
Hello @raunofreiberg thanks for your reply! 
We ended up creating a mock client rect instead of relying on useRect.

```
  const { getBoundingClientRect } = Element.prototype
  beforeAll(() => {
    delete Element.prototype.getBoundingClientRect
    Element.prototype.getBoundingClientRect = jest.fn()
  })
  afterAll(() => {
    Element.prototype.getBoundingClientRect = getBoundingClientRect
  })
  afterEach(() => {
    Element.prototype.getBoundingClientRect.mockClear()
  })
```
We would then use `mockImplementation` like so:
```
   Element.prototype.getBoundingClientRect.mockImplementation(
      mockRectValue({
        height: 265,
        width: 330,
      }, {
        top: 280,
        bottom: 320,
        left: 330,
        right: 470,
      })
    )
```
And ultimately test what our expectations are. I think we can close this ticket because the answer to my original question is to mock implementations.

**Comment by bijaygithubfair** [comment]
Hi guys, I am writing test cases for layout and element position testing but every time when I use method getBoundingClientRect() on any element, it gives all the coordinates value as 0 like   { bottom: 0, height: 0, left: 0, right: 0, top: 0, width: 0 }

Have anyone faced this and what will be the solution?

I am writing react js test cases using jest and testing libraries.
