### ISSUE TITLE
Is there a suitable component for constructing an accessible navbar?

### ISSUE THREAD

**Issue by orshick** [reach/reach-ui#595]
## ❓Question

I was interested in making an accessible `navbar`, which had some items as regular Link components, and others as dropdowns with subnav links. However I am not sure if the MenuButton component is really meant for this option since I didn't see any actual `navbar` examples, and when I tried to render a Menu component with either a MenuButton (for items with subnavs) and regular Link components for singular items, the singular items got skipped when tabbing through the links.

**Comment by chancestrickland** [comment]
The menu button pattern is good for isolated buttons but you'll need to do a fair bit more to build a navbar. This is out-of-scope for Reach UI at the moment.

**Comment by orshick** [comment]
Dang. Well, thanks for clearing that up!
