### ISSUE TITLE
Examples are broken in docs

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#598]
### Current Behavior

![image](https://user-images.githubusercontent.com/23662329/82539316-ee413e00-9b55-11ea-8d05-b7490f508b86.png)

### Expected behavior

Examples should not be broken.

### Reproducible example

https://reacttraining.com/reach-ui/listbox (and many other packages affected)

### Suggested solution(s)

Track the regression and fix it!

### Additional context

I will take a look at this and hopefully come up with a fix.

**Comment by raunofreiberg** [comment]
My gut feeling was that I broke something in #588, but I've traversed the commits back to 196cc567abea796b0aeff2f5c562c63092f0d92b and the examples are still broken:

![image](https://user-images.githubusercontent.com/23662329/82542309-6f023900-9b5a-11ea-90dd-9449be49f084.png)

**Comment by chancestrickland** [comment]
Still broken on prod after the fix. I'll investigate further later today.

**Comment by raunofreiberg** [comment]
> Still broken on prod after the fix. I'll investigate further later today.

That's really odd because if I spin up a production build of the website locally, everything is fine!

**Comment by raunofreiberg** [comment]
@chancestrickland do you think there might be a problem with caching?

e.g. I see in `travis.yml` that we cache yarn dependencies:

https://github.com/reach/reach-ui/blob/1b2535fb5843c563e48eeeef5eb5f3e160c0311f/.travis.yml#L3

**Comment by chancestrickland** [comment]
It's fixed now. I had changed a sub-dependency in a few packages (`descendants`) that needed to be released. Thanks again!
