### ISSUE TITLE
Auto focusing elements  in Popover doesn't work

### ISSUE THREAD

**Issue by tobiasandersen** [reach/reach-ui#603]
**First, thanks for making reach-ui. I really love this project!** 

### Current Behavior
It's not possible to give focus to an element inside a popover on mount. 

### Expected behavior
If I have an input field with `autoFocus={true}` inside a Popover, I'd expect it to be focused when the Popover mounts. 

### Reproducible example
If you click the "Open" button in this 
[CodeSandbox](https://codesandbox.io/s/gracious-water-82imk?file=/src/index.js), you can see that the input field doesn't receive focus.

### Suggested solution(s)

While the popover is measuring (to calculate its position), it adds this styling:

```js
{ visibility: "hidden" };
```

The problem is that an element with this can't receive focus. Could we use e.g. `opacity: 0` instead or would that introduce other problems? I'd be happy to make a PR :)

**Comment by raunofreiberg** [comment]
Possibly related to #561
