### ISSUE TITLE
Support for react hook form in Listbox component

### ISSUE THREAD

**Issue by Idered** [reach/reach-ui#604]
### Current Behavior

Listbox doesn't work with [react hook form](https://react-hook-form.com/) 

```
const {register} = useForm()

return (
  <Listbox ref={register} name="title">
     ....
  </Listbox>
)
```

ref is passed to listbox wrapper, not input. This prevents RHF from doing it's job.

### Desired Behavior

React `ref` is passed to `input`, not it's wrapper. [See here](https://github.com/reach/reach-ui/blob/master/packages/listbox/src/index.tsx#L325)

### Suggested Solution

I see 2 options:
- `ref` should be passed to input, not container
- add `inputRef` property

### Who does this impact? Who is this for?

People using react hook form

### Describe alternatives you've considered

There are many alternatives but having support for one of the most popular react form managers would be a nice touch to this already awesome component.

### Additional context

https://react-hook-form.com/

**Comment by raunofreiberg** [comment]
I think you should drop down to `ListboxInput` and compose `Listbox` with its parts like so:

```
<ListboxInput aria-labelledby="my-label" defaultValue="comedy">
	<ListboxButton />
	<ListboxPopover>
		<ListboxList>
			<ListboxOption value="drama">Drama</ListboxOption>
			<ListboxOption value="comedy">Comedy</ListboxOption>
			<ListboxOption value="suspense">Suspense</ListboxOption>
			<ListboxOption value="horror">Horror</ListboxOption>
		</ListboxList>
	</ListboxPopover>
</ListboxInput>
```

I'm unsure if `register` would work on `ListboxInput` though since it is a custom component and does not actually render a native `input`

**Comment by Idered** [comment]
It won't work, `register` needs to be passed to native `input`.

**Comment by raunofreiberg** [comment]
You have to register Listbox manually then. There is no native `input` underneath Listbox since it is a custom implementation of a native `<select>` element.

The docs of `react-hook-form` have a section on registering custom components:

> You can also register inputs manually, which is useful when working with custom components and Ref is not accessible. This is actually the case when you are working with React Native or custom component like react-select.

> By using a custom register call, you will need to update the input value with setValue, because input is no longer registered with its ref.
