### ISSUE TITLE
Packages using scope with internal dependencies

### ISSUE THREAD

**Issue by aappoalander** [reach/reach-ui#605]
### Current Behavior

It seems that semantic versioning is not currently used with this library. The packages refer internally to e.g. Utils with a scope. There were breaking changes for some internal dependencies (e.g. https://github.com/reach/reach-ui/releases/tag/v0.10.3) which allowed updating the dependencies with for example fresh installs. This becomes an issue when using a locked version of some package (e.g Popover).

In practice using exact 0.10.0 version of e.g. Popover (not sure if it was Popover, Portal or Menu-button which caused the issue in our case) breaks things since it uses 0.10.3 version of utils which introduced breaking changes.

### Expected behavior

Any of the packages should work out of the box when using a locked version.

### Reproducible example

Should be reproducible by creating an empty project using create react app and adding Menu-button, Popover and Portal packages with locked 0.10.0 version and related examples from the site.

### Suggested solution(s)

Use locked versions for internal dependencies or start using semantic versioning.

### Your environment

Found using a custom build, but reproduced with latest version of create react app.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     Popover, Menu-button, Portal    | 0.10.0        |
| React            |   React, React-dom      |    latest     |
| Browser          |    Chrome     |    latest     |
| Assistive tech   |    Create react app     |    latest     |
| Node             |         |         |
| npm/yarn         |    yarn     |  1.22.4  |
| Operating System |    OS X     |    latest     |

**Comment by chancestrickland** [comment]
> Use locked versions for internal dependencies

This is a good call, we'll make this change in the next release. We'll follow semver after the 1.0 release. Very sorry for the churn in the mean time!

**Comment by aappoalander** [comment]
> > Use locked versions for internal dependencies
> 
> This is a good call, we'll make this change in the next release. We'll follow semver after the 1.0 release. Very sorry for the churn in the mean time!

Great and no worries! :) This is a great library so keep up the good work!

**Comment by chaance** [comment]
We're pinning to exact versions now so I'll go ahead and close this. Let me know if you have any other concerns!
