### ISSUE TITLE
Add Multiple Selection to Listbox

### ISSUE THREAD

**Issue by flybayer** [reach/reach-ui#606]
### Current Behavior

Listbox only supports a single selected value.

### Desired Behavior

I need Listbox to support multiple selected items.

I'm building a complex filter component that works exactly like Listbox does but with multiple options. My selected values object is something like:

```
{
  days: ['day1', 'day3'],
  types: ['fruit'],
}
```

### Who does this impact? Who is this for?

Anyone doing multi selection :)

### Describe alternatives you've considered

An alternative is to add a new component like `MultiListbox` or something.

**Comment by chancestrickland** [comment]
This is likely out of scope at the moment. but we are considering this as a feature for a premium release at some point. Sorry!
