### ISSUE TITLE
Error suddenly cropped up "TypeError: targetRect is null" (found in official example too)

### ISSUE THREAD

**Issue by davidprae** [reach/reach-ui#608]
### Current Behavior
Code that was previously working no longer works. There were no changes related to this section of my app (afaik).

The new error, in my app:
<img width="711" alt="Screen Shot 2020-06-03 at 10 41 08 AM" src="https://user-images.githubusercontent.com/12590512/83664077-bf2fc100-a586-11ea-8cfb-9906eda6f288.png">

The error on an official example:
https://codesandbox.io/s/kj83k?file=/src/index.js

Taking ComboboxPopover out "fixes" the problem:
<img width="598" alt="Screen Shot 2020-06-03 at 10 40 12 AM" src="https://user-images.githubusercontent.com/12590512/83663977-9d363e80-a586-11ea-8cad-1ad93955d667.png">

### Expected behavior

I expect there not to be the above error and for the CombopoxPopover to work as intended.

### Reproducible example

https://codesandbox.io/s/kj83k?file=/src/index.js

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/combobox     |    0.6.2     |
| React            |         |    16.9.0     |
| Browser          |         |    FF 76     |
| Node             |         |   11.8.0      |
| npm         |         |  6.5.0       |
| Operating System |         |   MacOS 10.15.1      |

**Comment by davidprae** [comment]
Compared an old package-lock.json (on left) with my current one (on right).
Installing with the old one does not produce this issue while installing with the new one does.

<img width="1259" alt="Screen Shot 2020-06-03 at 10 59 52 AM" src="https://user-images.githubusercontent.com/12590512/83665914-5ac23100-a589-11ea-8647-a78c682f5ce3.png">

**Comment by chancestrickland** [comment]
This is a very old version of Combobox, but the issue doesn't exist in the most up-to-date version. The `observe-rect` dependency should have been pinned to the exact version of `observe-rect`, (that will be fixed in the next release). If you can't upgrade to a newer version your best bet is to revert the change in your lockfile.
