### ISSUE TITLE
Trick to debugging CSS of open menu?

### ISSUE THREAD

**Issue by hedgerh** [reach/reach-ui#61]
What's the best way to inspecting the CSS styles of the open menu/menu items in Chrome?  Every time I click on the inspector, the menu closes.  I ended up pulling down reach, changing the isOpen state, removing the click listeners, rebuilding, and linking locally.

Am I missing something here?  Is there an easier way to do this?  Thanks.

**Comment by jakierice** [comment]
First click the button to open the menu, and then right click -> inspect element on the MenuButton while the menu is open.

**Comment by hedgerh** [comment]
Ah, thank you!  That didn't occur to me.  I was having a rough time trying to inspect the MenuList/MenuItem.

**Comment by jakierice** [comment]
Glad I could help!

**Comment by nathanforce** [comment]
You can also use F8 to halt execution and the page will be frozen in the current state.

Another option is to add an HTML breakpoint on subtree modifications

![image](https://user-images.githubusercontent.com/6694194/46501899-cc663c80-c7f4-11e8-9f86-78b6a5a395a1.png)

**Comment by hedgerh** [comment]
This seems to be a common enough problem that it should probably be formally documented, unless there is some way to fix this.  I imagine that there may not be..

**Comment by ryanflorence** [comment]
Would be interesting to have a "how to debug web applications", but none of this is really unique to React or Reach UI :)

**Comment by qoalu** [comment]
> First click the button to open the menu, and then right click -> inspect element on the MenuButton while the menu is open.

Chrome crashes for me when doing this inside storybook:
![image](https://user-images.githubusercontent.com/1624045/58955632-c61dcb00-879c-11e9-86c0-a6b8a9d212a3.png)

**Comment by felixfbecker** [comment]
This technique doesn't for in Safari for me – as soon as the dev tools are focused, the popover closes.

**Comment by felixfbecker** [comment]
Actually, closes in Chrome too...
