### ISSUE TITLE
[TabList] typing of "as" prop seems to be off

### ISSUE THREAD

**Issue by trumbitta** [reach/reach-ui#612]
### Current Behavior

`TabList`'s `as` prop works but the type checker complains stating that `as` can only be equal to `div` when present.

### Expected behavior

Type checker doesn't complain.

### Reproducible example

https://codesandbox.io/s/loving-wave-3nwpy?file=/src/App.tsx:332-358

Same behavior in my local project.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | tabs | 0.10.3 |
| React            |         | 16.13.1 |
| Browser          | Chrome | 83.0.4103.97 (Official Build) (64-bit) |
| Assistive tech   |         |         |
| Node             |         | v12.16.1 |
| npm/yarn         | npm | 6.14.5 |
| Operating System | MacOS | 10.15.4 (19E287) |

**Comment by chancestrickland** [comment]
This regressed because I used `React.memo` which broke the `as` prop's type checks. Fixed in https://github.com/reach/reach-ui/commit/115eb680bae13e7e097c9a6cd3047c06530ee880 and I'll cut a release this week!

**Comment by chancestrickland** [comment]
Should be fixed in 0.10.4. Please let me know if you continue to have issues.
