### ISSUE TITLE
Testing MenuButton is non-trivial

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#617]
## 📖 Documentation
Sooo... I got to test my component built on top of `@reach/menu-button` and I wrote this nifty test case to test the opening and closing of the menu. 

Everything was straightforward (I even knew to use a mouse down event instead of click to open the menu!) until I wanted to assert that the menu closed after _selecting an item_. I had to dig into the source of menu button to figure this out. More specifically, neither mouse down nor click events would select an item. 

I had to trigger a mouseup event, which as I understand is so that the action does not trigger _instantly_, but leaves some time to either move over a different option or cancel entirely. Unfortunately, this distinction was not that intuitive to make while testing.

Here's the test case below:

```tsx
test("should open and close on selection", () => {
  const onSelect = jest.fn();
  const { getByText, getByTestId, debug } = render(
    <Menu>
      <Menu.Button>MenuButton</MenuButton>
      <Menu.List data-testid={MENU_TEST_ID}>
        <Menu.Item onSelect={onSelect}>First</Menu.Item>
        <Menu.Item onSelect={onSelect}>Second</Menu.Item>
        <Menu.Item onSelect={onSelect}>Third</Menu.Item>
      </Menu.List>
    </Menu>
  );

  const menu = getByTestId(MENU_TEST_ID);
  expect(menu).not.toBeVisible();

  const button = getByText("MenuButton");
  fireEvent.mouseDown(button);
  expect(menu).toBeVisible();

  const item = getByText("First");
  // Naturally, you would expect `mouseDown` or `click` to work here, but nope!
  fireEvent.mouseUp(item);
  expect(onSelect).toHaveBeenCalled();
  expect(menu).not.toBeVisible();
})
```

I tagged this issue as a documentation issue for now, which I think is the _least_ we could do here (adding some direction in docs would be great!), but maybe there are some other actions we could take here.

@chancestrickland wdyt? Is it just me or could this be improved somehow? 🙃

**Comment by chancestrickland** [comment]
I use a little helper for simulating a "click" by firing both mousedown and mouseup that I can use on either the button or a menu item. Agreed this could be documented better but TBQH I'm not sure if this is the best way to handle it either. Wouldn't consider myself an authority on testing or JSDOM but of course I'd want a "click" to trigger all of the same events that would fire in a real browser.

**Comment by arthureggert** [comment]
So, I did the same, fire the 3 events as described by @chancestrickland, but it was not working for me, it was not firing the onSelect, after a small research I found that it was being "blocked" by: 
https://github.com/reach/reach-ui/blob/a0c7b3672835b2a9f84732663bb0e78992541211/packages/menu-button/src/index.tsx#L444-L448

To fix this is my test, I needed to do:
` fireEvent.mouseMove(item);
   fireEvent.mouseUp(item);
`

**Comment by ghostd** [comment]
Hi @chancestrickland 

Is not the purpose of the click function (from the [user-event](https://github.com/testing-library/user-event) lib)?
https://github.com/testing-library/user-event/blob/6acbdb4dc3de3088be038aee654774cb5eda866f/src/click.js#L55-L79

**Comment by chancestrickland** [comment]
@ghostd looks like it, I'm not super familiar with all of the helpers in that lib but I'll try this out. Thanks!

**Comment by raunofreiberg** [comment]
As of https://github.com/reach/reach-ui/commit/dae686dfd3943f70087195115b97ca50e81e97f9, if you wish to make a selection on the menu button items, you'd have to fire a mouse move event as well. 

This is what I use now:

```ts
function click(element: Element) {
  fireEvent.mouseMove(element);
  fireEvent.mouseDown(element);
  fireEvent.mouseUp(element);
  fireEvent.click(element);
}
```
