### ISSUE TITLE
Maximum update depth exceeded.

### ISSUE THREAD

**Issue by antongiacomo** [reach/reach-ui#623]
### Current Behavior

React gives this error `Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

### Expected behavior

I had a working code base with a simple example. It have a search input and an autocomplete box. The search input is in a scroll view and the portal div is positioned dynamically underneath.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/quirky-haibt-rvur4)

### Additional context

The error disappears by removing the searchRef. But I can't position correctly the div in the portal.

### Your environment

Check codesandbox.

**Comment by chancestrickland** [comment]
I believe this should be fixed in 0.10.5. If you update the dependencies in the linked Sandbox the error is fixed. Let me know if you have any other issues.
