### ISSUE TITLE
How to use `listbox` component  to get a no popup list

### ISSUE THREAD

**Issue by thoamsy** [reach/reach-ui#630]
## ❓Question

I have a scene, want to use the listbox in two view: one for popup, one for just list.
But I don't find a way to implement the list like [this](https://www.w3.org/TR/wai-aria-practices-1.2/examples/listbox/listbox-scrollable.html)

This is my code:
```jsx
<ListboxInput>
  <ListboxList>
     ... some option
  </ListBoxList>
</ListboxInput>
```

It can render the list, but  lost the ability to select item

**Comment by chancestrickland** [comment]
Yeah, currently this isn't possible. I'd like to explore this in the future as a new feature or possibly even a standalone component, but right now listbox is intended to exist inside of a popover like a custom select.
