### ISSUE TITLE
reach/tabs can't be used with react-router

### ISSUE THREAD

**Issue by fabien0102** [reach/reach-ui#632]
### Current Behavior

To be able to have all the browser native features (open in new tab, copy link…) I want to use `reach/tabs` with `Link` from `react-router`. So far I'm failing, and I don't really know why 😕

### Expected behavior

I want to have a tab system connected to the router.

### Reproducible example

https://codesandbox.io/s/small-cdn-dr1lh?file=/src/App.tsx

Click on one link/tab =>
![image](https://user-images.githubusercontent.com/1761469/86101939-3770a000-babb-11ea-9262-b19cc1a41ebf.png)

### Additional context

I'm using `react-router:4.3.1`, all the details are in the repro example 😉 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    tabs     |  0.10.5       |
| React            |         |   16.12.0      |
| Browser          |    chrome     |    latest     |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by ghostd** [comment]
Hi,

Here what i found after some investigation:
* we call `ownRef.current.focus()` without checking if the target is a host element with a `focus` method (aka `HTMLElement`)
* we pass the reference into the `ref` property but the react-router `Link` component uses `innerRef`

How can we improve this part?
* check if the target element has a `focus` method?
* add a property to change the property receiving the reference? (`<Tab as={Link} asRef="innerRef" to="/three">`)
  * this option will allow the developers to use components using innerRef or other "not ref" properties to forward a reference
* other idea?

In the mean time, (not tested) i guess you can wrap the `Link` into a `CustomLink` to forward the `ref` prop to the react-router `innerRef` property.

**Comment by fabien0102** [comment]
@ghostd Thanks for your investigation! I tried quickly on the sandbox to wrap the `Link`

```tsx
const CustomLink = React.forwardRef((props, ref) => <Link {...props} innerRef={ref} />)
```

Typescript is not really happy, but the trick works 😁

**Comment by trumbitta** [comment]
And if you are using styled components to customize tabs appearance, don't forget to use `forwardedAs` instead of `as` 😉

**Comment by chaance** [comment]
Forgot to close this but I fixed the underlying bug a few versions back!

**Comment by fabien0102** [comment]
@chaance I did play a bit with the repro codesanding, and indeed this is working! Just noticed than when you are playing with the keyboard navigation (left / right to change tab) the url and the focus state are not following.

![9766d810-6ee3-46be-9763-a8d1c2939794](https://user-images.githubusercontent.com/1761469/113105252-aec99080-9201-11eb-9316-cc1e966494a3.gif)
