### ISSUE TITLE
MenuPopover Location

### ISSUE THREAD

**Issue by imrandyk** [reach/reach-ui#635]
## ❓Question

Is there a way to know if the MenuPopover is opening above/below or to a side of the MenuButton?

**Comment by chancestrickland** [comment]
You can look at the default logic of the popover's placement here: https://github.com/reach/reach-ui/blob/develop/packages/popover/src/index.tsx#L122

This is entirely up to you, though. You can override this logic by passing a `position` prop to `MenuPopover`.
