### ISSUE TITLE
Is there an ability to manually open and focus Listbox?

### ISSUE THREAD

**Issue by uulaal** [reach/reach-ui#643]
I can't find info about it in docs

**Comment by chancestrickland** [comment]
No, this is not currently possible and we have no plans to support that at this time. What is your use case?

**Comment by BrendanBerkley** [comment]
Glad I found this; it stopped me from trying.

A listbox replaces `<select>` for most of our use cases. Normally you can pair a `<label>` with a select; clicking the label will focus the select.

Listbox doesn't have anything that's directly analogous to this. If I want to add a visible label above a listbox and a user clicks that label, I want it to focus or activate the listbox.

Right now I can achieve what I want by adding a second ListboxButton, but that's an extra focus stop that doesn't need to exist, and it feels hacky.
