### ISSUE TITLE
[accordion] TypeScript error: Property 'translate' missing on Accordion

### ISSUE THREAD

**Issue by hereismass** [reach/reach-ui#668]
## 🐛 Bug report

Hello,

I'm am using the Accordion in a Controlled manner in a .tsx file.
I have a TS error regarding a missing 'translate' property:
```
Property 'translate' is missing in type '{ children: ReactNode; index: number; onChange: (index: number) => void; }' but required in type 'Pick<AccordionProps, "onChange" | "children" | "cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "accept" | "acceptCharset" | ... 349 more ... | "collapsible">'.
```

I'm not sure if I'm doing something wrong if this is a typescript related bug...
Here is the code of my component:

```
import React from 'react';
import { Accordion } from '@reach/accordion';

interface AccordionContainerProps {
  onChange?: (value: number) => void;
  sectionToShow?: number;
}

const AccordionContainer: React.FC<AccordionContainerProps> = ({
  onChange,
  children,
  sectionToShow,
}) => {
  const [openedSection, setOpenedSection] = React.useState<number>(sectionToShow || -1);
  const toggleSection = (index: number) => {
    let newIndex = -1;
    if (openedSection !== index) {
      newIndex = index;
    }
    if (onChange) {
      onChange(newIndex);
    }
    setOpenedSection(newIndex);
  };

  return (
    <Accordion index={openedSection} onChange={toggleSection}>
      {children}
    </Accordion>
  );
};

export default AccordionContainer;
```

### Current Behavior
![image](https://user-images.githubusercontent.com/2034044/93064544-eadb4080-f677-11ea-9c90-857ef61eba6b.png)
### Expected behavior

There should not be a TypeScript error

### Reproducible example

Couldn't reproduce in codesandbox

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   @reach/accordion      |    0.11.2     |
| React            |         |    16.13.1     |
| Typescript          |         |    4.0.2     |
| Node             |         |     10.22.0    |
| npm/yarn         |   npm      |    6.14.6     |
| Operating System |     MacOSX    |   10.15.6      |

**Comment by chaance** [comment]
Hi! Sorry I never got around to this but I'm unable to reproduce this either locally or in a sandbox. Let me know if you are still having issues here. It sounds like something in your project might be overriding our types for whatever reason, but there is no `translate` prop anywhere in our declarations so I'm not sure what it could be!
