### ISSUE TITLE
[dialog] Memory leak warning when using the animated example

### ISSUE THREAD

**Issue by andrewnystrom** [reach/reach-ui#669]
### Current Behavior

When using the provided animated Dialog component example, the following warning is given in the console: 
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ForwardRef (at App.js:26)
    in div (created by ForwardRef(DialogInner))
    in div (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef(DialogInner))
    in div (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef(DialogInner))
    in ForwardRef(DialogInner) (created by DialogOverlay)
    in Portal (created by DialogOverlay)
    in DialogOverlay (created by ForwardRef)
    in ForwardRef (at App.js:22)
```

### Expected behavior

This warning should not appear. 

### Reproducible example
The following sandbox is using the code from the example provided in the documentation. 

https://codesandbox.io/s/nifty-banzai-1d111

### Additional context

If you carefully watch the animation, it appears to finish and then the dialog moves down a pixel or two. I'm not sure if that has anything to do with this warning. The animation also seems to choke sometimes -- also not sure if that has anything to do with this. 
### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |      @reach/dialog   |      0.11.2   |
| React            |   react      |       16.13.1  |
| Browser          |   Safari/Firefox (but presuming all browsers)      | FF: 80.1, Safari: 13.1.1      |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chaance** [comment]
Fixed in #786
