### ISSUE TITLE
Layered components

### ISSUE THREAD

**Issue by jamiebuilds** [reach/reach-ui#67]
Certain components like menus or dialogs have elements which need to be positioned via "portals" in order to be positioned properly.

Here's an example of what a screen is _supposed_ to look like:

<img width="884" alt="screen shot 2018-09-17 at 2 55 17 pm" src="https://user-images.githubusercontent.com/952783/45652528-c00a8180-ba89-11e8-820c-c2c697f8bb18.png">

But it's easy to get stuff wrong with these, you can run into bugs like:

**Layer inside layer getting clipped:**

<img width="882" alt="screen shot 2018-09-17 at 2 56 22 pm" src="https://user-images.githubusercontent.com/952783/45652570-dfa1aa00-ba89-11e8-8f73-5956cd3b1ebe.png">

**Layers "jumping" on top of layers that they shouldn't:**

<img width="882" alt="screen shot 2018-09-17 at 2 55 28 pm" src="https://user-images.githubusercontent.com/952783/45652532-c26cdb80-ba89-11e8-8f50-eb89bd10ffc5.png">

**Layers getting captured inside of other positioned elements:**

<img width="768" alt="screen shot 2018-09-17 at 3 02 08 pm" src="https://user-images.githubusercontent.com/952783/45652898-fa285300-ba8a-11e8-92c7-02a1f7c4ea4c.png">

**Layers replacing each other when rendered:**

<img width="766" alt="screen shot 2018-09-17 at 3 06 08 pm" src="https://user-images.githubusercontent.com/952783/45653011-45426600-ba8b-11e8-8b46-072f16b49a92.png">

I've long thought that React needed a good generic component that *just* handled this.

> There's also issues of accessibility. But according to [ARIA's authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/), the components that would use layers have very different kinds of keyboard interactions. For this reason, a11y should be implemented at the actual "widget" level.

I thought a generic component that solves this would be a useful addition to Reach.

### Abstract API

```js
function Menu() {
  return (
    <Layer offset={1}>
      ...
    </Layer>
  )
}

function Dialog() {
  return (
    <Layer offset={2}>
      ...
    </Layer>
  )
}

function App() {
  return (
    <main>
      <Menu/>
      <Dialog>
        <Menu/>
      </Dialog>
    </main>
  );
}
```

Which would get vaguely rendered like this (had to use web components syntax so GitHub wouldn't render syntax errors)

```html
<main>
  ...
</main>
<x-portal>
  <div style="z-index: 1"><x-menu/></div>
  <div style="z-index: 2"><x-dialog/></div>
  <div style="z-index: 3"><x-menu/></div>
</x-portal>
```

What is essentially happening here is:

```js
const { Provider, Consumer } = React.createContext(0);

function Layer(props) {
  return (
    <Consumer>
      {value => (
        <Provider value={value + props.offset}>
          {props.children(value + props.offset)}
        </Provider>
      )}
    </Consumer>
  );
}
```

And a `ReactDOM.createPortal()` mixed in there somewhere.

**Comment by ryanflorence** [comment]
Awesome write up @jamiebuilds. I've been relying on document order of the portals for this, and as long as you don't do weird crap w/ z-index, I'm hoping this is all we need.

Except that #64 is a thing 😑

**Comment by jamiebuilds** [comment]
Relying on document order alone is definitely not enough. I've seen plenty of bugs with that in my day /old man voice

**Comment by ryanflorence** [comment]
How does outputting:

```jsx
<x-portal>
  <div style="z-index: 1"><x-menu/></div>
  <div style="z-index: 2"><x-dialog/></div>
  <div style="z-index: 3"><x-menu/></div>
</x-portal>
```

differ?

I'm just trying to think of scenarios where people could goof up the layering and its the same either way, they have a bigger z-index on a root element on the document body, and I don't see how grouping those divs in `x-portal` is any safer.

**Comment by jamiebuilds** [comment]
> How does outputting: ... differ?

Because the order of which elements get inserted in the portal is dependent on a depth-first-ish traversal of the DOM by React and in more complex interfaces that's not always reliable.

**Comment by giuseppeg** [comment]
@jamiebuilds is this an issue if one appends the "host" by hand and then renders inside of it with `createPortal`?

```jsx
createPortal(a, container)
createPortal(b, container)
createPortal(c, container)
``` 

vs

```jsx
createPortal(a, container1)
createPortal(a, container2)
createPortal(a, container3)
```

where `containerN` are nodes created by hand and manually appended to `x-portal`: 

```jsx
const container1 = xPortal.appendChild(document.createElement('div'))
createPortal(a, container1)
```

**Comment by chancestrickland** [comment]
@jamiebuilds Do you think this possibly be solved by allowing an `as` prop on components that render a Portal so that users could bail out if needed? I'd need to explore this further but I'm not convinced any sort of stacking prop is the right solution. To your point, it may be better to let apps bail out and manage this if needed.

```jsx
function MyOverlay(props) {
  return <DialogOverlay as={Layer} {...props} />
}
```
