### ISSUE TITLE
[TypeScript] Type definitions are not automatically found when extending styles

### ISSUE THREAD

**Issue by CodingDive** [reach/reach-ui#675]
## 🐛 Bug report

```
import {
  ComboboxPopover as _ComboboxPopover,
} from '@reach/combobox';
export const ComboboxPopover = styled(_ComboboxPopover)`` // <-- this prints the error
```

 The inferred type of 'ComboboxPopover' cannot be named without a reference to '@reach/combobox/node_modules/@reach/popover'. This is likely not portable. A type annotation is necessary.

The same thing happened to the @reach/tabs module whose style I was extending in similar fashion.

### Expected behavior

No type error should be thrown.

### Suggested solution(s)

Importing the types from node_modules resolves it.
```
import * as __ from '@reach/combobox/node_modules/@reach/utils';
```

### Your environment

| Software         |  Version |
| ---------------- |  ------- |
| Reach Package     |  0.11.2       |
| TypeScript                 |   4.0.3      |
| React               |  ^16       |
| Node                 |      12.9.1   |
| yarn         |           1.21.1      |
| lerna        |           3.19     |

**Comment by chaance** [comment]
Cleaning up old issues, but I don't think this is a problem anymore. Huzzah! 🥳 

![screenshot showing inferred types working as expected with styled components](https://user-images.githubusercontent.com/3082153/127954494-a2e1f18d-0697-43b9-995f-0813f9876b9c.png)
