### ISSUE TITLE
Vim / Alternate Keybindings (For Tabs)

### ISSUE THREAD

**Issue by knpwrs** [reach/reach-ui#676]
### Current Behavior

Arrow keys are the only keyboard shortcuts which can navigate between tabs.

### Desired Behavior

I would like to be able to define additional keys which can navigate between tabs, for instance, `h` and `l`.

### Suggested Solution

Something like the following might work:

```tsx
<Tabs
  alternateKeyBindings={{
    ArrowLeft: 'h',
    ArrowRight: 'l',
  }}
>
  {/* */}
</Tabs>
```

Or:

```tsx
<Tabs
  additionalKeyBindings={{
    previous: 'h',
    next: 'l',
  }}
>
  {/* */}
</Tabs>
```

### Who does this impact? Who is this for?

Lots of web apps define vim-like keyboard shortcuts, it would be nice to be able to utilize the same functionality provided by reach to do so accessibly. This is can be considered useful for any web app.

### Additional context

In an effort to enable greater accessibility for my app I just migrated a hap-hazard tabbed component from a manual implementation to `@reach/tabs`. The migration was fairly painless, except I lost the functionality of being able to use `h` and `l` keys that I had built into my original implementation.

**Comment by indiesquidge** [comment]
Reach [wraps event handlers][1] on most components so that you can still make use of them at an application level. Have you considered using a [controlled Tabs component][2] and adding your own `onKeyDown` handler to achieve the functionality you want?

```diff
function TabsExample() {
  const [tabIndex, setTabIndex] = useState(0);

  return (
    <div>
      <Tabs
        index={tabIndex}
        onChange={(index) => {
          setTabIndex(index);
        }}
      >
        <TabList
+         onKeyDown={(e) => {
+           if (e.key === "h") {
+             setTabIndex(previousTab);
+           }
+
+           if (e.key === "l") {
+             setTabIndex(nextTab);
+           }
+         }}
        >
          <Tab>One</Tab>
          <Tab>Two</Tab>
          <Tab>Three</Tab>
        </TabList>
        <TabPanels>
          <TabPanel><p>First Tab</p></TabPanel>
          <TabPanel><p>Second Tab</p></TabPanel>
          <TabPanel><p>Third Tab</p></TabPanel>
        </TabPanels>
      </Tabs>
    </div>
  );
}
```

[1]: https://github.com/indiesquidge/reach-ui/blob/821a03ea757eb25d34ae94d5451adddb3d554397/packages/tabs/src/index.tsx#L344
[2]: https://github.com/indiesquidge/reach-ui/blob/821a03ea757eb25d34ae94d5451adddb3d554397/packages/tabs/examples/controlled.example.js

**Comment by knpwrs** [comment]
That'll probably work, thanks!
