### ISSUE TITLE
Combo box

### ISSUE THREAD

**Issue by ashwinKumar0505** [reach/reach-ui#681]
Is there any way to store the value from the combo box options on pressing down key and up key. I tried it using onKeyDown event but that does not work properly. Can you suggest a way to do this

**Comment by indiesquidge** [comment]
Hey @ashwinKumar0505! I'm not sure I understand what the issue is that you're describing, could you create an example of your problem using the [CodeSandbox template](https://codesandbox.io/s/reach-ui-template-xonfs) please?
