### ISSUE TITLE
[Listbox] Value label is null when rendered conditionally

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#685]
### Current Behavior

If `ListboxPopover` is rendered conditionally based on `isExpanded`, `valueLabel` is null.

### Expected behavior

`valueLabel` is not null.

### Reproducible example

https://codesandbox.io/s/inspiring-feather-60k3k?file=/src/App.js:256-267

### Suggested solution(s)

I don't know, yet!

**Comment by raunofreiberg** [comment]
I guess this happens because the listbox items are unmounted and we can't find the selected value out of children? 

My use case for unmounting the listbox list is to animate the mount/unmount of it. Any other ideas here?

**Comment by raunofreiberg** [comment]
Well, I guess hiding the listbox items from the DOM would solve this problem, but this feels odd:

https://codesandbox.io/s/purple-sun-5bwir?file=/src/App.js:756-772

**Comment by chaance** [comment]
@raunofreiberg Your instinct I believe is correct. I don't believe this is a bug so much as a limitation in React, as we have no way to know what children might be rendered until they are ... well, rendered 😅

The solution in a case like this is to control state pass values and labels directly.
