### ISSUE TITLE
[Alert]: Element div not allowed as child of element span

### ISSUE THREAD

**Issue by mareksuscak** [reach/reach-ui#687]
### Current Behavior

W3 Html Validator complains about div being nested inside a span which is considered invalid syntax.

### Expected behavior

This library should not be using invalid HTML.

### Reproducible example

No example necessary, you can find the relevant snippet of code [here](https://github.com/reach/reach-ui/blob/51e163dcfc2b3654e5344b719398daa3775cab63/packages/alert/src/index.tsx#L148-L167).

![image](https://user-images.githubusercontent.com/613647/96199938-fd87b480-0f58-11eb-8c6c-41324890a9ee.png)

> Heads Up! In order to run the markup by the validator, you'll need to create a bookmarklet for according to https://validator.w3.org/nu/about.html. The bookmarklet ensures that the client-side DOM changes are also being tested since the classic implementation doesn't run JavaScript.

### Suggested solution(s)

Make the root element of the VisuallyHidden component customizable and use a block-level root element such as `div` for the alert.

### Additional context and Motivation

We need to use valid syntax because there are some accessibility trolls out there who are suing companies based on the accessibility or compatibility violations being reported by HTML validators as I was told by an accessibility audit firm.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |         |
| React            |         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by indiesquidge** [comment]
@mareksuscak can we mark this issue resolved now that #689 is merged?

**Comment by mareksuscak** [comment]
Yes sir, thanks!
