### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [reach/reach-ui#690]
### Current Behavior
a tiny bug when trying to import matchSorter as default
"Attempted import error: 'match-sorter' does not contain a default export "

### Expected behavior
...
### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/reach-ui-template-xonfs)

### Suggested solution(s)
solved when imported as not default
### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |         |
| React            |true         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by indiesquidge** [comment]
@Ali-Hussein-dev `match-sorter` is an external library, not part of Reach UI. I would direct all issues/bugs to that [library's GitHub][2]. It does look like a [recent change][1] tagged as V5.0.0 switched the default export to a named export.

[1]: https://github.com/kentcdodds/match-sorter/commit/ad338de83b8244d28717d62d28a1578da22b3917#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R333
[2]: https://github.com/kentcdodds/match-sorter

**Comment by david95s** [comment]
import { matchSorter } from 'match-sorter' <- For me worked.

**Comment by ThPch** [comment]
> import { matchSorter } from 'match-sorter' <- For me worked.

Thanks, worked like a charm

**Comment by ethanstrominger** [comment]
I solved the issue by reinstalling node_modules (`rm- -f node_modules & yarn (or npm install`).  The app had been working, then one day I started getting the above error - doing the previous steps fixed it.
