### ISSUE TITLE
Bump react and react-dom peerDependencies version

### ISSUE THREAD

**Issue by karlhorky** [reach/reach-ui#695]
### Current Behavior

Peer dependency warnings are generated when installing reach-ui libs using React 17:

```
warning @reach/portal@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning @reach/portal@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning @reach/tooltip@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning @reach/tooltip@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
```

### Expected behavior

No warnings.

### Suggested solution(s)

Change peer dependencies to "react@^16.8.0 || react@^17.0.0"

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | many (all?)        | latest        |
| React            |         | 17.0.1        |

**Comment by karlhorky** [comment]
I suppose if there are some incompatibilities such as that fixed by #694, those will need to be fixed first...

**Comment by beorn** [comment]
Seems like #694 is fixed - any other known ones?  Would be nice to shut up the warnings :)

**Comment by mikecousins** [comment]
And if you're using npm 7 it just doesn't install at all unless you use the `--legacy-peer-deps` flag.

**Comment by wojtekmaj** [comment]
Looks like a couple of deeper dependencies are also throwing some dependency warnings:
```
react-focus-lock@2.5.0 provides react@17.0.1 which doesn't satisfy ^15.3.0 || ^16.0.0 requested by react-clientside-effect@1.2.2
react-focus-lock@2.5.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by use-callback-ref@1.2.4
react-focus-lock@2.5.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by use-sidecar@1.0.3
react-remove-scroll@2.4.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by react-remove-scroll-bar@2.1.0
react-remove-scroll@2.4.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by react-style-singleton@2.1.0
react-remove-scroll@2.4.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by use-callback-ref@1.2.4
react-remove-scroll@2.4.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by use-sidecar@npm:1.0.3
react-remove-scroll-bar@2.1.0 provides react@17.0.1 which doesn't satisfy ^16.8.0 requested by react-style-singleton@npm:2.1.0
```

**Comment by felixmosh** [comment]
All reach-ui components are compatible to `^16.8` therefore compatible to `17`.

**Comment by karlhorky** [comment]
@felixmosh Ok, then opened #718 for this, thanks!
