### ISSUE TITLE
broken combobox server side search 

### ISSUE THREAD

**Issue by lawnchamp** [reach/reach-ui#696]
## 🐛 Bug report

When trying to use the server side search demo at https://reach.tech/combobox/#server-side-search the fetch to https://city-search.now.sh/? is returning the error:
>Access to fetch at 'https://city-search.now.sh/?testing' from origin 'https://reach.tech' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Current Behavior
When using the [live demo](https://reach.tech/combobox/#server-side-search) in the documentation  the result is always "No results found" because there is a CORS error
<img width="1375" alt="Screen Shot 2020-11-05 at 12 09 30 AM" src="https://user-images.githubusercontent.com/13643618/98200254-30d7b680-1efb-11eb-8a5e-5e70e9164645.png">

**Comment by indiesquidge** [comment]
Hmm looks like the service itself is actually down; I get a 404 DEPLOYMENT_NOT_FOUND error when attempting to hit the endpoint directly. @chaance do you know what's going on here?

**Comment by chaance** [comment]
@indiesquidge Looks like something Ryan set up a while ago on Now v1, which is no longer supported by Vercel. I'll see if we can get it up elsewhere this weekend.

**Comment by chaance** [comment]
Fixed!
