### ISSUE TITLE
Explain how to install the package on documentation website.

### ISSUE THREAD

**Issue by bricejar** [reach/reach-ui#697]
## 📖 Documentation

Most documentations explain how to install the package with yarn or npm. Users often look for this so as to find the exact package name.

**Comment by indiesquidge** [comment]
@bricejar each package does include an [Installation section][1] on the Reach UI website. Or are you referring to something else?

[1]: https://reach.tech/combobox#installation

**Comment by chaance** [comment]
@bricejar Each component is a separate package and, per @indiesquidge's comment we already have this documented. Open to suggestions on how we might make it more clear, but I'm going to close this for now!
