### ISSUE TITLE
Use `preview-head.html` instead of importing `styles.css`

### ISSUE THREAD

**Issue by stramel** [reach/reach-ui#7]
I noticed you were importing the `styles.css` on each story to apply the global css. You should be able to accomplish the same thing using 

```html
<!-- preview-head.html -->
<style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans,
      Ubuntu, Cantarell, Helvetica Neue, sans-serif;
  }
</style>
```

Side Note: I like to add the emoji fonts at the end of my font-family stack. `, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`

**Comment by ryanflorence** [comment]
if you wanna PR that I'll merge it.
