### ISSUE TITLE
Demo site Dialog(Modal) - Escape doesn't close most modals

### ISSUE THREAD

**Issue by Jared-Dev** [reach/reach-ui#70]
[This](https://ui.reach.tech/dialog#dialog-ondismiss) is the only demo modal that I've found that would actually close its open modal.

I was going to look through the source code for the site to see if I could possibly submit a PR with a fix, but I'm not seeing a repo for the site (is it staring me in the face?).

The only reason I point this out is that I actually assumed that the library didn't have this capability until I found the little nugget that mentions it at the end of the documentation!

Thanks for the library! Again if there is a public repo I'll take a stab at looking into that if I get time.

**Comment by pdong** [comment]
That looks correct to me.  If you read the section it is about the `onDismiss` prop.  The function there gets called when escape or the backdrop is clicked and you can close your modal.  That's the only example with an `onDimiss`  so it makes sense that that's the only one that closes with escape.

**Comment by InquisitiveDevelopment** [comment]
That indicates that if `onDismiss` is implemented it will be called and that you have to manage the state of `showDialog`. The documentation for [keyboard accessibility](https://ui.reach.tech/dialog#keyboard-accessibility) indicates that it will close the dialog if the app allows it.

I guess what I'm trying to get at is that while you may be correct that the demos are functioning as planned. The docs for keyboard accessibility could probably use a rewording to point to the need to implement `onDismiss` is you want that capability.

**Comment by ryanflorence** [comment]
Each modal is illustrating a different prop, I try to avoid adding any props that aren't critical for the thing it's documenting.

But the first example should absolute have onDismiss.

FYI, the website is in `www`, want to take a stab at it @Jared-Dev?

**Comment by Jared-Dev** [comment]
@ryanflorence sure thing. Would it be worth pointing out on that page somewhere (where?) that `onDismiss` is excluded for brevity, but should be on all `DIalog`'s?

I ask since the way I read that page initially was that closing a `Dialog` was another bit of magic that the library just attempted to handle. With the `onDismiss` section being included to show how specific control could be taken if needed.

**Comment by chancestrickland** [comment]
@Jared-Dev We've made quite a few updates to the build tools. If you're still interested in helping, let me know if you run into issues getting the site running and I can help troubleshoot on Windows if needed.

**Comment by kiku511** [comment]
Not sure if something changed but this seems to be working fine. I could close most the modals with the escape key. Is there something I am missing here?

**Comment by chancestrickland** [comment]
@kiku511 I believe we've updated all of the examples on the docs to include `onDismiss`, so I'll go ahead and close this.
