### ISSUE TITLE
Unable to override Dialog element with styled-components

### ISSUE THREAD

**Issue by hanselabreu** [reach/reach-ui#703]
### Current Behavior

Using the `[data-reach-dialog-overlay]` or `[data-reach-dialog-content]` is not overriding the default styles using `styled-components@5.2.0`.

```
import styled from "styled-components"
import { Dialog as ReachDialog } from "@reach/dialog"

export const Dialog = styled(ReachDialog)`
  background-color: blue;

  > [data-reach-dialog-overlay] {
    background-color: red;
  }

  > [data-reach-dialog-content] {
    background-color: red;
    height: 100vh;
  }
`
```

### Expected behavior

Default values should be overriden.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    dialog     |     0.11.2    |
| React            |         |    16.13.1     |
| Browser          |         |     Chrome    |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by ghostd** [comment]
Hi,

As stated in the [`DialogContent` documentation](https://reach.tech/dialog#dialogcontent):
```
Low-level component if you need more control over the styles or rendering of the dialog content.
```

So you can do something like this:
```
const ModalOverlay = styled(DialogOverlay)`
  background: rgba(0, 0, 0, 0.6);
`;

const ModalContent = styled(DialogContent)`
  margin: 0;
  padding: 0;
`;

function noop() {}

export const DialogModal = forwardRef<HTMLDivElement, DialogProps>(function DialogModal(
  { allowPinchZoom = false, initialFocusRef, isOpen, onDismiss = noop, ...props },
  forwardedRef
) {
  return (
    <ModalOverlay allowPinchZoom={allowPinchZoom} initialFocusRef={initialFocusRef} isOpen={isOpen} onDismiss={onDismiss}>
      <ModalContent ref={forwardedRef} {...props} />
    </ModalOverlay>
  );
});

```

**Comment by indiesquidge** [comment]
@hanselabreu if you are still having trouble with this, could you include a reproducible example? Your issue is likely one of build order. Are you sure that your app is loading Reach's Dialog CSS _after_ your component or any custom styling that you have?

> All styles use the lowest possible "specificity score", so as long as you include the component styles before your own app styles you should not run into any specificity problems. [[source][1]]

[1]: https://reach.tech/styling#css-selectors

**Comment by hanselabreu** [comment]
@indiesquidge the code snipped I attached produces the error. `Reach's Dialog CSS` is being loaded at the `root` of the project. In fact, the custom CSS is never rendered into the component.

```
import styled from "styled-components"
import { Dialog as ReachDialog } from "@reach/dialog"

export const Dialog = styled(ReachDialog)`
  background-color: blue;

  > [data-reach-dialog-overlay] {
    background-color: red;
  }

  > [data-reach-dialog-content] {
    background-color: red;
    height: 100vh;
  }
`
```

Outputs:

![image](https://user-images.githubusercontent.com/27902567/100297459-bc71bf80-2f5c-11eb-8344-509cd3640694.png)

**Comment by indiesquidge** [comment]
@hanselabreu a code snippet is not a reproducible example, it's a snippet :) It's helpful for us to have something live to see your issue.

I created a [CodeSandbox][1] (as per the [issue template][2]), and as @ghostd suggests, you can style the elements directly if you drop down to the lower-level components `<DialogContent>` and `<DialogOverlay>`.

Notice that `<Dialog>` is a shorthand wrapper around these components, and passes most of its props to the inner `<DialogContent>`.
https://github.com/reach/reach-ui/blob/c943b1104997d97b264033c1a413000e3dfae0d0/packages/dialog/src/index.tsx#L300-L309

Which means the CSS selectors in your styled component aren't selecting anything, as the overlay exists as a parent of the content.

[1]: https://codesandbox.io/s/snowy-fast-qisim
[2]: https://github.com/reach/reach-ui/issues/new?template=Bug_report.md
