### ISSUE TITLE
Dialog: Add ability to keep Dialog open on overlay click

### ISSUE THREAD

**Issue by laurenmbeatty** [reach/reach-ui#705]
### Current Behavior

Currently, clicking outside of the Dialog onto the DialogOverlay will close the Dialog automatically.

### Desired Behavior

It would be great to have an optional prop available that prevented this behavior. Something like `dismissOnOverlayClick`

### Suggested Solution

Perhaps a check [here](https://github.com/reach/reach-ui/blob/8ebdb4d7677ddb52077e3c0badc770213361263c/packages/dialog/src/index.tsx#L160-L165) for the overlay ref to call onDismiss if the prop is set to true and the target is the overlayRef.current, but would return if the prop is false. Prop would be true by default.

### Who does this impact? Who is this for?

We are currently considering alternative libraries to the modal component we use, and this is a requirement. I may be able to implement this apart from the library, but it would be nice to have it built-in.

### Describe alternatives you've considered

The above suggested solution is what I've considered, apart from using a different library, but I'm a huge fan of Reach. ✨ 

Thank you! 🙇‍♀️

**Comment by indiesquidge** [comment]
You can use the lower-level components that make up the Dialog if you'd like finer control over how they behave

```diff
function MyDialog() {
  const overlayRef = React.useRef(null);
  const contentRef = React.useRef(null);
  const [showDialog, setShowDialog] = React.useState(false);
  const open = () => setShowDialog(true);
  const close = () => setShowDialog(false);

  return (
    <div>
      <button onClick={open}>Show Dialog</button>

      <DialogOverlay
        ref={overlayRef}
        style={{ background: "hsla(0, 100%, 100%, 0.9)" }}
        isOpen={showDialog}
-       onDismiss={close}
      >
        <DialogContent
          aria-label="Announcement"
          ref={contentRef}
          style={{ boxShadow: "0px 10px 50px hsla(0, 0%, 0%, 0.33)" }}
        >
          <p>
            The overlay styles are a white fade instead of the default black
            fade.
          </p>
          <button onClick={close}>Very nice.</button>
        </DialogContent>
      </DialogOverlay>
    </div>
  );
}
```

However, the ability to close the dialog on overlay press is an accessibility feature, and it's usually a bad idea to prevent this behavior, especially if it's only for a design requirement.

> The only time you shouldn't close the dialog on dismiss is when the dialog requires a choice and none of them are "cancel". For example, perhaps two records need to be merged and the user needs to pick the surviving record. Neither choice is less destructive than the other, in these cases you may want to alert the user they need to a make a choice on dismiss instead of closing the dialog. [[source][1]]

[1]: https://reach.tech/dialog/#dialog-ondismiss
