### ISSUE TITLE
Tabs: propTypes error when using a render function

### ISSUE THREAD

**Issue by mitchgavan** [reach/reach-ui#706]
### Current Behavior

When passing a render function to the `<Tabs>` the following error is logged to the console:

> Warning: Failed prop type: Invalid prop `children` supplied to `Tabs`, expected a ReactNode.

### Expected behavior

No error logged to the console.

### Reproducible example

Example taken directly from the docs: [CodeSandbox](https://codesandbox.io/s/laughing-moore-v98zv?file=/src/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | Tabs |     0.11.2    |
| React            |         |  17.0.1       |
| Browser          | Chrome | 87 |
| Node             |         | 14.9.0  |
| npm/yarn         | Yarn  | 1.22.5  |
| Operating System | MacOS | 10.15.7 |

**Comment by indiesquidge** [comment]
Hmm, interesting that this error doesn't come up when you run the Storybook examples locally, nor does it occur if I clone the tabs source code into a local app.

It appears the issue has something do do with how the package was built in `v0.11.2` that turned this line

https://github.com/reach/reach-ui/blob/09eeccda6e4597d21545982c53db5c42beddce6b/packages/tabs/src/index.tsx#L270

into this
```
children: PropTypes__default['default'].node.isRequired,
```

Coincidentally, a new version ,`0.12.0`, was released within the hour, and that package's build is correct
```
children: /*#__PURE__*/PropTypes__default['default'].oneOfType([PropTypes__default['default'].func, PropTypes__default['default'].node]).isRequired,
```

**Comment by mitchgavan** [comment]
ahh 😁  thank you for the quick response.
