### ISSUE TITLE
Improve documentation for `as` prop in all cases

### ISSUE THREAD

**Issue by alaycock** [reach/reach-ui#710]
## 📖 Documentation
When implementing the `DisclosureButton` component, it started logging the error:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `DisclosureButton`.
```

It took a while to figure out that my button component needed to be wrapped with the a `forwardRef`. When trying to minimally reproduce this problem, I also found that the `onClick` property is required for Disclosure to function at all.

Would it be worth documenting the properties that are required for the `as` component? Or include an example of how to properly implement a custom disclosure button component?

If so, what are the requirements for Disclosure to operate as expected? I now know of `forwardRef` and the `onClick` prop, but is there anything else that is essential? Or should custom buttons always use prop spreading?

**Comment by chaance** [comment]
I'm not 100% clear on the problem here. Can you create a CodeSandbox with a reproduction showing what exactly you initially tried that didn't work? `Disclosure` should work without controlling the state, and the `as` prop is documented here: https://reach.tech/disclosure/#disclosurebutton-as

**Comment by alaycock** [comment]
@chaance here's what I mean:
https://codesandbox.io/s/disclosure-issue-repro-5xke5?file=/src/App.js

Without the `forwardRef` it produces this error:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `DisclosureButton`.
```
Given that I'm new to forwarding refs, that made me think that there was an issue in `DisclosureButton`, rather than in the component that I wrote.

My suggestion that this could be documented better, maybe the docs could indicate that `forwardRef` is required for the component that is used for the `as` prop.

**Comment by chaance** [comment]
Ah yes, I see now. Thank you!

Yes, as a rule you *always* need to forward refs in your implementation, and this is less about the `onClick` prop and more that you should really forward *all* props as well. https://codesandbox.io/s/disclosure-issue-repro-forked-1tjvd?file=/src/App.js

You're right that we can probably document it better. Perhaps a page on polymorphism/as prop usage that clarifies this would help, as it applies to all components.

**Comment by alaycock** [comment]
> Yes, as a rule you always need to forward refs in your implementation, and this is less about the onClick prop and more that you should really forward all props as well.

This makes sense and the idea isn't new to me, although more often I've seen the props passed in via a hook, eg, [`get___Props` in Downshift](https://www.downshift-js.com/use-select#props-used-in-examples). When you say this is a rule, is this following a pattern from other libraries or standard that you'd expect folks to be aware of, or a rule within Reach? I think I've seen the `as` prop in other libraries, is that a standard rule that I've been unfamiliar with until now.
