### ISSUE TITLE
[Descendants] conflicting index values in registerDescendant() ?

### ISSUE THREAD

**Issue by tshinnic** [reach/reach-ui#711]
This is purely from reading source of reach-ui/packages/descendants/src/index.tsx and I'm not where I could check further.

`DescendantProvider` internal function `registerDescendant()` ends with a [final "polishing up" line](https://github.com/reach/reach-ui/blob/develop/packages/descendants/src/index.tsx#L199)
```
    return newItems.map((item, index) => ({ ...item, index }));
```
to explicitly set the index number value of every item in the list given to `set()`, which then replaces the previous list of items.

As it reads, that final line will explicitly undo the [first clause of code](https://github.com/reach/reach-ui/blob/develop/packages/descendants/src/index.tsx#L133-L141) in `registerDescendant()` which tries to allow callers to set the item index manually. The index property will always be overwritten by that last line of code.

Further, it seems that the [third clause of code](https://github.com/reach/reach-ui/blob/develop/packages/descendants/src/index.tsx#L152-L154) is trying to allow for "no changes needed" when an already known element is again attempted. If the list given to `set()` is the previous list, work is avoided (correct?). But the `.map()` will always force a new list to be generated. 

Again, this is just from reading source, but it looks like the first and third if clauses ought to return immediately with their list, without falling through to the `.map()` on the final line.

Should I have gone to bed a few hours ago?

**Comment by chaance** [comment]
It's possible, but unless you have a specific problem that you can reproduce I'm going to close this for now. Feel free to submit a PR if you think we can improve the implementation -- I'm sure we can!
