### ISSUE TITLE
Make MOUSE_REST_TIMEOUT configurable for tooltips

### ISSUE THREAD

**Issue by sanbornhilland** [reach/reach-ui#713]
### Current Behavior

Currently the default `MOUSE_REST_TIMEOUT` for `Tooltips` is `100ms`, here: https://github.com/reach/reach-ui/blob/09b4d0a6f65803645e768a99f18907e96be7d4d6/packages/tooltip/src/index.tsx#L62.

### Desired Behavior

This feels slightly faster than I'd like and when I compare it to various other apps, it seems like it's quite fast. Ideally this value would be configurable. 

### Suggested Solution

It's not immediately clear to me what the cleanest way to do this would be. In it's current form it may be easiest to allow a single global setting but it might be more flexible if the timeout could be specified as `props` or arguments to the `useTooltip` hook.

### Who does this impact? Who is this for?

Users that want more control over the `Tooltip` behaviour

### Describe alternatives you've considered

I'm already using `react-spring` for animations so I tried to insert a delay before the Tooltip entrance animation. There are two problems with this approach, besides the fact that it feels like a hack.

1. It's only useful if you already have access to this library. You don't want to add a dependency just to tweak this time.
1. This would apply to each tooltip individually which I think is not really what is wanted because if the user is hovering over several tooltips in a row, it's only the first one that should have an increased delay. The others should show immediately.

**Comment by chaance** [comment]
See https://github.com/reach/reach-ui/issues/411#issuecomment-573970811

I'll leave this open because we haven't ruled it out, but it's not a priority at least until ARIA can finalize their recommendations.

**Comment by sanbornhilland** [comment]
> See [#411 (comment)](https://github.com/reach/reach-ui/issues/411#issuecomment-573970811)
> 
> I'll leave this open because we haven't ruled it out, but it's not a priority at least until ARIA can finalize their recommendations.

Thanks for the response. I didn't see that issue initially.

In the mean time is there an obvious work around that I'm missing? The only one that I could think of would be to take over the animation and add delays like I tried with `react-spring` but because tooltips don't act in isolation, I don't think it's possible to get this right. In fact the `react-spring` example in the docs which was really useful to understand how to combine these libraries, creates an awkward interaction because of this issue of tooltip animations acting in isolation but the tooltip behaviour being inter-dependent with other tooltips. Ideally we would be able to apply different animations depending on whether we are moving from (1) tooltip to tooltip or (2) from no tooltip to tooltip or (3) tooltip to no tooltip. As far as I can see this isn't exposed right now but internally these different transitions are accounted for. If there's no appetite to introduce a specific API for timings, I'm wondering if there would be an appetite for a more generic API that let's the consumer hook into the tooltip events that apply across tooltips. It would solve the custom animation problem and also introduce a workaround option for this issue of wanting more control over timings.
