### ISSUE TITLE
[combobox] Home/End button should move cursor in input field

### ISSUE THREAD

**Issue by stefanprobst** [reach/reach-ui#717]
### Current Behavior

currently, when pressing <kbd>Home</kbd> or <kbd>End</kbd> in a combobox input, the first/last value in the listbox will be selected, but the cursor in the `<input>` does not move, which feels very odd.

### Expected behavior

Pressing <kbd>Home</kbd> should place the cursor at the first character in the input field. similarly for <kbd>End</kbd>

### Reproducible example
https://codesandbox.io/s/combobox-home-btn-xj36c?file=/src/index.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  combobox       |   0.11.2      |
| React            |         |  17.0.1       |
| Browser          | Firefox         |  84      |
| Assistive tech   |         |         |
| Node             |         | 14.15.3        |
| npm/yarn         |  yarn       | 1.22.5        |
| Operating System |  Ubuntu       |  20.04        |

**Comment by stefanprobst** [comment]
the current behavior might actually be intentional, as it seems to match e.g. the combobox in react-aria, and material-ui.

the [wai-aria authoring practices](https://www.w3.org/TR/wai-aria-practices-1.2/#combobox-keyboard-interaction) have this:

When focus is in the combobox:
- If the combobox is editable, it supports standard single line text editing keys appropriate for the device platform (see note below).

When focus is in a listbox popup:
- Home (Optional): Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.
- End (Optional): Either moves focus to the last option or, if the combobox is editable, returns focus to the combobox and places the cursor after the last character.

**Comment by indiesquidge** [comment]
I get somewhat strange behavior of <kbd>Home</kbd> and <kbd>End</kbd> on the [wai-aria examples][1], at least in Chrome 87 on macOS 11.0.1, where the keys have to be pressed twice to move the cursor in the combobox. (In Safari 14 I actually don't get any combobox behavior with those keys.)

![combobox](https://user-images.githubusercontent.com/3409645/103485501-0481ce80-4db4-11eb-9a9c-56d7a86d3a43.gif)

Alternatively, Google's search combobox only moves the cursor to the beginning or end of the input when <kbd>Home</kbd> or <kbd>End</kbd> are pressed, respectively—the keys do nothing to the listbox of options. (And again, in Safari 14 I get no combobox behavior here with the keys.)

It's also worth pointing out that the combobox input element always retains focus (i.e. `document.activeElement`) even when the listbox is being navigated. This is true in the Reach UI combobox, Google's combobox, and the wai-aria example comboboxes. So I'm not sure what the spec strictly means by "when focus is in a listbox popup" as it relates to a combobox.

@stefanprobst certainly happy to take suggestions for improvement here, but not sure what the change should be. As it currently stands, Reach UI's <kbd>Home</kbd> and <kbd>End</kbd> behaviors are predictable and consistent across browsers (which cannot be said for many combobox implementations).

[1]: https://www.w3.org/TR/wai-aria-practices-1.2/#examples-1

**Comment by stefanprobst** [comment]
to give a bit more context: i'm trying to build a search input which accepts arbitrary text input and displays autosuggestions in a listbox popup, much like the google searchbox, or the top searchbox here on github. while reach ui's current behavior wrt Home and End is predictable, i don't think it fits the autosuggest searchbox usecase very well. wrt some actionable suggestion i'm not sure myself, i'll think on it.

**Comment by stefanprobst** [comment]
the [material-ui Autocomplete](https://material-ui.com/components/autocomplete/#free-solo) seems to handle this via a separate `handleHomeEndKeys` prop.
