### ISSUE TITLE
Should the MenuButton's MenuLink component announce that it is a link to screen readers?

### ISSUE THREAD

**Issue by phunkren** [reach/reach-ui#722]
## ❓Question
My screen reader only announces the content of a Reach UI [MenuLink](https://reach.tech/menu-button/#menulink), but doesn't mention that:

a) it's a link 
b) where it'll take the user.

Is this expected behaviour? Is there a way to notify the user if the content doesn't explicitly outline the action?

https://codesandbox.io/s/mystifying-darwin-dzfw0

**Comment by phunkren** [comment]
Briefly spoke with @chaance on this last week. Thread for reference:
https://twitter.com/phunkren/status/1347615510314233856

**Comment by chaance** [comment]
@phunkren Can you let me know what screen reader you're using so I can speak more directly to your reproduction?

**Comment by phunkren** [comment]
Hey @chaance,

I'm using NVDA. Let me know if there's anything I can do to help
