### ISSUE TITLE
How would you make a Mega Menu with Reach UI?

### ISSUE THREAD

**Issue by kilinkis** [reach/reach-ui#723]
## ❓How would you make a Mega Menu with Reach UI?

I'm trying to create an accesible Mega Menu, so I think Reach UI can be valuable help.
What I'm trying to do is very basic, just a couple of dropdowns which will have different child components (I mean, it's not just a list of links).

I was looking at https://reach.tech/menu-button/ first, but it seems like it's only clickeable (should I emulate a click using refs?), and not sure if it's the best solution when I'll have different child components in the dropdown content.

So then I saw https://reach.tech/disclosure, and it seems more like what I need, but I still need two or three disclosures, since I'll have a few nav items with dropdowns. Is there a best way to have multiple disclosures?
I saw that there is `useDisclosureContext` but there's no example on how to use it.

on top of that, should all these be children of a nav tag?

thanks in advance

**Comment by chaance** [comment]
I probably wouldn't make a mega menu with Reach, either with MenuButton or Disclosure. Both have very specific accessibility functions and a mega menu has its own requirements. Here are a few references that show examples and talk at length about what you need for a mega menu to be accessible for all users. 

https://adobe-accessibility.github.io/Accessible-Mega-Menu/
https://www.levelaccess.com/challenges-mega-menus-standard-menus-make-accessible/
