### ISSUE TITLE
[Combobox] Controlling the open state

### ISSUE THREAD

**Issue by raunofreiberg** [reach/reach-ui#726]
## ❓Question

👋 

There may be better alternatives here, but we're looking to improve our Combobox experience on mobile. Having it as-is on smaller screens is very bad since the keyboard covers most of the options. 

(I know that the native `<select>` is generally preferred for a smooth mobile experience, but some use cases warrant a search interface to navigate bigger data sets)

As a result, I'm trying to render `@reach/combobox` in a drawer on mobile which is essentially a dialog that appears from the bottom of the screen. See the screenshot below for reference.

Pseudo code:

```tsx
// <Combobox.List />

const { isExpanded } = useComboboxContext()

if (isMobile) {
  return (
    <ComboboxPopover
      portal={false}
      as={Drawer}
      show={isExpanded}
      onDismiss={() => {
        // ??
      }}
    >
      <Input />
      <ComboboxList>{results}</ComboboxList>
    </ComboboxPopover>
  )
}
```

Though, I'm having trouble hooking into the open state of the Combobox (specifically closing the drawer). Is that something that would be a reasonable part of the component to expose?

Thanks

![image](https://user-images.githubusercontent.com/23662329/104954330-b7674480-59d0-11eb-89e1-44f5c14361a9.png)

**Comment by chaance** [comment]
@raunofreiberg To be clear here, you aren't having trouble accessing the open state, but instead you're looking for a way to programmatically close the popover since the normal behavior wouldn't really apply for this use case. Is that correct?

**Comment by chaance** [comment]
Internally we use a state machine to manage this. Seems like you essentially want to simulate what we do when the user presses `Escape` for a normal popover. 

```js
// what we do internally when escape is pressed
if (state !== IDLE) {
  send(ESCAPE); // transitions to the IDLE state
}

// some fake API that would trigger a similar transition

const { isExpanded, close } = useComboboxContext()

if (isMobile) {
  return (
    <ComboboxPopover
      portal={false}
      as={Drawer}
      show={isExpanded}
      onDismiss={close}
    >
      <Input />
      <ComboboxList>{results}</ComboboxList>
    </ComboboxPopover>
  )
}
```

**Comment by raunofreiberg** [comment]
Yeah, exactly. Though I am aware that this may be unorthodox or out of limits in terms of what kind of control you want to expose. But happy to consider alternatives and see how others have worked around a similar problem.

**Comment by chaance** [comment]
Thanks for confirming. Your use case raises a good question though I'm unsure that the proposed solution is the right one. In my mind we would provide a way to compose these parts yourself, so `Popover` and `Drawer` would both work in a combobox context and provide the functionality you need. Unfortunately I don't know that I have the time in fleshing out something like this anytime soon, but it's good to know and worth keeping on the back burner.
