### ISSUE TITLE
Why is Popover not documented?

### ISSUE THREAD

**Issue by kylemh** [reach/reach-ui#729]
## ❓Question

https://github.com/reach/reach-ui/tree/develop/packages/popover exists, and I don't see anything inherently wrong with the implementation... Is there a reason we shouldn't be using it?

**Comment by chaance** [comment]
Popover is considered an internal utility component. You're of course welcome to use it if it fits your needs, but we are a bit less careful in updating internal packages when it comes to breaking changes.
