### ISSUE TITLE
Unable to Override Default Menu Styling

### ISSUE THREAD

**Issue by nathanforce** [reach/reach-ui#73]
I'm loving the data-attribute style hooks, but with `<Menu />` I am unable to access the top level div.

https://github.com/reach/reach-ui/blob/master/packages/menu-button/src/index.js#L155-L159

The styles here seem to be adding `fontFamily`.  I'm using Glamor so the only way I can think to override these styles is by wrapping my Menu in a `div`. Not the end of the day but also not ideal.

**Comment by nathanforce** [comment]
Actually a div doesn't work either as the `div` does not get portaled.

**Comment by ryanflorence** [comment]
https://github.com/reach/reach-ui/blob/61804848e2b1ee7ed61fc6f9458ba48e80e47695/packages/menu-button/src/index.js#L301

should be what you need?

Will reopen if I'm mistaken.

**Comment by nathanforce** [comment]
@ryanflorence That works for global overrides I suppose.  I was looking to add props (`className`) onto the div that is created by <MenuList />. The only non global way I can think to hook onto `data-reach-menu` is to add a parent element that can then leverage css nesting, which is less ideal as it requires an extra wrapping div.

```const MySerifFontMenu = () => {
    return (
        <Menu> 
            <MenuList> // <-- I want to override 'font-family: sans-serif';
                { /* ... */ }
            </MenuList>
        </Menu>
    )
}

// this works but requires the outer div
const MySerifFontMenu = () => {
    return (
        <div {...css({
            '& [data-reach-menu]: {
                fontFamily: 'serif'
            }
        })}>
            <Menu>
                <MenuList>
                    { /* ... */ }
                </MenuList>
            </Menu>
        </div>
    )
}```

Basically, I'd like access to pass arbitrary props to this div https://github.com/reach/reach-ui/blob/61804848e2b1ee7ed61fc6f9458ba48e80e47695/packages/menu-button/src/index.js#L300-L304

I'm not sure of a great way to do this without exposing some weird api.
