### ISSUE TITLE
[Menu Button] styling MenuLink with styled-components breaks default behavior

### ISSUE THREAD

**Issue by mlimberg** [reach/reach-ui#730]
## 🐛 Bug report

When styling a `MenuLink` component and setting the `as` property to a `Link` from react-router-dom, the link within the MenuList no longer works w/ built in pseudo selectors or keyboard navigation

### Current Behavior

Opening menu defaults to second item and first item (styled link) is not navigable nor does it have they styles set based on the pseuo selector settings

![image](https://user-images.githubusercontent.com/16227556/105528178-e2d48280-5ca1-11eb-9e6f-135c37344097.png)

### Expected behavior

If you use an un-styled MenuLink with the `as` prop set to a react-router-dom Link, it works as expected. It's only when styling via styled-components. Additionally, a styled MenuItem still works with default behavior which leads me to believe it is a bug with the MenuLink

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/styled-menu-13vls?file=/src/App.js)

_note: changing from `as={Link}` to `const StyledLink = styled(MenuLink).attrs({ as: Link })` does not make a difference_

### Suggested solution(s)

Unclear, would need to understand why links are affected differently than the menu item div's. Seems there are workarounds to style MenuLinks without using the styled-components method, so this is definitely a low priority issue but thought I would call it out. 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | @reach/menu-button | 0.12.1 |
| React            |         | 17.0.0, 17.0.1      |
| Browser          | Chrome        |    87.0.4280.88     |
| React-dom    |         |   17.0.0, 17.0.1      |
| styled-components             |         |  5.2.1       |
| react-router-dom         |         |     5.2.0    |
| Operating System |     Catalina    |    10.15.7     |

**Comment by gavinsharp** [comment]
I think you may be running into a conflict with the [`styled-components` `as` prop](https://styled-components.com/docs/api#as-polymorphic-prop). You may need to use [`forwardedAs`](https://styled-components.com/docs/api#forwardedas-prop) instead.

**Comment by chaance** [comment]
What @gavinsharp said. Here's a tweak to your sandbox that should help you out. https://codesandbox.io/s/styled-menu-forked-sj2wx?file=/src/App.js
