### ISSUE TITLE
[Popover] How can I programmatically close a Popover?

### ISSUE THREAD

**Issue by brookback** [reach/reach-ui#731]
## ❓Question

Anybody know how I can programmatically close a `MenuPopover`? I've read the source of both [`MenuButton`](https://github.com/reach/reach-ui/blob/develop/packages/menu-button/src/index.tsx) and [`Popover`](https://github.com/reach/reach-ui/blob/develop/packages/popover/src/index.tsx), and I can't find a way to close it.

No "write" APIs are exposed to do things, and nor can I force close a popover by triggering `click` events on a `MenuButton` or `document`.

***

My use case is that I have a link in a popover which should trigger another view in my React app and close the popover. Let me know if I've missed anything in the documentation around this.

**Comment by brookback** [comment]
Ok, a second after posting this I realised Reach is using the `mousedown` event instead of `click`. So triggering the former on the button works:

```js
domButton.dispatchEvent(new Event("mousedown"));
```

(although this answers my question, it'd be *really* sweet with a 1st class component API for this ✨✨✨).

**Comment by chaance** [comment]
We intentionally don't have an API for this because the menu popover behaves in a specific way for a reason to meet accessibility needs. Can you explain your use case a bit more and why you think we should have an API to support this?

**Comment by brookback** [comment]
Thanks for replying! 🙏

> because the menu popover behaves in a specific way for a reason to meet accessibility needs.

I totally get that. Would a programmatic close call mess the state up for screenreaders and others? Like, if a hook would expose a `toggle(show: boolean) => void` function, would that be like pulling the rug on a11y tooling?

***

The use case is merely to close a popover once the user interacts with a button or link inside of it. I know dropdown menus in Reach close as soon as you click an item or link inside of them, but popovers don't.

For my specific case, my popover has a button inside of it, which toggles the visibility of another pane in the app. The default behaviour of the Reach popover is currently to linger on the screen after the button click.

**Incorrect behaviour — popover doesn't close**

https://user-images.githubusercontent.com/30257156/105814788-30a6fe80-5fb2-11eb-8ff1-a6a4f7402171.mov

**Correct behaviour — popover close**

https://user-images.githubusercontent.com/30257156/105814800-34d31c00-5fb2-11eb-8c1b-ec1be045b2b7.mov

**Comment by chaance** [comment]
In your example the popover should close on blur, so are you properly sending focus to the new popover when it opens? If so and it still doesn't work, that's certainly a bug we should address. Happy to help if you can create a repro in CodeSandbox.

**Comment by brookback** [comment]
@chaance Thanks for the hint! I didn't pick that up myself.

However, it doesn't seem to work correctly (unless I'm doing something wrong): https://codesandbox.io/s/beautiful-hypatia-lmknd?file=/src/App.tsx

The pane which is shown when one clicks the button in the popover is getting focus (red background), but the popover is still showing:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/30257156/106119363-689a7700-6155-11eb-8e65-d51724c4a030.png">

I followed the stuff in https://reach.tech/menu-button/#unmounting-the-menu-after-an-action.
