### ISSUE TITLE
[ListBox] Cannot focus on ListboxList when its styled to overlap ListboxButton

### ISSUE THREAD

**Issue by loque** [reach/reach-ui#735]
## 🐛 Bug report

First of all, amazing library, thanks for the hard work! I'm trying to create a `ListBox` with a behaviour similar to the [Select of Material UI](https://material-ui.com/components/selects/) in the sense that I want `ListboxList` to completely cover `ListboxButton` when shown.

### Current Behavior

If I understand correctly, the `ListboxList` is shown on `ListboxButton`'s _mousedown_ but the focus on `ListboxList` is triggered on `ListboxButton`'s _mouseup_. In this situation, when the user triggers the _mousedown_ event  the `ListboxList` is shown beneath the user's mouse. _mouseup_ is not triggered with `ListboxButton` as a target, thus, not calling the function `focusList` in the machine.

### Expected behavior

I would expect the `ListboxList` to be focused after being shown even if it is placed over the `ListboxButton`.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/thirsty-kare-tqdot?file=/src/App.js)
Clicking in the bottom half of `ListboxButton` will not focus on `ListboxList`. Clicking in the upper half (not covered by `ListboxList`) it will.

### Suggested solution(s)

Would you consider showing the `Popover` on _click_ or _mouseup_ instead of _mousedown_? I assume there is a background that I'm not aware of so I don't know if this is possible.

### Additional context

Some of the problems that this causes is that no keyboard events are being listened and sometimes you get an "automatic" selection of an `ListboxOption`.

This is what caused the [issue 664](https://github.com/reach/reach-ui/issues/664).

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |     @reach/listbox    |    0.13.0     |
| React            |         |    17.0.1     |
| Browser          |     FF/Chrome    |      84.0.2/88.0.4324.96   |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |   yarn      |     1.22.10    |
| Operating System |    ElementaryOS     |    5.1.7     |

**Comment by chaance** [comment]
This should be fixed in the latest release but let me know if you still have issues.
