### ISSUE TITLE
[Combobox] 📦  Object as ComboboxOption value, for example: Google Places Autosuggest API

### ISSUE THREAD

**Issue by ScottAgirs** [reach/reach-ui#737]
### Current Behavior

Goggle Places Autocomplete returns an array of suggestions.
For each suggestion, we render a `<ComboboxOption />`s where the `value` is set to be whatever we want to display as the label. So far so good.

### But what happens if we need access to the rest of the `suggestion` data? 
This use-case introduces a limitation, whereby passing in a handler function to the 
```javascript
   <Comboxbox onSelect={handlerFunction} />
```
 the only argument that is available within the `handlerFunction` arguments is merely the label itself of the 

```javascript
   <ComboboxOption value={`${suggestion.textPartsAsLabelString}`} />
```

### My suggestion/question/proposal:

The ability to pass in an `object {}` to the `<ComboxboxOption />` alongside a `label` would potentially make this more eloquent.

Or maybe there already exists something that would solve this?

Thank you for this awesome utility!

**Comment by chaance** [comment]
Take a look at the solution in #628. That PR isn't merged, but I show how you can implement this behavior on top of our API in my comment here: https://github.com/reach/reach-ui/pull/628#issuecomment-734966035
