### ISSUE TITLE
[Tooltip] Not able to wrap text

### ISSUE THREAD

**Issue by grandalf6** [reach/reach-ui#743]
### Current Behavior

I am not able to wrap text inside tooltip popup while having tooltip width set.

### Expected behavior

I expect text to be wrapped when tooltip width is set.

### Reproducible example

[Link](https://codesandbox.io/s/condescending-swirles-rd4zk?file=/src/index.js)

### Suggested solution(s)

None

### Additional context

None

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/tooltip     |    0.13.0     |
| React            |     NA    |    16.12.0     |
| Browser          |     Google Chrome    |     Version 87.0.4280.141    |
| Assistive tech   |    none     |     NA    |
| Node             |    NA     |     v10.20.1    |
| npm/yarn         |     NA (codesandbox)  |     NA    |
| Operating System |     Windows    |    10 Pro  |

**Comment by grandalf6** [comment]
It works with:

```css
 white-space: normal;
```

[solution](https://codesandbox.io/s/quizzical-proskuriakova-rg27k)

**Comment by thiemeljiri** [comment]
Hi, unfortunately this causes an infinite loop when the button with the tooltip is close to the right edge of the screen and the tooltip is aligned to the left. This issue should be reopened.
