### ISSUE TITLE
MenuItem could conditionally cause menu to close

### ISSUE THREAD

**Issue by jdanielson-indeed** [reach/reach-ui#744]
### Current Behavior

When a `<MenuItem>` is selected (click or keypress) the `onSelect` callback executes and then the `<Menu>` itself closes.

### Desired Behavior

`<MenuItem>` can conditionally cause the `<Menu>` to close after selection, enabling the menu to stay open after selection. (Potential use case: the menu is a list of checkbox or radio inputs)

### Suggested Solution

`onSelect` callback function determines `<Menu>` close behavior.

Default behavior: the `<Menu>` closes as normal.

Possible ways to prevent `<Menu>` close:

1. Explicitly return `false` from the `onSelect` callback. e.g.
```
onSelect={() => {
  doSomething();

  if (foo) {
    return false;
  }
}}
```
2. `onSelect` takes simple event parameter with a `preventDefault()` field which can be called to stop `<Menu>` close. e.g.
```
onSelect={(evt) => {
  doSomething();

  if (foo) {
    evt.preventDefault();
  }
}}
```

### Who does this impact? Who is this for?

Currently running into a problem using this component because I need the menu to remain open after a menu item is selected, but I cannot.

Interestingly, if the `onSelect` callback throws an error, ReachUI seems to handle the error and prevent the menu from closing... but that is obviously not ideal.

### Describe alternatives you've considered

Implementing my own `<Menu>` component in React specific to my requirements.

### Additional context

I'd be happy to submit an MR for this if it's something that seems reasonable to implement. I'm not sure if this runs afoul of accessibility guidelines or the design philosophy of ReachUI.

**Comment by samueljoli** [comment]
@jdanielson-indeed how did you implement this. I assumed stopping event propagation would work but that doesn't seem to be the case
