### ISSUE TITLE
[Slider] Types lost when wrapping/extending with styled-components

### ISSUE THREAD

**Issue by mrseanbaines** [reach/reach-ui#750]
### Current Behavior

It appears as though type information is lost when wrapping Reach slider components with styled-components (e.g. `const StyledSliderInput = styled(SliderInput)`). There is no autocomplete and no error when e.g. passing a string to the `onChange` props (see picture), while this all works in the unwrapped component.

**Version `0.13.0`:**
![Screenshot_2021-02-20 CodeSandbox](https://user-images.githubusercontent.com/24367010/108601335-fdc70f00-7393-11eb-9f8a-b407bf5e12e0.png)

This seems to be a bug introduced from version `0.12.0` as I get this behaviour on versions above (including latest) but not below.

I've only observed this happening with the Slider component. I'm not sure if it happens with other components.

### Expected behavior

Reach components extended with styled-components should retain their type information. This is the case in versions `0.11.2` and below (see picture).

**Version `0.11.2`:**
![Screenshot_2021-02-20 CodeSandbox(1)](https://user-images.githubusercontent.com/24367010/108601333-fb64b500-7393-11eb-88c4-d9cd403744e3.png)

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/reachslider-ts-bug-wf8oo?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |    @reach/slider     |     0.12.0 (and above)    |
| React            |     react    |    17.0.1     |
| Browser          |    Firefox     |    85.0.2     |
| Assistive tech   |    -     |     -    |
| Node             |    -     |    -     |
| npm/yarn         |     -    |     -    |
| Operating System |    macOS Big Sur     |     11.2.1    |
| Other |    styled-components     |     5.2.1    |
| Other |    @types/styled-components     |     5.1.7    |
| Other |    typescript     |     3.8.3    |

**Comment by chaance** [comment]
Same issue as https://github.com/reach/reach-ui/issues/724 AFAICT, I'll close this but feel free to post it there.

**Comment by mrseanbaines** [comment]
@chaance I'm not sure that is the same issue. #724 seems to be about a TypeScript error showing up (due to incompatible types), whereas this issue is  about TypeScript _not_ throwing any errors when extended with styled-components, or more accurately, losing all type information.

**Comment by marciobarrios** [comment]
I'm having the same problem losing typings when using `styled` (with styled-components), and looks like it's not related to #724 (related to the the way `as` is typed in Reach UI vs Emotion).
