### ISSUE TITLE
forwardRefWithAs in Typescript 4.2

### ISSUE THREAD

**Issue by strass** [reach/reach-ui#753]
## 🐛 Bug report
Keeping this brief and more as a heads up rather than a report since 4.2 just released 2 days ago. My team tried to upgrade and our components that used forwardRefWithAs broke.

Note: we aren't using reach-ui, just your forwardRefWithAs hack

### Current Behavior

After upgrading to Typescript 4.2 [forwardRefWithAs](https://github.com/reach/reach-ui/blob/main/packages/utils/src/index.tsx) has stopped working and components using as get this tsc error `Expression produces a union type that is too complex to represent.`

If we set `as={asProp as 'div'}` on the component then the error goes away, so I think the default type of React.ElementType<any> is now causing issues.

### Expected behavior

forwardRefWithAs is usable with future versions of Typescript

**Comment by chaance** [comment]
Thanks for flagging! Most likely I'll be removing that hack altogether and using https://github.com/kripod/react-polymorphic-types instead, just haven't gotten around to it. If you are using our hack directly I'd suggest forking or going a different route since `@reach/utils` isn't meant for public consumption and can cause a breaking change at any time.

**Comment by strass** [comment]
Thanks for the reply :) it is forked/copy-pasted in our repo I just noticed that it didn't survive the upgrade to 4.2.

I'll try out react-polymorphic-types, thanks for the recommendation!

**Comment by kylemh** [comment]
did it work @strass  👀

**Comment by strass** [comment]
> did it work @strass  👀 

Yeah, it was a shockingly easy conversion. We converted about 16 components of varying complexity from forward ref with as in less than a day

**Comment by chaance** [comment]
This utility was removed in 0.15.0 and issues here should be resolved with the updated types.
