### ISSUE TITLE
[Combobox] Leave suggestions open when clearing input content

### ISSUE THREAD

**Issue by geekus** [reach/reach-ui#759]
### Current Behavior

When clearing the last character in the input field, the internal state changes from `SUGGESTING` to `IDLE`. This does not make sense to me.

### Desired Behavior

As long as the input field has focus, the user is still interested in filling out the field, and should be provided with the possible suggestions. So the popover should not be hidden, but visible, showing all options.

### Suggested Solution

I have not tested, but to me it looks like changing `CLEAR` action when state is `SUGGESTING` from `IDLE` to `SUGGESTING`. https://github.com/reach/reach-ui/blob/develop/packages/combobox/src/index.tsx#L122

As this changes the behavior it might be desirable to leave it as an config option.

### Who does this impact? Who is this for?

Better UX for all users.

### Describe alternatives you've considered

Keep popover open by using CSS, but this is too hacky and I assume there will be side effects by leaving the lib in the wrong internal state.

### Additional context

Nothing more to add.

**Comment by geekus** [comment]
Maybe instead of introducing a new option, it could be possible to make this adjustment for option `openOnFocus`. I think using this option indicates that we'd want the popup with options to be available whenever the field has focus and not just when the input field is clicked.

**Comment by indiesquidge** [comment]
I think this is a duplicate of #709

**Comment by geekus** [comment]
You are right! Tried to do some searching but not enough I guess. Thanks.
