### ISSUE TITLE
[Combox] Is it possible to detect when popover is opened?

### ISSUE THREAD

**Issue by comatory** [reach/reach-ui#760]
##  Callback for setting whether popover is opened or not

I would like to detect when Combobox opened popover. Some kind of callback would be useful. I do not want to clear combobox options on blur and use that as mechanism for detecting whether I'm expecting popover to be opened or not.

**Comment by indiesquidge** [comment]
@comatory #501 added a hook that allowed you to see when the ComboboxPopover is expanded.

**Comment by comatory** [comment]
> @comatory #501 added a hook that allowed you to see when the ComboboxPopover is expanded.

Yeah I know about this. However that hooks is only to be used in child components right? I mean I can work around that by passing a callback to child component and the setting state in parent component when it expands/collapses.

It's just sort of other way around for me since I keep this logic in the parent component.

**Comment by indiesquidge** [comment]
@comatory I'm not sure I understand your follow-up question, can you provide an example of what you're trying to do?

**Comment by comatory** [comment]
```
const MyComboxInput = () => {
  const [ opened, setOpened ] = useState(false)
  
  const { isExpanded } = useComboboxContext()
  
  useEffect(() => {
    setOpened(isExpanded)
   }, [ isExpanded ])
   
   
  
   return (
     <Combobox>
        // other components that need to know whether its opened
        <CustomComboboxWrapper opened={opened} />
     </Combobox>
   )
}
```

In this scenario it cannot be used. I need to move it  somewhere deeper and pass callback to set the state. That's why I was asking if there is some kind of callback for `Combobox` component that could be used.

My use case: I'm manually positioning some absolute elements in this component and I need to know whether it's opened or not. It does not make sense to move this positioning code somewhere else.

**Comment by indiesquidge** [comment]
Is there a reason that "other components that need to know whether its opened" cannot make use of `useComboboxContext` themselves? Anything rendered within the `Combobox` has knowledge of the context provider state.

**Comment by comatory** [comment]
Yeah I see why this was designed the way it was. Unfortunately can't show the code and don't have the time to provide example.
