### ISSUE TITLE
[Menu] Two menus open at the same time

### ISSUE THREAD

**Issue by Schwefelhexa** [reach/reach-ui#762]
### Current Behavior

When one Menu is open, and the MenuButton for the second one is long-clicked, both menus open.

### Expected behavior

The first menu should close.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/young-field-740zz?file=/src/index.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | @reach/menu-button | 0.13.2 |
| React            |         | 17.0.1 |
| Browser          | Chrome | 88.0.4324.190 |
| Assistive tech   |  None   |         |
| Node             |         | 14.15.0 |
| npm/yarn         | yarn | 1.22.10 |
| Operating System | Windows 10 | 2009 (Build 19042.804) |

**Comment by sezeregrek** [comment]
same issue [#566](https://github.com/reach/reach-ui/issues/566)

**Comment by chaance** [comment]
Closing as duplicate, but I'm working on this! https://github.com/reach/reach-ui/issues/566
