### ISSUE TITLE
[MenuButton] Confused about intended click away behaviour

### ISSUE THREAD

**Issue by sanbornhilland** [reach/reach-ui#764]
## ❓Question

I'm unclear about what the intended click away behaviour is for the `MenuButton` component. In the [docs](https://reach.tech/menu-button) that are currently live when I click outside of an open Menu, the Menu closes. However when I installed the latest version (v0.13.2) I need to click outside the menu twice in order to close it. This seems unusual to me but I'll admit I'm not an expert on these MenuButton interactions so maybe this is intentional. #700 claims to have "fixed" this close-on-click-outside behaviour but that seems like a feature to me not a bug.

If this is the intended behaviour, _why_ is this the intended behaviour? It would be great to include a note about this in the docs. I've found the docs really good at teaching some accessibility concerns, beyond just providing API docs, so adding a note about this would be really useful.

**Comment by taifen** [comment]
Looks like a bug. The component works fine with React 17, but not with React 16

https://codesandbox.io/s/reachmenu-button-with-react-17-punio 

https://codesandbox.io/s/reachmenu-button-with-react-16-n42ni

**Comment by sanbornhilland** [comment]
> Looks like a bug. The component works fine with React 17, but not with React 16
> 
> [codesandbox.io/s/reachmenu-button-with-react-17-punio](https://codesandbox.io/s/reachmenu-button-with-react-17-punio)
> 
> [codesandbox.io/s/reachmenu-button-with-react-16-n42ni](https://codesandbox.io/s/reachmenu-button-with-react-16-n42ni)

O good find. We have not been able to update to React 17 yet because of other dependencies that haven't caught up. Is React < 17 intentionally no longer supported or should this get converted to a bug?

**Comment by third774** [comment]
I ran into this last night and suspect this _may have been_ introduced by this PR: https://github.com/reach/reach-ui/pull/740

There were some [changes to React's event delegation](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation) introduced in v17 and maybe they're why this works in v17 but not v16?

**Comment by chaance** [comment]
Closing as a duplicate, but I'm working on this! Please track the issue here https://github.com/reach/reach-ui/issues/566
