### ISSUE TITLE
Edge case: Tooltip alignment assumes <body> not offset from <html> 

### ISSUE THREAD

**Issue by jsg2021** [reach/reach-ui#765]
### Current Behavior
This is an edge case, but I thought I'd bring it up. :)

Tooltips are not aligning correctly in an environment where the root HTML element reserves space for a nav bar and pushes the body elements top offset away from 0... body also set to position relative. The absolute positioned tooltips show up way below their targets.

### Expected behavior

Tooltips show up correctly aligned.

### Reproducible example

https://codesandbox.io/s/zealous-tharp-rvyxc

### Suggested solution(s)

maybe use the bounding client rect of body in calculations?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | tooltip | 0.13.2 |
| React            |         | 16.14.0 |
| Browser          | any | any |
| Assistive tech   | - | - |
| Node             | | 15.11.0 |
| npm/yarn         | npm | 7.6.3 |
| Operating System | fedora | 33 |

**Comment by chaance** [comment]
This should be solvable using the `position` prop that allows you to do your own calculations: https://codesandbox.io/s/lingering-resonance-ymk5c?file=/src/index.js
