### ISSUE TITLE
Click outside not closing menu

### ISSUE THREAD

**Issue by liamjohnston** [reach/reach-ui#768]
### Current Behavior

https://user-images.githubusercontent.com/1134713/112769879-0dff9780-9080-11eb-801c-40e610dcdaf1.mov

### Expected behavior

The first click outside the dropdown should close it.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/adoring-elgamal-m8sj4?file=/src/App.js)

Note: in my codesandbox example this only happens when there are multiple Menus on the page. 

1. Click menu button 1
2. Click menu button 2
3. Click outside. Menu does not close on the first try.

I need to take a closer look at my real example (in my video) to see how it differs. I can't see anything wrong with my code though 🤔  

### Additional context

It seems to happen regardless of whether I use MenuPopover or MenuList (but in this case I am using MenuPopover).

This may relate to #762 and #566 

### Your environment

OS X 10.15.5, Chrome 89 (but also happens in IE11 in browserstack, so don't think it's an OS/browser thing)

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | menu-button | 0.14.0 |
| React            |  | 16.8.6 |
| Browser          | Chrome |   89 |
| Node             |         |  10.6.3 |
| npm/yarn         |  yarn | 1.9.2 |
| Operating System |  OSX | 10.15.5 |

**Comment by sanbornhilland** [comment]
I think it's likely the same issue as #764. In that issue it's noted that the behaviour is correct in React 17+ but not in React 16.

**Comment by chaance** [comment]
Yeah, this will be addressed in the next release. It's my net priority bug to hit.

**Comment by liamjohnston** [comment]
@sanbornhilland Ah, thanks for that info. I just switched to React 17 and my "click outside" issue goes away. You're a life saver!
