### ISSUE TITLE
Migrate to GitHub Actions for CI

### ISSUE THREAD

**Issue by chaance** [reach/reach-ui#771]
I'd like to migrate from Travis to GitHub actions.

Anyone wanna take a stab at this before I mark it as "In Progress", please feel free

**Comment by antoniolofiego** [comment]
I can give it a go tonight, too! Happy to help @MatanBobi :)

**Comment by MatanBobi** [comment]
@chaance Should the github action be triggered only manually? Or you want it to run on every push to branch `develop`?

**Comment by nayaabkhan** [comment]
I don't know if others have already covered good ground, but I'm thinking of giving it a shot as well. 😅

**Comment by nayaabkhan** [comment]
Hey @chaance 👋 

I've submitted a PR for this. I was able to check the step `Test`. But not sure how to test `Release` and `Website` myself.

Also, left comments where maintainer's attention is needed.
