### ISSUE TITLE
[combobox] Error: 'findAll' is not exported by highlight-words-core

### ISSUE THREAD

**Issue by Bartozzz** [reach/reach-ui#776]
## 🐛 Bug report

I cannot create my application's bundle with Rollup when using `@reach/combobox`. It fails to resolve some deep-dependency export:

`Error: 'findAll' is not exported by highlight-words-core`

### Current Behavior

```bash
$ BABEL_ENV=production rollup -c

[!] Error: 'findAll' is not exported by ../../node_modules/highlight-words-core/dist/index.js, imported by ../../node_modules/@reach/combobox/dist/reach-combobox.esm.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

../../node_modules/@reach/combobox/dist/reach-combobox.esm.js (5:9)
3: import { createNamedContext, forwardRefWithAs, makeId, useCheckStyles, isFunction, useUpdateEffect, useForkedRef, getOwnerDocument, useIsomorphicLayoutEffect, wrapEvent, useLazyRef, noop } from '@reach/utils';
4: import { createDescendantContext, useDescendantsInit, DescendantProvider, useDescendant, useDescendants } from '@reach/descendants';
5: import { findAll } from 'highlight-words-core';
            ^
```

### Expected behavior

Should bundle correctly.

### Additional context

`rollup.config.js`:

```js
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
import json from 'rollup-plugin-json'
import resolve from 'rollup-plugin-node-resolve'
import url from 'rollup-plugin-url'

import pkg from './package.json'

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true,
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true,
    },
  ],
  plugins: [
    external(),
    url({
      include: ['**/*.ttf', '**/*.svg', '**/*.png', '**/*.jpg'],
      limit: Infinity,
    }),
    babel({
      exclude: 'node_modules/**',
    }),
    resolve({
      browser: true,
    }),
    commonjs(),
    json(),
  ],
  external: [
    'react',
    'react-dom',
    'react-is',
    'prop-types',
    'styled-components',
    'react-helmet',
    '@react-pdf/renderer',
  ],
  onwarn(warning) {
    // skips warning caused by `i18-js` dependency
    // >> `this` has been rewritten to `undefined`
    if (warning.code === 'THIS_IS_UNDEFINED') {
      return
    }

    // console.warn everything else
    console.warn(warning.message)
  },
}

```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | `@reach/combobox` | `^0.14.0` |
| React            |         | `^16.11.0` |
| Node             |         | LTS |
| npm/yarn         |         | LTS |
| Operating System |         | All |

**Comment by chaance** [comment]
AFAICT we aren't doing anything wrong here. `highlight-words-core`, pinned to 1.2.2, is a listed dependency in Combobox. I checked the source as well as its bundled files, and `findAll` is exported as I would expect.

**Comment by Bartozzz** [comment]
Yes, I debugged it a little and came to the same conclusion. I think it might be related to Rollup, maybe it has some trouble parsing `highlight-words-core/dist/index.js` (generated by Webpack). Adding `@reach/combobox` to `external` configuration option seems to do the job.

**Comment by chaance** [comment]
Good call, I'll close this for now since there's nothing really actionable here. Feel free to open an issue in that repo or let me know if you have any other issues.
