### ISSUE TITLE
Remove -1 `tabIndex` from accordion and disclosure panels

### ISSUE THREAD

**Issue by joshuajaco** [reach/reach-ui#778]
## ❓Question

The `div` rendered by the `DisclosurePanel` component gets a `tabIndex` of `-1` and I don't understand why. It causes it to have a rather ugly looking outline when clicked.

**Comment by chaance** [comment]
I'm not actually sure that this is needed, so good call. Did a quick scan of the ARIA design pattern and I don't see it as a requirement so I think we can safely remove it.
