### ISSUE TITLE
[menu-button]: Composing the MenuButton API, but with Modal characteristics?

### ISSUE THREAD

**Issue by kylemh** [reach/reach-ui#781]
## ❓Question

Our designs have a MenuButton looking drastically different on mobile viewports.

Think typical MenuButton on desktop, but down to [this](https://material.io/components/sheets-bottom#standard-bottom-sheet) on mobile.

I understand why the imperative ability to close the poppers isn't exposed. This should clearly be a modal because of the overlay click desires and the need to disable scrolling; however, it's also clearly a menu of options that expands and collapses.

Should I use the Dialog component and apply additional aria-attributes related to MenuButton or is there a better alternative you can imagine?

**Comment by chaance** [comment]
Yeah, so at the moment what you'd probably need to do is use a Dialog on mobile. But then you'd have to wire up all the list's behavior which isn't really ideal. We probably want a lower level component for selectable lists that can be used independently for this case. I doubt I'll have time to thoughtfully plan that API any time soon, so give me a bit and I'll put together a quick sandbox with an example.
