### ISSUE TITLE
[menu-button] Click outside behavior - should it close the menu?

### ISSUE THREAD

**Issue by sandrina-p** [reach/reach-ui#782]
### Current Behavior

1. Go to the [docs example](https://reach.tech/menu-button/), first example (or any other example)
2. Click the menu trigger "Actions" - The menu list is opened.
3. Click outside the menu (any blank area)

### Expected behavior

I expected the menu list to close.

In reality, I had to click twice outside for the menu to close.

Is that a bug or is there a reason in order to comply with WCAG criteria?

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/recursing-ellis-prgcz?file=/src/index.js)

### Suggested solution(s)

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | 0.15.0        |         |
| React            | 16/17        |         |
| Browser          |  Any browser       |         |
| Assistive tech   | Touch / Mouse        |         |
| Node             |  12       |         |
| npm/yarn         |  6       |         |
| Operating System |  macOS       |         |

**Comment by h0rhay** [comment]
➕ 1 on this.
I have followed advice for similar issues.. and they mentioned updating to latest react and latest version of @reach.
Both of which I have done, but still need to click twice to close.

**Comment by chaance** [comment]
Duplicate, tracking here: https://github.com/reach/reach-ui/issues/566
