### ISSUE TITLE
[combobox]: Options inside `ComboboxPopover` can't be selected when `Combobox` is rendered inside a shadow DOM

### ISSUE THREAD

**Issue by pierlon** [reach/reach-ui#787]
### Current Behavior

When the `Combobox` component is rendered inside a shadow DOM, no options can be selected from the popover. I figure it has something to do with the [`useBlur`](https://github.com/reach/reach-ui/blob/878906eb21aa45f29fe84dd6c72311338e58c127/packages/combobox/src/index.tsx#L1126) function, which is incorrectly using `document` to retrieve the active element, instead of using the shadow root of the shadow DOM it is rendered in.

### Expected behavior

To be able to choose an option from the popover when the `Combobox` is rendered inside a shadow DOM.

### Reproducible example

[CodeSandbox demo](https://codesandbox.io/s/awesome-frost-0zp09?file=/src/App.js)

### Suggested solution(s)

Update [`getOwnerDocument()`](https://github.com/reach/reach-ui/blob/878906eb21aa45f29fe84dd6c72311338e58c127/packages/utils/src/owner-document.ts#L9) to return the root node of the element, which will return the shadow root if the element is within a shadow DOM:

```diff
diff --git a/packages/utils/src/owner-document.ts b/packages/utils/src/owner-document.ts
index 3c05829..3eeb563 100644
--- a/packages/utils/src/owner-document.ts
+++ b/packages/utils/src/owner-document.ts
@@ -9,7 +9,7 @@ import { canUseDOM } from "./can-use-dom";
 export function getOwnerDocument<T extends Element>(
   element: T | null | undefined
 ) {
-  return canUseDOM() ? (element ? element.ownerDocument : document) : null;
+  return canUseDOM() ? (element ? element.getRootNode() : document) : null;
 }
 
 /**
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | @reach/combobox        | 0.14.0        |
| React            | react        |         | 16.14.0
| Browser          | Google Chrome        |   89      |
| Assistive tech   | -        |         |
| Node             | Node        | 14.16.0        |
| npm/yarn         | npm        | 7.6.3        |
| Operating System | Ubuntu        | 20.04        |

**Comment by chaance** [comment]
Should be addressed more simply I think by getting the newly focused element directly from the blur event's `relatedTarget` instead of `document.activeElement`. Let's me get rid of the rAF hack as well as an added bonus. Look for this fix in the next release. https://github.com/reach/reach-ui/commit/a51134ca4cbfbc37020ab983ba787b02e1707016

**Comment by pierlon** [comment]
Thanks @chaance!
