### ISSUE TITLE
Peer Dependency Issues for React 17.0.2

### ISSUE THREAD

**Issue by tannerhuynh** [reach/reach-ui#795]
### Current Behavior

```
warning "@reach/dialog > react-focus-lock > react-clientside-effect@1.2.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning "@reach/dialog > react-focus-lock > use-callback-ref@1.2.4" has incorrect peer dependency "react@^16.8.0".
warning "@reach/dialog > react-focus-lock > use-sidecar@1.0.2" has incorrect peer dependency "react@^16.8.0".
warning "@reach/dialog > react-remove-scroll > react-remove-scroll-bar@2.1.0" has incorrect peer dependency "react@^16.8.0".
warning "@reach/dialog > react-remove-scroll > react-style-singleton@2.1.0" has incorrect peer dependency "react@^16.8.0".
```

The latest updated peer dependency does not seem to be working for this particular component.

### Expected behavior

Updated peer dependencies should work with React 17.0.2.

### Reproducible example

We are importing components individually as needed.

```
"@reach/dialog": "^0.15.0",
```

Run yarn on version 0.15.0

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |   0.15.0      |
| React            |         |     17.0.2    |
| Browser          |     Chrome    |     90    |
| Assistive tech   |         |         |
| Node             |         |    10.24.0     |
| npm/yarn         |         |    1.22.4     |
| Operating System |    Mac     |   BigSur      |

**Comment by clementbalestrat** [comment]
Any updates on this? I'm having the issue too.

**Comment by andrewnystrom** [comment]
I, too, would like to know if there is an update on this.

**Comment by IanVS** [comment]
Some of this would be solved by updating your yarn.lock or package-lock.json, I believe.  For instance, `@reach/dialog` depends on `react-focus-lock@^2.5.0`, which depends on `react-clientside-effect@^1.2.2`, and version `1.2.3` of that package (which is in-range) includes react 17 in peerDependencies.  I didn't check the other packages, but it's possible that some or all of the others are in the same situation.

**Comment by andrewnystrom** [comment]
> Some of this would be solved by updating your yarn.lock or package-lock.json, I believe. For instance, `@reach/dialog` depends on `react-focus-lock@^2.5.0`, which depends on `react-clientside-effect@^1.2.2`, and version `1.2.3` of that package (which is in-range) includes react 17 in peerDependencies. I didn't check the other packages, but it's possible that some or all of the others are in the same situation.

@IanVS Could you please clarify what you mean by editing the `yarn.lock` file? The first line in this file is: 
`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.`

**Comment by IanVS** [comment]
No I don't think you should edit it directly.  But I find that I need to periodically update my transitive dependencies.  One way I've done this in the past is by deleting my yarn.lock, regenerating it, and thoroughly QA testing my app to ensure there haven't been any breaking changes which did not follow semver.  You can also pin your direct dependencies to specific versions if you don't want to allow them to update according to semver.  That way, removing your lock and recreating it would only update transitive dependencies.

**Comment by chaance** [comment]
We've updated our dependencies in 0.15.3 and it looks like all of the packages that trigger these warnings have also updated their supported version to add 17.0.
