### ISSUE TITLE
[menu-button] Popover does not consistently close when clicking between Menu Buttons using MenuPopover component

### ISSUE THREAD

**Issue by iliatcymbal** [reach/reach-ui#802]
Issue is still reproduced if we use `MenuPopover` instead of `MenuList`. 
https://codesandbox.io/s/friendly-darwin-zf50o?file=/src/index.js

![popoverIssues](https://user-images.githubusercontent.com/6584990/120697949-08c32c80-c4b7-11eb-9ce6-5c749ca2967c.gif)

_Originally posted by @iliatcymbal in https://github.com/reach/reach-ui/issues/566#issuecomment-854104312_

**Comment by chaance** [comment]
You still need to use `MenuItems`. See my response here: https://github.com/reach/reach-ui/issues/566#issuecomment-854766894
