### ISSUE TITLE
Codeblock support in tab content

### ISSUE THREAD

**Issue by velhari** [reach/reach-ui#809]
Hi,

It will be good to have codeblock support inside the tab content in this library. Is this support is there already?

Thanks,

**Comment by chaance** [comment]
Hey, thanks for opening an issue! I'm not sure what you mean by this exactly, but if you just mean using `<code>` inside of `TabPanel` then that's definitely possible through regular old composition.

```js
function Example() {
  return (
    <Tabs>
      <TabList>
        <Tab>One</Tab>
        <Tab>Two</Tab>
      </TabList>

      <TabPanels>
        <TabPanel>
          <code>let code = 'awesome';</code>
        </TabPanel>
        <TabPanel>
          <pre dangerouslySetInnerHtml={{ __html: `let preformattedCode = 'cool';` }}></pre>
        </TabPanel>
      </TabPanels>
    </Tabs>
  );
}
```
