### ISSUE TITLE
Upgrading @reach/menu-button from v0.15.1 to v0.15.3 throws a garbage collection error on my build

### ISSUE THREAD

**Issue by deltaepsilon** [reach/reach-ui#819]
I'm using TS and NextJS. I've been upgrading @reach/menu-button for nearly a year, and this most recent patch finally broke me.

![image](https://user-images.githubusercontent.com/878947/126194648-58b8f192-b014-40bd-8f71-b4b7903f9a8c.png)

**Comment by arshad** [comment]
I'm seeing the same issue. Similar setup: Next.js, TypeScript and Reach UI `0.15.3`.

```json
"dependencies": {
  "@reach/alert-dialog": "^0.15.3",
  "@reach/checkbox": "^0.15.3",
  "@reach/dialog": "^0.15.3",
  "@reach/menu-button": "^0.15.3",
  "@reach/slider": "^0.15.3",
  "@reach/tabs": "^0.15.3",
  "next": "^11.0.1",
  "react": "^17.0.2",
  "react-dom": "^17.0.2"
},
```

Downgrading to `0.15.0` for now.

**Comment by chaance** [comment]
Could either of you please post what version of Node you're working with? I'll try to take a look this weekend, as I'm planning another release with `menu-button` ASAP.

**Comment by arshad** [comment]
I’ve tested with Node 14 and 16.

**Comment by chaance** [comment]
I've set up a Next app with `npx create-next-app --ts` and installed those exact dependencies @arshad. Before each install attempt I deleted `node_modules` and the lockfile to ensure I'm starting fresh. All run via macOS. No issues.

If you can create a minimal reproduction repo and use the table in the issue template to give me a closer idea of what environment is giving you trouble, I can reopen this and take another look. As you can see this starts to get really tedious to debug when I don't know all of the software you're running when these issues arise, so please use the templates. They help me help you! 🙏 

| Node | npm 6.14.14 | npm 7.20.3 | yarn 1.20.3 |
| -- | -- | -- | -- | 
| 12.22.4 | ✅  | ✅ | ✅ |
| 14.17.4 | ✅  | ✅ | ✅ |
| 16.6.0 | ✅  | ✅ | ✅ | 

![image](https://user-images.githubusercontent.com/3082153/127745351-6e660692-b267-455f-8cef-be47e40d95db.png)
