### ISSUE TITLE
[combobox] Support combobox options with identical values

### ISSUE THREAD

**Issue by JohannesFischer** [reach/reach-ui#826]
### Current Behavior

Combobox uses the options value to find the current navigation item when navigating the combobox list using the keyboard. Having multiple options with the same value will highlight all options with matching value when selected. This also makes it impossible to navigate the full list using the keyboard as the selection jumps back to the first or last  matching option (depending on the direction). 

### Desired Behavior

Multiple options with the same value should not affect keyboard navigation.

### Suggested Solution

Add a number index to track the current navigation item, additionally to the `navigationLabel` or instead of it and expose it via `useComboboxContext`.

### Who does this impact? Who is this for?

Probably advanced users.

### Describe alternatives you've considered

N/A

### Additional context

Duplicated items might be the exception but in my use case the options are grouped in categories in which sub items are not necessarily unique.

A simplified example:

```
Option Group A
- Option 1
- Option 2
Option Group B
- Option 3
- Option 1
```

Basic example of combobox with duplicated items: https://codesandbox.io/s/spring-fog-x9lv9?file=/src/App.js

**Comment by sballesteros** [comment]
@JohannesFischer I am having a similar issue. Have you found a workaround by any chance or do we need to create a pull request?
@chaance could you re-open the issue (it is niche but for cases when you cannot deduplicate values having support for identical values would be great)?

**Comment by chaance** [comment]
New features are not in the pipeline right now, as I don't have time to implement them and no one else is maintaining the lib at the moment. If you need this feature, you'll either need to fork or use another library. 

That said, if someone wants to implement it and includes tests to ensure that everything works as expected, I'd be happy to review that.
