### ISSUE TITLE
ComboBox a11y bug

### ISSUE THREAD

**Issue by tannerhuynh** [reach/reach-ui#835]
## 🐛 Bug report
Combobox is not following a11y convention.

### Current Behavior
The input is the combobox and maintains all the aria types for combobox.

```
<div data-reach-combobox="" data-state="idle" data-dashlane-rid="b545fd378b85726b" data-form-type="other">
<input aria-autocomplete="both" aria-controls="listbox--5" aria-expanded="false" aria-haspopup="listbox" role="combobox" data-reach-combobox-input="" data-state="idle" value="" style="width: 300px; margin: 0px;" data-dashlane-rid="2cc65e2daf8a5c39" data-form-type="other">
</div>
```

### Expected behavior
Per https://www.w3.org/TR/wai-aria-1.1/#combobox, the combox should instead contain or own the input which has a role of textbox or searchbox (this should be a choice).

```
<div aria-label="Tag" role="combobox" aria-expanded="true" aria-owns="owned_listbox" aria-haspopup="listbox">
    <input type="text" aria-autocomplete="list" aria-controls="owned_listbox" aria-activedescendant="selected_option">
</div>
<ul role="listbox" id="owned_listbox">
    <li role="option">Zebra</li>
    <li role="option" id="selected_option">Zoom</li>
</ul>
```

### Reproducible example
Just implement the current Reach UI combobox and look at the DOM.

### Suggested solution(s)

As suggested in https://www.w3.org/TR/wai-aria-1.1/#combobox and https://dequeuniversity.com/rules/axe/4.2/aria-required-children?application=axeAPI

**Comment by indiesquidge** [comment]
Hey @tannerhuynh, thanks for your bug report! Please see https://github.com/reach/reach-ui/pull/479 which goes into detail on why we're following the 1.2 Candidate Recommendation, rather than 1.1 (you'll also see 1.2 listed on the [documentation][1]). Having the `combobox` role exist on the input itself is indeed intentional.

[1]: https://reach.tech/combobox

**Comment by tannerhuynh** [comment]
Thank you!
