### ISSUE TITLE
[Listbox] Support for multiple values

### ISSUE THREAD

**Issue by wojtekmaj** [reach/reach-ui#855]
### Current Behavior

Listbox allows selecting one element only.

### Desired Behavior

Listbox component to accept prop `multiple`, or MultiListbox component to be created

### Who does this impact? Who is this for?

All users

### Describe alternatives you've considered

Building a custom solution using Menu component. I failed miserably: either it works for mouse users only (impl 1) or closes itself after each selection (impl 2) 😫 

Here are my takes:

https://codesandbox.io/s/reach-menu-multiselect-b80xs

### Additional context

This is what I'm trying to build - a dropdown for filtering purposes. I feel like this would be a fairly common use case.

![image](https://user-images.githubusercontent.com/5426427/138870293-7a5d3634-f834-49d7-93a0-4572f56c3050.png)

My company would be interested in sponsoring implementation of this feature. Please let me know if that's something you'd be interested in.

**Comment by wojtekmaj** [comment]
@chaance - how do you feel about this proposal? I'm eagerly looking forward to your reply.

**Comment by wojtekmaj** [comment]
@chaance - how do you feel about this proposal? I'm eagerly looking forward to your reply.

**Comment by chaance** [comment]
A little late to this. No issues with the proposal on first read (I appreciate the detailed writeup!). Full disclosure though, my time to work on this lib is pretty limited these days and it'll likely take a while to get back to new features. I'll keep this open for consideration when we can get to it.
