### ISSUE TITLE
Menu button inside a dialog takes 2 clicks to open

### ISSUE THREAD

**Issue by honestbonsai** [reach/reach-ui#862]
### Current Behavior

Using a MenuButton in a Dialog needs 2 clicks to open the menu.

I have a MenuButton not in a Dialog and it works as expected with a single click.

### Expected behavior

It should only take 1 click.

### Additional context

Might be related to #830 and #808

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   @reach/menu-button      |    0.16.1     |
| Reach Package    |   @reach/dialog      |    0.16.0     |
| React            |         |  17.0.1       |
| Browser          |   Chrome      |         |
| Node             |         |   16.1.0      |
| npm/yarn         |         |    1.22.10     |
| Operating System |   Mac      |    11.6     |

**Comment by honestbonsai** [comment]
On further investigation, it seems like this was resolved in #808. Just the official docs haven't been updated. For anyone with the same issue, you can look at: https://github.com/reach/reach-ui/blob/develop/packages/menu-button/examples/inside-dialog.example.tsx

**Comment by YauheniKhadanionak** [comment]
UPD: new link for file with example https://github.com/reach/reach-ui/blob/v0.18.0/playground/stories/menu-button/inside-dialog.example.tsx
