### ISSUE TITLE
[Dialog] Add prop to specify the root of the dialog

### ISSUE THREAD

**Issue by everdimension** [reach/reach-ui#87]
I noticed that currently you cannot specify the root for the dialog to be rendered into https://github.com/reach/reach-ui/blob/master/packages/portal/src/index.js#L10

The `body` element is hardcoded to the <Portal /> component.

I would very much like to see this feature. It's very important for apps that get integrated into other apps.

Would you accept a PR implementing this?

**Comment by everdimension** [comment]
@denkristoffer No, I haven't yet. I wanted to make sure that the project wants this first. But I guess it wouldn't hurt if you want to send a PR before that

**Comment by denkristoffer** [comment]
I currently need this functionality so I would have to build something to do it either way 🙂 I've started work on this in #88, would like to hear your thoughts if you have any.

**Comment by ryanflorence** [comment]
let's continue the conversation in #88
