### ISSUE TITLE
[Listbox] Support nodes as labels

### ISSUE THREAD

**Issue by rogorman9** [reach/reach-ui#882]
### Current Behavior
The `label` prop on `ListboxOption` only accepts `string`s at the moment. For my use case, I need to render an SVG in that spot. At the moment, the SVG does render correctly but it breaks the typeahead functionality since Reach tries to call `option.label.toLowerCase()`. 

### Desired Behavior
`label` should accept a `ReactNode`. 

### Suggested Solution
`label` should be able to accept a `ReactNode` and extract the text from that for the typeahead functionality. Alternatively, `Listbox` could accept a prop that disables typeahead to avoid breaking for non-string `label`s. 

### Who does this impact? Who is this for?
Myself, as well as anyone who would like to render something other than text when the Listbox is closed. 

### Describe alternatives you've considered
This can be done manually via the `button` prop, but it would be nice for the component to handle this automatically.

**Comment by indiesquidge** [comment]
@rogorman9 can you provide an [example CodeSandbox][1] of what you're trying to accomplish? The `label` prop intentionally only takes in human-readable text, and `children` can be used if your option has multiple text nodes that may or may not correlate with the intended value.

Is there a reason something like this will not work for you?

```jsx
<Listbox>
  <ListboxOption value="asada" label="Carne Asada">
    <SVG /> Carne Asada
  </ListboxOption>
  <ListboxOption value="pollo" label="Pollo">
    <SVG /> Pollo
  </ListboxOption>
</Listbox>
```

[1]: https://codesandbox.io/s/reach-ui-template-xonfs
