### ISSUE TITLE
Deprecate `@reach/auto-id` package once React 18 is live

### ISSUE THREAD

**Issue by MichaelDeBoey** [reach/reach-ui#887]
Since the `useId` hook will be available in React 18, the `@reach/auto-id` package can be deprecated once it's live.

Ref: https://github.com/reactwg/react-18/discussions/111
Ref: https://reactjs.org/docs/hooks-reference.html#useid

**Comment by MichaelDeBoey** [comment]
@stephyswe This is not a PR, so this isn't implemented yet & should work fine as before.

**Comment by chaance** [comment]
I doubt we'll deprecate it either way. It can still be useful as a utility for other libs that support both React 17 + 18 or use the fallback parameter to support user-provided IDs. I'd think of this as a slightly higher-level abstraction for R18.
