### ISSUE TITLE
[AlertDialog][Mobile] Button overflows Dialog

### ISSUE THREAD

**Issue by chaimsalzer** [reach/reach-ui#89]
On mobile devices, the dialog is too thin, and the button overflows. 
`width: 80%;` instead of `width: 50vw;` seems to do the trick while looking good on both mobile and desktop
![ui reach tech_alert-dialog](https://user-images.githubusercontent.com/7330622/48024169-95af7900-e148-11e8-80d3-fad65db9a2d5.png)

**Comment by ryanflorence** [comment]
Should probably have a media query or something for the default alert dialog width, want to add it? it's in `alert-dialog/src/styles.css` I think.

Closing in hopes of a PR popping up elsewhere :)
