### ISSUE TITLE
Weird scrollbar on the website

### ISSUE THREAD

**Issue by gunar** [reach/reach-ui#90]
![image](https://user-images.githubusercontent.com/7684574/48350162-785d3c00-e66d-11e8-8398-1e45555155cf.png)

Running on Chromium Version 70.0.3538.77 (Official Build) Arch Linux (64-bit)

**Comment by ryanflorence** [comment]
It's got overflow: auto, probably an OS setting you have to always show scroll bars?

**Comment by gunar** [comment]
Good ol' "works on my computer" eh? :)

I learned the disabled scrollbar disappears if I shrink the window until the sidebar is hidden then grow it again.

Thought you might wanted to know. Anyway, your call. Thanks.

---

![uireach2-2019-01-05_18 04 38 mp4](https://user-images.githubusercontent.com/7684574/50728660-7b782400-1114-11e9-828d-39369cda347d.gif)
