### ISSUE TITLE
Extra span in portal triggering flex issues.

### ISSUE THREAD

**Issue by kentcdodds** [reach/reach-ui#902]
### Current Behavior

I've got a menu button inside a flex container. [This extra span](https://github.com/reach/reach-ui/blob/07d815040f95d192225bac7fff2432fb26f7f90b/packages/portal/src/index.tsx#L75-L79) is causing me grief (layout shift):

https://user-images.githubusercontent.com/1500684/150923102-da21486c-28d5-4e0d-8d85-39deb09ffc6c.mov

Here's what it looks like *before* hydration:

![image](https://user-images.githubusercontent.com/1500684/150922669-8bf3b024-2a23-4dd0-b1d9-38b7b295f794.png)

Here it is after hydration:

![image](https://user-images.githubusercontent.com/1500684/150922649-ebed2f00-5eed-4588-a812-f8a4850842e3.png)

### Expected behavior

Wrapping the button in a flex container makes the sibling span trigger a content shift.

### Reproducible example

https://stackblitz.com/edit/node-qppzt9?file=app%2Froot.tsx

### Suggested solution(s)

Maybe don't render anything on the server render?

A workaround (that I'm implementing) is to wrap the `<Menu>` inside a `<div>` so the sibling span doesn't end up messing up the flex flow. But this was surprising.

### Additional context

This seems to only be a problem when server rendering.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  @reach/portal and @reach/menu  |  latest       |
| React            |   dom   |   17   |
| Browser          |   any  | any |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by artursvonda** [comment]
Similar issue but causes warnings when rendered in context where span is not suited (like tbody).

**Comment by chaance** [comment]
I'm thinking we should add a prop to `Portal` (and by extension, all portal'd components) that skips mounting before hydration. That's probably the right default for menu button and listbox since neither of these dropdowns need to be rendered on the server anyway.

**Comment by chaance** [comment]
Fixed in v0.17.0
