### ISSUE TITLE
Reach/Menu-Button hover example does not work with modern version

### ISSUE THREAD

**Issue by ml242** [reach/reach-ui#917]
### Current Behavior

I am trying to implement the example hover from the code sandbox example:
https://codesandbox.io/embed/reach-ui-hover-dropdown-bzid5

As you can see it works fine with react 16 and version .1. 
If you bump that to the newest flavor of 0.16.2, it will not function.

### Expected behavior

hover opens menu button

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/reach-ui-template-xonfs)

### Suggested solution(s)

synthetic event should still open dropdown.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |  0.16.2 |
| React            |         17.0.2         |
| Browser          |        chrome         |
| Assistive tech   |         |         |
| Node             |         |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chaance** [comment]
This is not a feature of our menu button. Button menus and hover menus work a bit differently from an accessibility standpoint, so I'd advise against using Reach for this component.

I may implement a hover menu in the future, but it's not something we have on the todo list at the moment.
