### ISSUE TITLE
Question on Browser Support

### ISSUE THREAD

**Issue by jkdowdle** [reach/reach-ui#94]
Is there a list of browsers that reach ui will plan on supporting?

I love the library and hope to use it on my current project in production however I noticed that the MenuButton dropdown does not seem to be working on my project. 

It is not working in my app or on in the demo on the website. https://ui.reach.tech/menu-button. Once you press the button the menu does not show up. It is giving me the missing styles warning probably because ie11 does not support css variables. Not sure though if that is also messing with the data-reach-menu container that is positioned absolute. 

Edge appears to be working as expected. 

Thank you.

**Comment by ryanflorence** [comment]
I haven't done extensive browser testing yet, but the plan is the same support as React itself.

**Comment by ryanflorence** [comment]
would love for somebody to do some testing between browsers to make sure the default styles are working cross browser :)

**Comment by Glazy** [comment]
As a follow up to this we should add a page or section to the Reach UI docs that details the supported browsers :+1: @ryanflorence, if you want me to add a page with your plan for now then let me know :smile:

**Comment by jkdowdle** [comment]
@ryanflorence 

Thank you for getting to this. As I do my own cross browser testing I will do my best to give you feedback. Other than the dropdown just not opening up, I think the all the styles are consistent other than the default browser outline for active elements. 

Not sure how consistent you want them to be but In chrome of course it is a blue highlight, in ie11 its like a black dotted border. Where these are browser defaults I think this is the right way to go. 

Button animation looks right.

![image](https://user-images.githubusercontent.com/19804196/50925421-8205e480-140f-11e9-9b6a-22c430833e51.png)

@Glazy
I think it would be beneficial to have this info somewhere in the docs, thank you.
