### ISSUE TITLE
Docs for component-component didUpdate should say `prevProps` not `nextProps`

### ISSUE THREAD

**Issue by ncknuna** [reach/reach-ui#95]
Just an FYI that the docs for `didUpdate` on https://ui.reach.tech/component-component#didupdate say that it takes a `nextProps` and `nextState` rather than `prevProps` and `prevState`

**Comment by ryanflorence** [comment]
Thanks, mind sending a quick PR?

**Comment by ncknuna** [comment]
https://github.com/reach/reach-ui/pull/101
