### ISSUE TITLE
menu-button: add `component` prop (on MenuButton)

### ISSUE THREAD

**Issue by VinceMalone** [reach/reach-ui#96]
Like `MenuLink`, it would be nice to add a `component` prop on `MenuButton`. This would allow [abstractions through components] to be used with `MenuButton`; for example:

1. Styles (that don't, **or can't**, rely on the `[data-*]` approach)

```jsx
<MenuButton component={MyFancyButton} theme="really-fancy" />
```

2. Button components that care about various events (like `focus`) as they relate to the MenuButton components; e.g. show a tooltip on focus.

```jsx
<MenuButton component={ButtonThatDoesShitOnFocus} />
```

**Comment by Pau1fitz** [comment]
I think I have a similar use case, or else perhaps it is possible to do this already.

I have a logout component that looks like the following:

```js
import React from 'react';
// this has come from from useReducer
import { useDispatch } from '../store';

const Logout = () => {
	const dispatch = useDispatch();
	const performLogout = (): void => {
		dispatch({
			type: 'LOGOUT_SUCCESS',
		});
	};

	return (
		<div onClick={performLogout}>Logout</div>
	);
};

export default Logout;
```

I then import this into my `Menu`.

```js
import React from 'react';
import {Menu, MenuList, MenuButton, MenuItem } from "@reach/menu-button";

const Dropdown = () => {
	return(
		<Menu>
			<MenuButton>
				Select
			</MenuButton>
			<MenuList>
				<MenuItem onSelect={() => alert("Settings")}>Settings
				</MenuItem>
				<MenuItem onSelect={() => performLogout()}>
					Logout
				</MenuItem>
			</MenuList>
		</Menu>
	);
};

export default Dropdown;
```

Is there anyway to call the method defined in my `Logout` component?

**Comment by ryanflorence** [comment]
closing in favor of the PR, thanks!
