### ISSUE TITLE
Not able to run yarn install after cloning the repo

### ISSUE THREAD

**Issue by SwarajGK** [reach/reach-ui#962]
### Current Behavior

<img width="724" alt="Screenshot 2022-08-29 at 3 04 31 PM" src="https://user-images.githubusercontent.com/52201115/187171555-eb07e2db-8c08-4adc-a598-09063451c7fc.png">

### Expected behavior
It should run yarn install and install all the deps

Should install modules and can build the project

### Suggested solution(s)

As per my understanding, this is not able resolve `https://registry.yarnpkg.com/@reach-internal%2ftest` which is `https://registry.yarnpkg.com/@reach-internal/test` so have to look into why this is happening while doing yarn install

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |         |         |
| React            |         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |    v16.16.0     |         |
| npm/yarn         |   Yarn      |     1.22.19    |
| Operating System |    Macos     |     Monterey    |

**Comment by jeanpan** [comment]
It's updated to use `pnpm`. You can check this [PR](https://github.com/reach/reach-ui/pull/954/files). Hope it can be merged soon.
