### ISSUE TITLE
menu-button: issue when using the key "space"

### ISSUE THREAD

**Issue by baptooo** [reach/reach-ui#99]
Hello, I would like to report an issue on the component `MenuButton` when navigating with a keyboard.

Component: https://ui.reach.tech/menu-button

**Actual behavior:**
When using the key `space` to validate a value the pages scroll.

**Desired behavior:**
When using the key `space` the value currently highlighted is chosen and the list is hidden.

Have a nice day !

**Comment by ryanflorence** [comment]
Ah, yes, want to open a PR for this? Should be straightforward, just `event.preventDefault()` on `event.key === " "`.

**Comment by bradd123** [comment]
Is it still open? I'd like to contribute here.

**Comment by chancestrickland** [comment]
Should be fixed with #156
